function getURL(urlKeyCode){
switch (urlKeyCode){
    case "chicago||a3":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
   case "chicago||a3-cabriolet":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
   case "chicago||a3-e-tron":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
   case "chicago||a3-e-tron-sportback":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
   case "chicago||a4":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
   case "chicago||a5":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=A5&make=Audi";
   case "chicago||a5-cabriolet":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
   case "chicago||a5-coupe":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
   case "chicago||a5-sportback":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
   case "chicago||a6":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
   case "chicago||a7":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
   case "chicago||a7-hatchback":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
   case "chicago||a8":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
   case "chicago||allroad":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
   case "chicago||q3":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
   case "chicago||q5":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
   case "chicago||q7":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
   case "chicago||q8":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
   case "chicago||r8":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
   case "chicago||r8-convertible":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
   case "chicago||rs5":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
   case "chicago||rs5-convertible":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
   case "chicago||rs7":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
   case "chicago||s3":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
   case "chicago||s4":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
   case "chicago||s5":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
   case "chicago||s5-cabriolet":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
   case "chicago||s5-sportback":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
   case "chicago||s6":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
   case "chicago||s7":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
   case "chicago||s8":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
   case "chicago||sq5":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
   case "chicago||tt-coupe":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
   case "chicago||tt-roadster":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
   case "chicago||tts-coupe":
        return "https://www.audioffers.com/chicagoland/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
   case "cincinnati||a3":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
   case "cincinnati||a3-cabriolet":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
   case "cincinnati||a3-e-tron":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
   case "cincinnati||a3-e-tron-sportback":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
   case "cincinnati||a4":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
   case "cincinnati||a5":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=A5&make=Audi";
   case "cincinnati||a5-cabriolet":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
   case "cincinnati||a5-coupe":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
   case "cincinnati||a5-sportback":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
   case "cincinnati||a6":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
   case "cincinnati||a7":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
   case "cincinnati||a7-hatchback":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
   case "cincinnati||a8":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
   case "cincinnati||allroad":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
   case "cincinnati||q3":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
   case "cincinnati||q5":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
   case "cincinnati||q7":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
   case "cincinnati||q8":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
   case "cincinnati||r8":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
   case "cincinnati||r8-convertible":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
   case "cincinnati||rs5":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
   case "cincinnati||rs5-convertible":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
   case "cincinnati||rs7":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
   case "cincinnati||s3":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
   case "cincinnati||s4":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
   case "cincinnati||s5":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
   case "cincinnati||s5-cabriolet":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
   case "cincinnati||s5-sportback":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
   case "cincinnati||s6":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
   case "cincinnati||s7":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
   case "cincinnati||s8":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
   case "cincinnati||sq5":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
   case "cincinnati||tt-coupe":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
   case "cincinnati||tt-roadster":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
   case "cincinnati||tts-coupe":
        return "https://www.audioffers.com/cincinnati/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
   case "cleveland||a3":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
   case "cleveland||a3-cabriolet":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
   case "cleveland||a3-e-tron":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
   case "cleveland||a3-e-tron-sportback":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
   case "cleveland||a4":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
   case "cleveland||a5":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=A5&make=Audi";
   case "cleveland||a5-cabriolet":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
   case "cleveland||a5-coupe":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
   case "cleveland||a5-sportback":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
   case "cleveland||a6":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
   case "cleveland||a7":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
   case "cleveland||a7-hatchback":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
   case "cleveland||a8":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
   case "cleveland||allroad":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
   case "cleveland||q3":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
   case "cleveland||q5":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
   case "cleveland||q7":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
   case "cleveland||q8":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
   case "cleveland||r8":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
   case "cleveland||r8-convertible":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
   case "cleveland||rs5":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
   case "cleveland||rs5-convertible":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
   case "cleveland||rs7":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
   case "cleveland||s3":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
   case "cleveland||s4":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
   case "cleveland||s5":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
   case "cleveland||s5-cabriolet":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
   case "cleveland||s5-sportback":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
   case "cleveland||s6":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
   case "cleveland||s7":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
   case "cleveland||s8":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
   case "cleveland||sq5":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
   case "cleveland||tt-coupe":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
   case "cleveland||tt-roadster":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
   case "cleveland||tts-coupe":
        return "https://www.audioffers.com/cleveland/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
   case "columbus||a3":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
   case "columbus||a3-cabriolet":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
   case "columbus||a3-e-tron":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
   case "columbus||a3-e-tron-sportback":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
   case "columbus||a4":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
   case "columbus||a5":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=A5&make=Audi";
   case "columbus||a5-cabriolet":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
   case "columbus||a5-coupe":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
   case "columbus||a5-sportback":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
   case "columbus||a6":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
   case "columbus||a7":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
   case "columbus||a7-hatchback":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
   case "columbus||a8":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
   case "columbus||allroad":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
   case "columbus||q3":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
   case "columbus||q5":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
   case "columbus||q7":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
   case "columbus||q8":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
   case "columbus||r8":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
   case "columbus||r8-convertible":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
   case "columbus||rs5":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
   case "columbus||rs5-convertible":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
   case "columbus||rs7":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
   case "columbus||s3":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
   case "columbus||s4":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
   case "columbus||s5":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
   case "columbus||s5-cabriolet":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
   case "columbus||s5-sportback":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
   case "columbus||s6":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
   case "columbus||s7":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
   case "columbus||s8":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
   case "columbus||sq5":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
   case "columbus||tt-coupe":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
   case "columbus||tt-roadster":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
   case "columbus||tts-coupe":
        return "https://www.audioffers.com/columbus/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
   case "detroit||a3":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
   case "detroit||a3-cabriolet":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
   case "detroit||a3-e-tron":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
   case "detroit||a3-e-tron-sportback":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
   case "detroit||a4":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
   case "detroit||a5":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=A5&make=Audi";
   case "detroit||a5-cabriolet":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
   case "detroit||a5-coupe":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
   case "detroit||a5-sportback":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
   case "detroit||a6":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
   case "detroit||a7":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
   case "detroit||a7-hatchback":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
   case "detroit||a8":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
   case "detroit||allroad":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
   case "detroit||q3":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
   case "detroit||q5":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
   case "detroit||q7":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
   case "detroit||q8":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
   case "detroit||r8":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
   case "detroit||r8-convertible":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
   case "detroit||rs5":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
   case "detroit||rs5-convertible":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
   case "detroit||rs7":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
   case "detroit||s3":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
   case "detroit||s4":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
   case "detroit||s5":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
   case "detroit||s5-cabriolet":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
   case "detroit||s5-sportback":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
   case "detroit||s6":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
   case "detroit||s7":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
   case "detroit||s8":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
   case "detroit||sq5":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
   case "detroit||tt-coupe":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
   case "detroit||tt-roadster":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
   case "detroit||tts-coupe":
        return "https://www.audioffers.com/detroit/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
   case "grand-rapids||a3":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
   case "grand-rapids||a3-cabriolet":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
   case "grand-rapids||a3-e-tron":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
   case "grand-rapids||a3-e-tron-sportback":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
   case "grand-rapids||a4":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
   case "grand-rapids||a5":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=A5&make=Audi";
   case "grand-rapids||a5-cabriolet":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
   case "grand-rapids||a5-coupe":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
   case "grand-rapids||a5-sportback":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
   case "grand-rapids||a6":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
   case "grand-rapids||a7":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
   case "grand-rapids||a7-hatchback":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
   case "grand-rapids||a8":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
   case "grand-rapids||allroad":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
   case "grand-rapids||q3":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
   case "grand-rapids||q5":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
   case "grand-rapids||q7":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
   case "grand-rapids||q8":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
   case "grand-rapids||r8":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
   case "grand-rapids||r8-convertible":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
   case "grand-rapids||rs5":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
   case "grand-rapids||rs5-convertible":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
   case "grand-rapids||rs7":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
   case "grand-rapids||s3":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
   case "grand-rapids||s4":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
   case "grand-rapids||s5":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
   case "grand-rapids||s5-cabriolet":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
   case "grand-rapids||s5-sportback":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
   case "grand-rapids||s6":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
   case "grand-rapids||s7":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
   case "grand-rapids||s8":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
   case "grand-rapids||sq5":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
   case "grand-rapids||tt-coupe":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
   case "grand-rapids||tt-roadster":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
   case "grand-rapids||tts-coupe":
        return "https://www.audigrandrapids.com/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
   case "indianapolis||a3":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
   case "indianapolis||a3-cabriolet":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
   case "indianapolis||a3-e-tron":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
   case "indianapolis||a3-e-tron-sportback":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
   case "indianapolis||a4":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
   case "indianapolis||a5":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=A5&make=Audi";
   case "indianapolis||a5-cabriolet":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
   case "indianapolis||a5-coupe":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
   case "indianapolis||a5-sportback":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
   case "indianapolis||a6":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
   case "indianapolis||a7":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
   case "indianapolis||a7-hatchback":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
   case "indianapolis||a8":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
   case "indianapolis||allroad":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
   case "indianapolis||q3":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
   case "indianapolis||q5":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
   case "indianapolis||q7":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
   case "indianapolis||q8":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
   case "indianapolis||r8":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
   case "indianapolis||r8-convertible":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
   case "indianapolis||rs5":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
   case "indianapolis||rs5-convertible":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
   case "indianapolis||rs7":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
   case "indianapolis||s3":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
   case "indianapolis||s4":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
   case "indianapolis||s5":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
   case "indianapolis||s5-cabriolet":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
   case "indianapolis||s5-sportback":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
   case "indianapolis||s6":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
   case "indianapolis||s7":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
   case "indianapolis||s8":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
   case "indianapolis||sq5":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
   case "indianapolis||tt-coupe":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
   case "indianapolis||tt-roadster":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
   case "indianapolis||tts-coupe":
        return "https://www.audiindianapolis.com/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
   case "kansas-city||a3":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi&geoZip=64114";
   case "kansas-city||a3-cabriolet":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi&geoZip=64114";
   case "kansas-city||a3-e-tron":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi&geoZip=64114";
   case "kansas-city||a3-e-tron-sportback":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi&geoZip=64114";
   case "kansas-city||a4":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi&geoZip=64114";
   case "kansas-city||a5":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=A5&make=Audi&geoZip=64114";
   case "kansas-city||a5-cabriolet":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi&geoZip=64114";
   case "kansas-city||a5-coupe":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi&geoZip=64114";
   case "kansas-city||a5-sportback":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback&geoZip=64114";
   case "kansas-city||a6":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi&geoZip=64114";
   case "kansas-city||a7":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi&geoZip=64114";
   case "kansas-city||a7-hatchback":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi&geoZip=64114";
   case "kansas-city||a8":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi&geoZip=64114";
   case "kansas-city||allroad":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi&geoZip=64114";
   case "kansas-city||q3":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi&geoZip=64114";
   case "kansas-city||q5":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi&geoZip=64114";
   case "kansas-city||q7":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi&geoZip=64114";
   case "kansas-city||q8":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi&geoZip=64114";
   case "kansas-city||r8":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi&geoZip=64114";
   case "kansas-city||r8-convertible":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi&geoZip=64114";
   case "kansas-city||rs5":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi&geoZip=64114";
   case "kansas-city||rs5-convertible":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi&geoZip=64114";
   case "kansas-city||rs7":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi&geoZip=64114";
   case "kansas-city||s3":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi&geoZip=64114";
   case "kansas-city||s4":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi&geoZip=64114";
   case "kansas-city||s5":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi&geoZip=64114";
   case "kansas-city||s5-cabriolet":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi&geoZip=64114";
   case "kansas-city||s5-sportback":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi&geoZip=64114";
   case "kansas-city||s6":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi&geoZip=64114";
   case "kansas-city||s7":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi&geoZip=64114";
   case "kansas-city||s8":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi&geoZip=64114";
   case "kansas-city||sq5":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi&geoZip=64114";
   case "kansas-city||tt-coupe":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi&geoZip=64114";
   case "kansas-city||tt-roadster":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi&geoZip=64114";
   case "kansas-city||tts-coupe":
        return "http://www.audioffers.com/kansas-city/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi&geoZip=64114";
   case "louisville||a3":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
   case "louisville||a3-cabriolet":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
   case "louisville||a3-e-tron":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
   case "louisville||a3-e-tron-sportback":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
   case "louisville||a4":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
   case "louisville||a5":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=A5&make=Audi";
   case "louisville||a5-cabriolet":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
   case "louisville||a5-coupe":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
   case "louisville||a5-sportback":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
   case "louisville||a6":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
   case "louisville||a7":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
   case "louisville||a7-hatchback":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
   case "louisville||a8":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
   case "louisville||allroad":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
   case "louisville||q3":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
   case "louisville||q5":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
   case "louisville||q7":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
   case "louisville||q8":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
   case "louisville||r8":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
   case "louisville||r8-convertible":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
   case "louisville||rs5":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
   case "louisville||rs5-convertible":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
   case "louisville||rs7":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
   case "louisville||s3":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
   case "louisville||s4":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
   case "louisville||s5":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
   case "louisville||s5-cabriolet":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
   case "louisville||s5-sportback":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
   case "louisville||s6":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
   case "louisville||s7":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
   case "louisville||s8":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
   case "louisville||sq5":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
   case "louisville||tt-coupe":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
   case "louisville||tt-roadster":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
   case "louisville||tts-coupe":
        return "https://www.audilouisville.com/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
   case "minneapolis||a3":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi&geoZip=55109";
   case "minneapolis||a3-cabriolet":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi&geoZip=55109";
   case "minneapolis||a3-e-tron":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi&geoZip=55109";
   case "minneapolis||a3-e-tron-sportback":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi&geoZip=55109";
   case "minneapolis||a4":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi&geoZip=55109";
   case "minneapolis||a5":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=A5&make=Audi&geoZip=55109";
   case "minneapolis||a5-cabriolet":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi&geoZip=55109";
   case "minneapolis||a5-coupe":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi&geoZip=55109";
   case "minneapolis||a5-sportback":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback&geoZip=55109";
   case "minneapolis||a6":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi&geoZip=55109";
   case "minneapolis||a7":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi&geoZip=55109";
   case "minneapolis||a7-hatchback":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi&geoZip=55109";
   case "minneapolis||a8":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi&geoZip=55109";
   case "minneapolis||allroad":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi&geoZip=55109";
   case "minneapolis||q3":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi&geoZip=55109";
   case "minneapolis||q5":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi&geoZip=55109";
   case "minneapolis||q7":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi&geoZip=55109";
   case "minneapolis||q8":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi&geoZip=55109";
   case "minneapolis||r8":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi&geoZip=55109";
   case "minneapolis||r8-convertible":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi&geoZip=55109";
   case "minneapolis||rs5":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi&geoZip=55109";
   case "minneapolis||rs5-convertible":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi&geoZip=55109";
   case "minneapolis||rs7":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi&geoZip=55109";
   case "minneapolis||s3":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi&geoZip=55109";
   case "minneapolis||s4":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi&geoZip=55109";
   case "minneapolis||s5":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi&geoZip=55109";
   case "minneapolis||s5-cabriolet":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi&geoZip=55109";
   case "minneapolis||s5-sportback":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi&geoZip=55109";
   case "minneapolis||s6":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi&geoZip=55109";
   case "minneapolis||s7":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi&geoZip=55109";
   case "minneapolis||s8":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi&geoZip=55109";
   case "minneapolis||sq5":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi&geoZip=55109";
   case "minneapolis||tt-coupe":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi&geoZip=55109";
   case "minneapolis||tt-roadster":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi&geoZip=55109";
   case "minneapolis||tts-coupe":
        return "https://www.audioffers.com/twin-cities/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi&geoZip=55109";
   case "st-louis||a3":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
   case "st-louis||a3-cabriolet":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
   case "st-louis||a3-e-tron":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
   case "st-louis||a3-e-tron-sportback":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
   case "st-louis||a4":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
   case "st-louis||a5":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=A5&make=Audi";
   case "st-louis||a5-cabriolet":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
   case "st-louis||a5-coupe":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
   case "st-louis||a5-sportback":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
   case "st-louis||a6":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
   case "st-louis||a7":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
   case "st-louis||a7-hatchback":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
   case "st-louis||a8":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
   case "st-louis||allroad":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
   case "st-louis||q3":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
   case "st-louis||q5":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
   case "st-louis||q7":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
   case "st-louis||q8":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
   case "st-louis||r8":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
   case "st-louis||r8-convertible":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
   case "st-louis||rs5":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
   case "st-louis||rs5-convertible":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
   case "st-louis||rs7":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
   case "st-louis||s3":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
   case "st-louis||s4":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
   case "st-louis||s5":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
   case "st-louis||s5-cabriolet":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
   case "st-louis||s5-sportback":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
   case "st-louis||s6":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
   case "st-louis||s7":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
   case "st-louis||s8":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
   case "st-louis||sq5":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
   case "st-louis||tt-coupe":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
   case "st-louis||tt-roadster":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
   case "st-louis||tts-coupe":
        return "https://www.audioffers.com/st-louis/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
   case "toledo||a3":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
   case "toledo||a3-cabriolet":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
   case "toledo||a3-e-tron":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
   case "toledo||a3-e-tron-sportback":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
   case "toledo||a4":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
   case "toledo||a5":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=A5&make=Audi";
   case "toledo||a5-cabriolet":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
   case "toledo||a5-coupe":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
   case "toledo||a5-sportback":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
   case "toledo||a6":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
   case "toledo||a7":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
   case "toledo||a7-hatchback":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
   case "toledo||a8":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
   case "toledo||allroad":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
   case "toledo||q3":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
   case "toledo||q5":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
   case "toledo||q7":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
   case "toledo||q8":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
   case "toledo||r8":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
   case "toledo||r8-convertible":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
   case "toledo||rs5":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
   case "toledo||rs5-convertible":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
   case "toledo||rs7":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
   case "toledo||s3":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
   case "toledo||s4":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
   case "toledo||s5":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
   case "toledo||s5-cabriolet":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
   case "toledo||s5-sportback":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
   case "toledo||s6":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
   case "toledo||s7":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
   case "toledo||s8":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
   case "toledo||sq5":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
   case "toledo||tt-coupe":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
   case "toledo||tt-roadster":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
   case "toledo||tts-coupe":
        return "https://www.sylvaniaaudi.com/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
   case "wichita||a3":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
   case "wichita||a3-cabriolet":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
   case "wichita||a3-e-tron":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
   case "wichita||a3-e-tron-sportback":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
   case "wichita||a4":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
   case "wichita||a5":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=A5&make=Audi";
   case "wichita||a5-cabriolet":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
   case "wichita||a5-coupe":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
   case "wichita||a5-sportback":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
   case "wichita||a6":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
   case "wichita||a7":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
   case "wichita||a7-hatchback":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
   case "wichita||a8":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
   case "wichita||allroad":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
   case "wichita||q3":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
   case "wichita||q5":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
   case "wichita||q7":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
   case "wichita||q8":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
   case "wichita||r8":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
   case "wichita||r8-convertible":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
   case "wichita||rs5":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
   case "wichita||rs5-convertible":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
   case "wichita||rs7":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
   case "wichita||s3":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
   case "wichita||s4":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
   case "wichita||s5":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
   case "wichita||s5-cabriolet":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
   case "wichita||s5-sportback":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
   case "wichita||s6":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
   case "wichita||s7":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
   case "wichita||s8":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
   case "wichita||sq5":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
   case "wichita||tt-coupe":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
   case "wichita||tt-roadster":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
   case "wichita||tts-coupe":
        return "https://www.audiwichita.com/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
   default:
        return "https://www.audioffers.com";
    }
}

