console.log("loaded");
function getURL(urlKeyCode){
switch (urlKeyCode){
    case 'albany||a3':
        return "https://www.audialbany.com/showroom/2019/Audi/A3/Sedan.htm";
    case 'albany||a3-cabriolet':
        return "https://www.audialbany.com/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'albany||a3-e-tron':
        return "https://www.audialbany.com/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'albany||a4':
        return "https://www.audialbany.com/showroom/2019/Audi/A4/Sedan.htm";
    case 'albany||a4-allroad':
        return "https://www.audialbany.com/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'albany||a5':
        return "https://www.audialbany.com/showroom/2019/Audi/A5/Sedan.htm";
    case 'albany||a5-cabriolet':
        return "https://www.audialbany.com/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'albany||a5-coupe':
        return "https://www.audialbany.com/showroom/2019/Audi/A5/Coupe.htm";
    case 'albany||a5-sportback':
        return "https://www.audialbany.com/showroom/2019/Audi/A5/Sportback.htm";
    case 'albany||a6':
        return "https://www.audialbany.com/showroom/2019/Audi/A6/Sedan.htm";
    case 'albany||a7':
        return "https://www.audialbany.com/showroom/2019/Audi/A7/Hatchback.htm";
    case 'albany||a7-hatchback':
        return "https://www.audialbany.com/showroom/2019/Audi/A7/Hatchback.htm";
    case 'albany||a8':
        return "https://www.audialbany.com/showroom/2019/Audi/A8/Sedan.htm";
    case 'albany||q3':
        return "https://www.audialbany.com/showroom/2019/Audi/Q3/SUV.htm";
    case 'albany||q5':
        return "https://www.audialbany.com/showroom/2019/Audi/Q5/SUV.htm";
    case 'albany||q7':
        return "https://www.audialbany.com/showroom/2019/Audi/Q7/SUV.htm";
    case 'albany||q8':
        return "https://www.audialbany.com/showroom/2019/Audi/Q8/SUV.htm";
    case 'albany||rs3':
        return "https://www.audialbany.com/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'albany||rs7-hatchback':
        return "https://www.audialbany.com/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'albany||s3':
        return "https://www.audialbany.com/showroom/2019/Audi/S3/Sedan.htm";
    case 'albany||s4':
        return "https://www.audialbany.com/showroom/2019/Audi/S4/Sedan.htm";
    case 'albany||s5-cabriolet':
        return "https://www.audialbany.com/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'albany||s5-coupe':
        return "https://www.audialbany.com/showroom/2019/Audi/S5/Coupe.htm";
    case 'albany||s5-sportback':
        return "https://www.audialbany.com/showroom/2019/Audi/S5/Sportback.htm";
    case 'albany||s6':
        return "https://www.audialbany.com/showroom/2019/Audi/S6/Sedan.htm";
    case 'albany||s7-hatchback':
        return "https://www.audialbany.com/showroom/2019/Audi/S7/Hatchback.htm";
    case 'albany||s8':
        return "https://www.audialbany.com/showroom/2019/Audi/S8/Sedan.htm";
    case 'albany||tt-coupe':
        return "https://www.audialbany.com/showroom/2019/Audi/TT/Coupe.htm";
    case 'albany||tts-coupe':
        return "https://www.audialbany.com/showroom/2019/Audi/TTS/Coupe.htm";
    case 'delaware-valley||a3':
        return "https://www.audioffers.com/delaware-valley/showroom/2019/Audi/A3/Sedan.htm";
    case 'delaware-valley||a3-cabriolet':
        return "https://www.audioffers.com/delaware-valley/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'delaware-valley||a3-e-tron':
        return "https://www.audioffers.com/delaware-valley/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'delaware-valley||a4':
        return "https://www.audioffers.com/delaware-valley/showroom/2019/Audi/A4/Sedan.htm";
    case 'delaware-valley||a4-allroad':
        return "https://www.audioffers.com/delaware-valley/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'delaware-valley||a5':
        return "https://www.audioffers.com/delaware-valley/showroom/2019/Audi/A5/Sedan.htm";
    case 'delaware-valley||a5-cabriolet':
        return "https://www.audioffers.com/delaware-valley/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'delaware-valley||a5-coupe':
        return "https://www.audioffers.com/delaware-valley/showroom/2019/Audi/A5/Coupe.htm";
    case 'delaware-valley||a5-sportback':
        return "https://www.audioffers.com/delaware-valley/showroom/2019/Audi/A5/Sportback.htm";
    case 'delaware-valley||a6':
        return "https://www.audioffers.com/delaware-valley/showroom/2019/Audi/A6/Sedan.htm";
    case 'delaware-valley||a7':
        return "https://www.audioffers.com/delaware-valley/showroom/2019/Audi/A7/Hatchback.htm";
    case 'delaware-valley||a7-hatchback':
        return "https://www.audioffers.com/delaware-valley/showroom/2019/Audi/A7/Hatchback.htm";
    case 'delaware-valley||a8':
        return "https://www.audioffers.com/delaware-valley/showroom/2019/Audi/A8/Sedan.htm";
    case 'delaware-valley||q3':
        return "https://www.audioffers.com/delaware-valley/showroom/2019/Audi/Q3/SUV.htm";
    case 'delaware-valley||q5':
        return "https://www.audioffers.com/delaware-valley/showroom/2019/Audi/Q5/SUV.htm";
    case 'delaware-valley||q7':
        return "https://www.audioffers.com/delaware-valley/showroom/2019/Audi/Q7/SUV.htm";
    case 'delaware-valley||q8':
        return "https://www.audioffers.com/delaware-valley/showroom/2019/Audi/Q8/SUV.htm";
    case 'delaware-valley||rs3':
        return "https://www.audioffers.com/delaware-valley/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'delaware-valley||rs7-hatchback':
        return "https://www.audioffers.com/delaware-valley/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'delaware-valley||s3':
        return "https://www.audioffers.com/delaware-valley/showroom/2019/Audi/S3/Sedan.htm";
    case 'delaware-valley||s4':
        return "https://www.audioffers.com/delaware-valley/showroom/2019/Audi/S4/Sedan.htm";
    case 'delaware-valley||s5-cabriolet':
        return "https://www.audioffers.com/delaware-valley/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'delaware-valley||s5-coupe':
        return "https://www.audioffers.com/delaware-valley/showroom/2019/Audi/S5/Coupe.htm";
    case 'delaware-valley||s5-sportback':
        return "https://www.audioffers.com/delaware-valley/showroom/2019/Audi/S5/Sportback.htm";
    case 'delaware-valley||s6':
        return "https://www.audioffers.com/delaware-valley/showroom/2019/Audi/S6/Sedan.htm";
    case 'delaware-valley||s7-hatchback':
        return "https://www.audioffers.com/delaware-valley/showroom/2019/Audi/S7/Hatchback.htm";
    case 'delaware-valley||s8':
        return "https://www.audioffers.com/delaware-valley/showroom/2019/Audi/S8/Sedan.htm";
    case 'delaware-valley||tt-coupe':
        return "https://www.audioffers.com/delaware-valley/showroom/2019/Audi/TT/Coupe.htm";
    case 'delaware-valley||tts-coupe':
        return "https://www.audioffers.com/delaware-valley/showroom/2019/Audi/TTS/Coupe.htm";
    case 'hartford||a3':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2019/Audi/A3/Sedan.htm";
    case 'hartford||a3-cabriolet':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'hartford||a3-e-tron':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'hartford||a4':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2019/Audi/A4/Sedan.htm";
    case 'hartford||a4-allroad':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'hartford||a5':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2019/Audi/A5/Sedan.htm";
    case 'hartford||a5-cabriolet':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'hartford||a5-coupe':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2019/Audi/A5/Coupe.htm";
    case 'hartford||a5-sportback':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2019/Audi/A5/Sportback.htm";
    case 'hartford||a6':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2019/Audi/A6/Sedan.htm";
    case 'hartford||a7':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2019/Audi/A7/Hatchback.htm";
    case 'hartford||a7-hatchback':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2019/Audi/A7/Hatchback.htm";
    case 'hartford||a8':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2019/Audi/A8/Sedan.htm";
    case 'hartford||q3':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2019/Audi/Q3/SUV.htm";
    case 'hartford||q5':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2019/Audi/Q5/SUV.htm";
    case 'hartford||q7':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2019/Audi/Q7/SUV.htm";
    case 'hartford||q8':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2019/Audi/Q8/SUV.htm";
    case 'hartford||rs3':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'hartford||rs7-hatchback':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'hartford||s3':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2019/Audi/S3/Sedan.htm";
    case 'hartford||s4':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2019/Audi/S4/Sedan.htm";
    case 'hartford||s5-cabriolet':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'hartford||s5-coupe':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2019/Audi/S5/Coupe.htm";
    case 'hartford||s5-sportback':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2019/Audi/S5/Sportback.htm";
    case 'hartford||s6':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2019/Audi/S6/Sedan.htm";
    case 'hartford||s7-hatchback':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2019/Audi/S7/Hatchback.htm";
    case 'hartford||s8':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2019/Audi/S8/Sedan.htm";
    case 'hartford||tt-coupe':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2019/Audi/TT/Coupe.htm";
    case 'hartford||tts-coupe':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2019/Audi/TTS/Coupe.htm";
    case 'new-england||a3':
        return "https://www.audioffers.com/new-england/showroom/2019/Audi/A3/Sedan.htm";
    case 'new-england||a3-cabriolet':
        return "https://www.audioffers.com/new-england/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'new-england||a3-e-tron':
        return "https://www.audioffers.com/new-england/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'new-england||a4':
        return "https://www.audioffers.com/new-england/showroom/2019/Audi/A4/Sedan.htm";
    case 'new-england||a4-allroad':
        return "https://www.audioffers.com/new-england/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'new-england||a5':
        return "https://www.audioffers.com/new-england/showroom/2019/Audi/A5/Sedan.htm";
    case 'new-england||a5-cabriolet':
        return "https://www.audioffers.com/new-england/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'new-england||a5-coupe':
        return "https://www.audioffers.com/new-england/showroom/2019/Audi/A5/Coupe.htm";
    case 'new-england||a5-sportback':
        return "https://www.audioffers.com/new-england/showroom/2019/Audi/A5/Sportback.htm";
    case 'new-england||a6':
        return "https://www.audioffers.com/new-england/showroom/2019/Audi/A6/Sedan.htm";
    case 'new-england||a7':
        return "https://www.audioffers.com/new-england/showroom/2019/Audi/A7/Hatchback.htm";
    case 'new-england||a7-hatchback':
        return "https://www.audioffers.com/new-england/showroom/2019/Audi/A7/Hatchback.htm";
    case 'new-england||a8':
        return "https://www.audioffers.com/new-england/showroom/2019/Audi/A8/Sedan.htm";
    case 'new-england||q3':
        return "https://www.audioffers.com/new-england/showroom/2019/Audi/Q3/SUV.htm";
    case 'new-england||q5':
        return "https://www.audioffers.com/new-england/showroom/2019/Audi/Q5/SUV.htm";
    case 'new-england||q7':
        return "https://www.audioffers.com/new-england/showroom/2019/Audi/Q7/SUV.htm";
    case 'new-england||q8':
        return "https://www.audioffers.com/new-england/showroom/2019/Audi/Q8/SUV.htm";
    case 'new-england||rs3':
        return "https://www.audioffers.com/new-england/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'new-england||rs7-hatchback':
        return "https://www.audioffers.com/new-england/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'new-england||s3':
        return "https://www.audioffers.com/new-england/showroom/2019/Audi/S3/Sedan.htm";
    case 'new-england||s4':
        return "https://www.audioffers.com/new-england/showroom/2019/Audi/S4/Sedan.htm";
    case 'new-england||s5-cabriolet':
        return "https://www.audioffers.com/new-england/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'new-england||s5-coupe':
        return "https://www.audioffers.com/new-england/showroom/2019/Audi/S5/Coupe.htm";
    case 'new-england||s5-sportback':
        return "https://www.audioffers.com/new-england/showroom/2019/Audi/S5/Sportback.htm";
    case 'new-england||s6':
        return "https://www.audioffers.com/new-england/showroom/2019/Audi/S6/Sedan.htm";
    case 'new-england||s7-hatchback':
        return "https://www.audioffers.com/new-england/showroom/2019/Audi/S7/Hatchback.htm";
    case 'new-england||s8':
        return "https://www.audioffers.com/new-england/showroom/2019/Audi/S8/Sedan.htm";
    case 'new-england||tt-coupe':
        return "https://www.audioffers.com/new-england/showroom/2019/Audi/TT/Coupe.htm";
    case 'new-england||tts-coupe':
        return "https://www.audioffers.com/new-england/showroom/2019/Audi/TTS/Coupe.htm";
    case 'pittsburgh||a3':
        return "https://www.audioffers.com/pittsburgh/showroom/2019/Audi/A3/Sedan.htm";
    case 'pittsburgh||a3-cabriolet':
        return "https://www.audioffers.com/pittsburgh/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'pittsburgh||a3-e-tron':
        return "https://www.audioffers.com/pittsburgh/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'pittsburgh||a4':
        return "https://www.audioffers.com/pittsburgh/showroom/2019/Audi/A4/Sedan.htm";
    case 'pittsburgh||a4-allroad':
        return "https://www.audioffers.com/pittsburgh/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'pittsburgh||a5':
        return "https://www.audioffers.com/pittsburgh/showroom/2019/Audi/A5/Sedan.htm";
    case 'pittsburgh||a5-cabriolet':
        return "https://www.audioffers.com/pittsburgh/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'pittsburgh||a5-coupe':
        return "https://www.audioffers.com/pittsburgh/showroom/2019/Audi/A5/Coupe.htm";
    case 'pittsburgh||a5-sportback':
        return "https://www.audioffers.com/pittsburgh/showroom/2019/Audi/A5/Sportback.htm";
    case 'pittsburgh||a6':
        return "https://www.audioffers.com/pittsburgh/showroom/2019/Audi/A6/Sedan.htm";
    case 'pittsburgh||a7':
        return "https://www.audioffers.com/pittsburgh/showroom/2019/Audi/A7/Hatchback.htm";
    case 'pittsburgh||a7-hatchback':
        return "https://www.audioffers.com/pittsburgh/showroom/2019/Audi/A7/Hatchback.htm";
    case 'pittsburgh||a8':
        return "https://www.audioffers.com/pittsburgh/showroom/2019/Audi/A8/Sedan.htm";
    case 'pittsburgh||q3':
        return "https://www.audioffers.com/pittsburgh/showroom/2019/Audi/Q3/SUV.htm";
    case 'pittsburgh||q5':
        return "https://www.audioffers.com/pittsburgh/showroom/2019/Audi/Q5/SUV.htm";
    case 'pittsburgh||q7':
        return "https://www.audioffers.com/pittsburgh/showroom/2019/Audi/Q7/SUV.htm";
    case 'pittsburgh||q8':
        return "https://www.audioffers.com/pittsburgh/showroom/2019/Audi/Q8/SUV.htm";
    case 'pittsburgh||rs3':
        return "https://www.audioffers.com/pittsburgh/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'pittsburgh||rs7-hatchback':
        return "https://www.audioffers.com/pittsburgh/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'pittsburgh||s3':
        return "https://www.audioffers.com/pittsburgh/showroom/2019/Audi/S3/Sedan.htm";
    case 'pittsburgh||s4':
        return "https://www.audioffers.com/pittsburgh/showroom/2019/Audi/S4/Sedan.htm";
    case 'pittsburgh||s5-cabriolet':
        return "https://www.audioffers.com/pittsburgh/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'pittsburgh||s5-coupe':
        return "https://www.audioffers.com/pittsburgh/showroom/2019/Audi/S5/Coupe.htm";
    case 'pittsburgh||s5-sportback':
        return "https://www.audioffers.com/pittsburgh/showroom/2019/Audi/S5/Sportback.htm";
    case 'pittsburgh||s6':
        return "https://www.audioffers.com/pittsburgh/showroom/2019/Audi/S6/Sedan.htm";
    case 'pittsburgh||s7-hatchback':
        return "https://www.audioffers.com/pittsburgh/showroom/2019/Audi/S7/Hatchback.htm";
    case 'pittsburgh||s8':
        return "https://www.audioffers.com/pittsburgh/showroom/2019/Audi/S8/Sedan.htm";
    case 'pittsburgh||tt-coupe':
        return "https://www.audioffers.com/pittsburgh/showroom/2019/Audi/TT/Coupe.htm";
    case 'pittsburgh||tts-coupe':
        return "https://www.audioffers.com/pittsburgh/showroom/2019/Audi/TTS/Coupe.htm";
    case 'providence||a3':
        return "http://www.audioffers.com/east/showroom/2019/Audi/A3/Sedan.htm?geoZip=02886";
    case 'providence||a3-cabriolet':
        return "http://www.audioffers.com/east/showroom/2019/Audi/A3/Cabriolet.htm?geoZip=02886";
    case 'providence||a3-e-tron':
        return "http://www.audioffers.com/east/showroom/2019/Audi/A3+e-tron/Hatchback.htm?geoZip=02886";
    case 'providence||a4':
        return "http://www.audioffers.com/east/showroom/2019/Audi/A4/Sedan.htm?geoZip=02886";
    case 'providence||a4-allroad':
        return "http://www.audioffers.com/east/showroom/2019/Audi/A4+allroad/Wagon.htm?geoZip=02886";
    case 'providence||a5':
        return "http://www.audioffers.com/east/showroom/2019/Audi/A5/Sedan.htm?geoZip=02886";
    case 'providence||a5-cabriolet':
        return "http://www.audioffers.com/east/showroom/2019/Audi/A5/Cabriolet.htm?geoZip=02886";
    case 'providence||a5-coupe':
        return "http://www.audioffers.com/east/showroom/2019/Audi/A5/Coupe.htm?geoZip=02886";
    case 'providence||a5-sportback':
        return "http://www.audioffers.com/east/showroom/2019/Audi/A5/Sportback.htm?geoZip=02886";
    case 'providence||a6':
        return "http://www.audioffers.com/east/showroom/2019/Audi/A6/Sedan.htm?geoZip=02886";
    case 'providence||a7':
        return "http://www.audioffers.com/east/showroom/2019/Audi/A7/Hatchback.htm?geoZip=02886";
    case 'providence||a7-hatchback':
        return "http://www.audioffers.com/east/showroom/2019/Audi/A7/Hatchback.htm?geoZip=02886";
    case 'providence||a8':
        return "http://www.audioffers.com/east/showroom/2019/Audi/A8/Sedan.htm?geoZip=02886";
    case 'providence||q3':
        return "http://www.audioffers.com/east/showroom/2019/Audi/Q3/SUV.htm?geoZip=02886";
    case 'providence||q5':
        return "http://www.audioffers.com/east/showroom/2019/Audi/Q5/SUV.htm?geoZip=02886";
    case 'providence||q7':
        return "http://www.audioffers.com/east/showroom/2019/Audi/Q7/SUV.htm?geoZip=02886";
    case 'providence||q8':
        return "http://www.audioffers.com/east/showroom/2019/Audi/Q8/SUV.htm?geoZip=02886";
    case 'providence||rs3':
        return "http://www.audioffers.com/east/showroom/2019/Audi/RS+3/Sedan.htm?geoZip=02886";
    case 'providence||rs7-hatchback':
        return "http://www.audioffers.com/east/showroom/2019/Audi/RS+7/Hatchback.htm?geoZip=02886";
    case 'providence||s3':
        return "http://www.audioffers.com/east/showroom/2019/Audi/S3/Sedan.htm?geoZip=02886";
    case 'providence||s4':
        return "http://www.audioffers.com/east/showroom/2019/Audi/S4/Sedan.htm?geoZip=02886";
    case 'providence||s5-cabriolet':
        return "http://www.audioffers.com/east/showroom/2019/Audi/S5/Cabriolet.htm?geoZip=02886";
    case 'providence||s5-coupe':
        return "http://www.audioffers.com/east/showroom/2019/Audi/S5/Coupe.htm?geoZip=02886";
    case 'providence||s5-sportback':
        return "http://www.audioffers.com/east/showroom/2019/Audi/S5/Sportback.htm?geoZip=02886";
    case 'providence||s6':
        return "http://www.audioffers.com/east/showroom/2019/Audi/S6/Sedan.htm?geoZip=02886";
    case 'providence||s7-hatchback':
        return "http://www.audioffers.com/east/showroom/2019/Audi/S7/Hatchback.htm?geoZip=02886";
    case 'providence||s8':
        return "http://www.audioffers.com/east/showroom/2019/Audi/S8/Sedan.htm?geoZip=02886";
    case 'providence||tt-coupe':
        return "http://www.audioffers.com/east/showroom/2019/Audi/TT/Coupe.htm?geoZip=02886";
    case 'providence||tts-coupe':
        return "http://www.audioffers.com/east/showroom/2019/Audi/TTS/Coupe.htm?geoZip=02886";
    case 'tri-state||a3':
        return "https://www.audioffers.com/tri-state/showroom/2019/Audi/A3/Sedan.htm";
    case 'tri-state||a3-cabriolet':
        return "https://www.audioffers.com/tri-state/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'tri-state||a3-e-tron':
        return "https://www.audioffers.com/tri-state/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'tri-state||a4':
        return "https://www.audioffers.com/tri-state/showroom/2019/Audi/A4/Sedan.htm";
    case 'tri-state||a4-allroad':
        return "https://www.audioffers.com/tri-state/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'tri-state||a5':
        return "https://www.audioffers.com/tri-state/showroom/2019/Audi/A5/Sedan.htm";
    case 'tri-state||a5-cabriolet':
        return "https://www.audioffers.com/tri-state/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'tri-state||a5-coupe':
        return "https://www.audioffers.com/tri-state/showroom/2019/Audi/A5/Coupe.htm";
    case 'tri-state||a5-sportback':
        return "https://www.audioffers.com/tri-state/showroom/2019/Audi/A5/Sportback.htm";
    case 'tri-state||a6':
        return "https://www.audioffers.com/tri-state/showroom/2019/Audi/A6/Sedan.htm";
    case 'tri-state||a7':
        return "https://www.audioffers.com/tri-state/showroom/2019/Audi/A7/Hatchback.htm";
    case 'tri-state||a7-hatchback':
        return "https://www.audioffers.com/tri-state/showroom/2019/Audi/A7/Hatchback.htm";
    case 'tri-state||a8':
        return "https://www.audioffers.com/tri-state/showroom/2019/Audi/A8/Sedan.htm";
    case 'tri-state||q3':
        return "https://www.audioffers.com/tri-state/showroom/2019/Audi/Q3/SUV.htm";
    case 'tri-state||q5':
        return "https://www.audioffers.com/tri-state/showroom/2019/Audi/Q5/SUV.htm";
    case 'tri-state||q7':
        return "https://www.audioffers.com/tri-state/showroom/2019/Audi/Q7/SUV.htm";
    case 'tri-state||q8':
        return "https://www.audioffers.com/tri-state/showroom/2019/Audi/Q8/SUV.htm";
    case 'tri-state||rs3':
        return "https://www.audioffers.com/tri-state/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'tri-state||rs7-hatchback':
        return "https://www.audioffers.com/tri-state/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'tri-state||s3':
        return "https://www.audioffers.com/tri-state/showroom/2019/Audi/S3/Sedan.htm";
    case 'tri-state||s4':
        return "https://www.audioffers.com/tri-state/showroom/2019/Audi/S4/Sedan.htm";
    case 'tri-state||s5-cabriolet':
        return "https://www.audioffers.com/tri-state/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'tri-state||s5-coupe':
        return "https://www.audioffers.com/tri-state/showroom/2019/Audi/S5/Coupe.htm";
    case 'tri-state||s5-sportback':
        return "https://www.audioffers.com/tri-state/showroom/2019/Audi/S5/Sportback.htm";
    case 'tri-state||s6':
        return "https://www.audioffers.com/tri-state/showroom/2019/Audi/S6/Sedan.htm";
    case 'tri-state||s7-hatchback':
        return "https://www.audioffers.com/tri-state/showroom/2019/Audi/S7/Hatchback.htm";
    case 'tri-state||s8':
        return "https://www.audioffers.com/tri-state/showroom/2019/Audi/S8/Sedan.htm";
    case 'tri-state||tt-coupe':
        return "https://www.audioffers.com/tri-state/showroom/2019/Audi/TT/Coupe.htm";
    case 'tri-state||tts-coupe':
        return "https://www.audioffers.com/tri-state/showroom/2019/Audi/TTS/Coupe.htm";
    case 'albany||a6':
        return "https://www.audialbany.com/showroom/2020/Audi/A6/Sedan.htm";
    case 'delaware-valley||a6':
        return "https://www.audioffers.com/delaware-valley/showroom/2020/Audi/A6/Sedan.htm";
    case 'hartford||a6':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2020/Audi/A6/Sedan.htm";
    case 'new-england||a6':
        return "https://www.audioffers.com/new-england/showroom/2020/Audi/A6/Sedan.htm";
    case 'pittsburgh||a6':
        return "https://www.audioffers.com/pittsburgh/showroom/2020/Audi/A6/Sedan.htm";
    case 'providence||a6':
        return "http://www.audioffers.com/east/showroom/2020/Audi/A6/Sedan.htm?geoZip=02886";
    case 'tri-state||a6':
        return "https://www.audioffers.com/tri-state/showroom/2020/Audi/A6/Sedan.htm";
    case 'albany||a7-hatchback':
        return "https://www.audialbany.com/showroom/2020/Audi/A7/Hatchback.htm";
    case 'albany||q3':
        return "https://www.audialbany.com/showroom/2020/Audi/Q3/SUV.htm";
    case 'albany||q5':
        return "https://www.audialbany.com/showroom/2020/Audi/Q5/SUV.htm";
    case 'albany||q8':
        return "https://www.audialbany.com/showroom/2020/Audi/Q8/SUV.htm";
    case 'delaware-valley||a7-hatchback':
        return "https://www.audioffers.com/delaware-valley/showroom/2020/Audi/A7/Hatchback.htm";
    case 'delaware-valley||q3':
        return "https://www.audioffers.com/delaware-valley/showroom/2020/Audi/Q3/SUV.htm";
    case 'delaware-valley||q5':
        return "https://www.audioffers.com/delaware-valley/showroom/2020/Audi/Q5/SUV.htm";
    case 'delaware-valley||q8':
        return "https://www.audioffers.com/delaware-valley/showroom/2020/Audi/Q8/SUV.htm";
    case 'hartford||a7-hatchback':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2020/Audi/A7/Hatchback.htm";
    case 'hartford||q3':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2020/Audi/Q3/SUV.htm";
    case 'hartford||q5':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2020/Audi/Q5/SUV.htm";
    case 'hartford||q8':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2020/Audi/Q8/SUV.htm";
    case 'new-england||a7-hatchback':
        return "https://www.audioffers.com/new-england/showroom/2020/Audi/A7/Hatchback.htm";
    case 'new-england||q3':
        return "https://www.audioffers.com/new-england/showroom/2020/Audi/Q3/SUV.htm";
    case 'new-england||q5':
        return "https://www.audioffers.com/new-england/showroom/2020/Audi/Q5/SUV.htm";
    case 'new-england||q8':
        return "https://www.audioffers.com/new-england/showroom/2020/Audi/Q8/SUV.htm";
    case 'pittsburgh||a7-hatchback':
        return "https://www.audioffers.com/pittsburgh/showroom/2020/Audi/A7/Hatchback.htm";
    case 'pittsburgh||q3':
        return "https://www.audioffers.com/pittsburgh/showroom/2020/Audi/Q3/SUV.htm";
    case 'pittsburgh||q5':
        return "https://www.audioffers.com/pittsburgh/showroom/2020/Audi/Q5/SUV.htm";
    case 'pittsburgh||q8':
        return "https://www.audioffers.com/pittsburgh/showroom/2020/Audi/Q8/SUV.htm";
    case 'providence||a7-hatchback':
        return "http://www.audioffers.com/east/showroom/2020/Audi/A7/Hatchback.htm?geoZip=02886";
    case 'providence||q3':
        return "http://www.audioffers.com/east/showroom/2020/Audi/Q3/SUV.htm?geoZip=02886";
    case 'providence||q5':
        return "http://www.audioffers.com/east/showroom/2020/Audi/Q5/SUV.htm?geoZip=02886";
    case 'providence||q8':
        return "http://www.audioffers.com/east/showroom/2020/Audi/Q8/SUV.htm?geoZip=02886";
    case 'tri-state||a7-hatchback':
        return "https://www.audioffers.com/tri-state/showroom/2020/Audi/A7/Hatchback.htm";
    case 'tri-state||q3':
        return "https://www.audioffers.com/tri-state/showroom/2020/Audi/Q3/SUV.htm";
    case 'tri-state||q5':
        return "https://www.audioffers.com/tri-state/showroom/2020/Audi/Q5/SUV.htm";
    case 'tri-state||q8':
        return "https://www.audioffers.com/tri-state/showroom/2020/Audi/Q8/SUV.htm";
    case 'albany||s6':
        return "https://www.audialbany.com/showroom/2020/Audi/S6/Sedan.htm";
    case 'delaware-valley||s6':
        return "https://www.audioffers.com/delaware-valley/showroom/2020/Audi/S6/Sedan.htm";
    case 'hartford||s6':
        return "https://www.audioffers.com/hartford-new-haven/showroom/2020/Audi/S6/Sedan.htm";
    case 'new-england||s6':
        return "https://www.audioffers.com/new-england/showroom/2020/Audi/S6/Sedan.htm";
    case 'pittsburgh||s6':
        return "https://www.audioffers.com/pittsburgh/showroom/2020/Audi/S6/Sedan.htm";
    case 'providence||s6':
        return "http://www.audioffers.com/east/showroom/2020/Audi/S6/Sedan.htm?geoZip=02886";
    case 'tri-state||s6':
        return "https://www.audioffers.com/tri-state/showroom/2020/Audi/S6/Sedan.htm";
    default:
        return "https://www.audioffers.com";
    }
}

