console.log("loaded");
function getURL(urlKeyCode){
switch (urlKeyCode){
    case 'albany||a3':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'albany||a3-cabriolet':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
    case 'albany||a3-e-tron':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
    case 'albany||a3-e-tron-sportback':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
    case 'albany||a4':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
    case 'albany||a5':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=A5&make=Audi";
    case 'albany||a5-cabriolet':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
    case 'albany||a5-coupe':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
    case 'albany||a5-sportback':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
    case 'albany||a6':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
    case 'albany||a7':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
    case 'albany||a7-hatchback':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
    case 'albany||a8':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
    case 'albany||allroad':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
    case 'albany||q3':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
    case 'albany||q5':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
    case 'albany||q7':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
    case 'albany||q8':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
    case 'albany||r8':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
    case 'albany||r8-convertible':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
    case 'albany||rs5':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
    case 'albany||rs5-convertible':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
    case 'albany||rs7':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
    case 'albany||s3':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
    case 'albany||s4':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
    case 'albany||s5':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
    case 'albany||s5-cabriolet':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
    case 'albany||s5-sportback':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
    case 'albany||s6':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
    case 'albany||s7':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
    case 'albany||s8':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'albany||sq5':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
    case 'albany||tt-coupe':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
    case 'albany||tt-roadster':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
    case 'albany||tts-coupe':
        return "https://www.audialbany.com/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
    case 'delaware-valley||a3':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'delaware-valley||a3-cabriolet':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
    case 'delaware-valley||a3-e-tron':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
    case 'delaware-valley||a3-e-tron-sportback':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
    case 'delaware-valley||a4':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
    case 'delaware-valley||a5':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=A5&make=Audi";
    case 'delaware-valley||a5-cabriolet':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
    case 'delaware-valley||a5-coupe':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
    case 'delaware-valley||a5-sportback':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
    case 'delaware-valley||a6':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
    case 'delaware-valley||a7':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
    case 'delaware-valley||a7-hatchback':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
    case 'delaware-valley||a8':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
    case 'delaware-valley||allroad':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
    case 'delaware-valley||q3':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
    case 'delaware-valley||q5':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
    case 'delaware-valley||q7':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
    case 'delaware-valley||q8':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
    case 'delaware-valley||r8':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
    case 'delaware-valley||r8-convertible':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
    case 'delaware-valley||rs5':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
    case 'delaware-valley||rs5-convertible':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
    case 'delaware-valley||rs7':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
    case 'delaware-valley||s3':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
    case 'delaware-valley||s4':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
    case 'delaware-valley||s5':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
    case 'delaware-valley||s5-cabriolet':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
    case 'delaware-valley||s5-sportback':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
    case 'delaware-valley||s6':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
    case 'delaware-valley||s7':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
    case 'delaware-valley||s8':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'delaware-valley||sq5':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
    case 'delaware-valley||tt-coupe':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
    case 'delaware-valley||tt-roadster':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
    case 'delaware-valley||tts-coupe':
        return "https://www.audioffers.com/delaware-valley/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
    case 'hartford||a3':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'hartford||a3-cabriolet':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
    case 'hartford||a3-e-tron':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
    case 'hartford||a3-e-tron-sportback':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
    case 'hartford||a4':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
    case 'hartford||a5':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=A5&make=Audi";
    case 'hartford||a5-cabriolet':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
    case 'hartford||a5-coupe':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
    case 'hartford||a5-sportback':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
    case 'hartford||a6':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
    case 'hartford||a7':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
    case 'hartford||a7-hatchback':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
    case 'hartford||a8':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
    case 'hartford||allroad':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
    case 'hartford||q3':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
    case 'hartford||q5':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
    case 'hartford||q7':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
    case 'hartford||q8':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
    case 'hartford||r8':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
    case 'hartford||r8-convertible':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
    case 'hartford||rs5':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
    case 'hartford||rs5-convertible':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
    case 'hartford||rs7':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
    case 'hartford||s3':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
    case 'hartford||s4':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
    case 'hartford||s5':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
    case 'hartford||s5-cabriolet':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
    case 'hartford||s5-sportback':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
    case 'hartford||s6':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
    case 'hartford||s7':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
    case 'hartford||s8':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'hartford||sq5':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
    case 'hartford||tt-coupe':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
    case 'hartford||tt-roadster':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
    case 'hartford||tts-coupe':
        return "https://www.audioffers.com/hartford-new-haven/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
    case 'new-england||a3':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'new-england||a3-cabriolet':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
    case 'new-england||a3-e-tron':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
    case 'new-england||a3-e-tron-sportback':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
    case 'new-england||a4':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
    case 'new-england||a5':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=A5&make=Audi";
    case 'new-england||a5-cabriolet':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
    case 'new-england||a5-coupe':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
    case 'new-england||a5-sportback':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
    case 'new-england||a6':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
    case 'new-england||a7':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
    case 'new-england||a7-hatchback':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
    case 'new-england||a8':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
    case 'new-england||allroad':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
    case 'new-england||q3':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
    case 'new-england||q5':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
    case 'new-england||q7':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
    case 'new-england||q8':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
    case 'new-england||r8':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
    case 'new-england||r8-convertible':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
    case 'new-england||rs5':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
    case 'new-england||rs5-convertible':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
    case 'new-england||rs7':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
    case 'new-england||s3':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
    case 'new-england||s4':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
    case 'new-england||s5':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
    case 'new-england||s5-cabriolet':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
    case 'new-england||s5-sportback':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
    case 'new-england||s6':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
    case 'new-england||s7':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
    case 'new-england||s8':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'new-england||sq5':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
    case 'new-england||tt-coupe':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
    case 'new-england||tt-roadster':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
    case 'new-england||tts-coupe':
        return "https://www.audioffers.com/new-england/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
    case 'pittsburgh||a3':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'pittsburgh||a3-cabriolet':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
    case 'pittsburgh||a3-e-tron':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
    case 'pittsburgh||a3-e-tron-sportback':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
    case 'pittsburgh||a4':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
    case 'pittsburgh||a5':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=A5&make=Audi";
    case 'pittsburgh||a5-cabriolet':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
    case 'pittsburgh||a5-coupe':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
    case 'pittsburgh||a5-sportback':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
    case 'pittsburgh||a6':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
    case 'pittsburgh||a7':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
    case 'pittsburgh||a7-hatchback':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
    case 'pittsburgh||a8':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
    case 'pittsburgh||allroad':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
    case 'pittsburgh||q3':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
    case 'pittsburgh||q5':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
    case 'pittsburgh||q7':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
    case 'pittsburgh||q8':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
    case 'pittsburgh||r8':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
    case 'pittsburgh||r8-convertible':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
    case 'pittsburgh||rs5':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
    case 'pittsburgh||rs5-convertible':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
    case 'pittsburgh||rs7':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
    case 'pittsburgh||s3':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
    case 'pittsburgh||s4':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
    case 'pittsburgh||s5':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
    case 'pittsburgh||s5-cabriolet':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
    case 'pittsburgh||s5-sportback':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
    case 'pittsburgh||s6':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
    case 'pittsburgh||s7':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
    case 'pittsburgh||s8':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'pittsburgh||sq5':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
    case 'pittsburgh||tt-coupe':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
    case 'pittsburgh||tt-roadster':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
    case 'pittsburgh||tts-coupe':
        return "https://www.audioffers.com/pittsburgh/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
    case 'providence||a3':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi&geoZip=02886";
    case 'providence||a3-cabriolet':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi&geoZip=02886";
    case 'providence||a3-e-tron':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi&geoZip=02886";
    case 'providence||a3-e-tron-sportback':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi&geoZip=02886";
    case 'providence||a4':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi&geoZip=02886";
    case 'providence||a5':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=A5&make=Audi&geoZip=02886";
    case 'providence||a5-cabriolet':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi&geoZip=02886";
    case 'providence||a5-coupe':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi&geoZip=02886";
    case 'providence||a5-sportback':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback&geoZip=02886";
    case 'providence||a6':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi&geoZip=02886";
    case 'providence||a7':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi&geoZip=02886";
    case 'providence||a7-hatchback':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi&geoZip=02886";
    case 'providence||a8':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi&geoZip=02886";
    case 'providence||allroad':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi&geoZip=02886";
    case 'providence||q3':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi&geoZip=02886";
    case 'providence||q5':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi&geoZip=02886";
    case 'providence||q7':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi&geoZip=02886";
    case 'providence||q8':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi&geoZip=02886";
    case 'providence||r8':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi&geoZip=02886";
    case 'providence||r8-convertible':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi&geoZip=02886";
    case 'providence||rs5':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi&geoZip=02886";
    case 'providence||rs5-convertible':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi&geoZip=02886";
    case 'providence||rs7':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi&geoZip=02886";
    case 'providence||s3':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi&geoZip=02886";
    case 'providence||s4':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi&geoZip=02886";
    case 'providence||s5':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi&geoZip=02886";
    case 'providence||s5-cabriolet':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi&geoZip=02886";
    case 'providence||s5-sportback':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi&geoZip=02886";
    case 'providence||s6':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi&geoZip=02886";
    case 'providence||s7':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi&geoZip=02886";
    case 'providence||s8':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi&geoZip=02886";
    case 'providence||sq5':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi&geoZip=02886";
    case 'providence||tt-coupe':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi&geoZip=02886";
    case 'providence||tt-roadster':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi&geoZip=02886";
    case 'providence||tts-coupe':
        return "https://www.audiwarwick.com/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi&geoZip=02886";
    case 'tri-state||a3':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'tri-state||a3-cabriolet':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
    case 'tri-state||a3-e-tron':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
    case 'tri-state||a3-e-tron-sportback':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
    case 'tri-state||a4':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
    case 'tri-state||a5':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=A5&make=Audi";
    case 'tri-state||a5-cabriolet':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
    case 'tri-state||a5-coupe':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
    case 'tri-state||a5-sportback':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
    case 'tri-state||a6':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
    case 'tri-state||a7':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
    case 'tri-state||a7-hatchback':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
    case 'tri-state||a8':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
    case 'tri-state||allroad':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
    case 'tri-state||q3':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
    case 'tri-state||q5':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
    case 'tri-state||q7':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
    case 'tri-state||q8':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
    case 'tri-state||r8':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
    case 'tri-state||r8-convertible':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
    case 'tri-state||rs5':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
    case 'tri-state||rs5-convertible':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
    case 'tri-state||rs7':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
    case 'tri-state||s3':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
    case 'tri-state||s4':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
    case 'tri-state||s5':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
    case 'tri-state||s5-cabriolet':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
    case 'tri-state||s5-sportback':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
    case 'tri-state||s6':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
    case 'tri-state||s7':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
    case 'tri-state||s8':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'tri-state||sq5':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
    case 'tri-state||tt-coupe':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
    case 'tri-state||tt-roadster':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
    case 'tri-state||tts-coupe':
        return "https://www.audioffers.com/tri-state/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
    default:
        return "https://www.audioffers.com";
    }
}

