console.log("loaded");
function getURL(urlKeyCode){
	switch (urlKeyCode){
		case "e-tron":
			return "https://audiusa.com/models/audi-e-tron";
		case "q3":
			return "https://audiusa.com/models/audi-q3";
		case "a4-allroad":
			return "https://audiusa.com/models/audi-a4-allroad";
		case "a6-allroad":
			return "https://audiusa.com/models/audi-a6-allroad";
		case "q5":
			return "https://audiusa.com/models/audi-q5";
		case "sq5":
			return "https://audiusa.com/models/audi-sq5";
		case "q7":
			return "https://audiusa.com/models/audi-q7";
		case "q8":
			return "https://audiusa.com/models/audi-q8";
		case "a3-sedan":
			return "https://audiusa.com/models/audi-a3-sedan";
		case "s3-sedan":
			return "https://audiusa.com/models/audi-s3-sedan";
		case "a3":
			return "https://audiusa.com/models/audi-a3-sedan";
		case "s3":
			return "https://audiusa.com/models/audi-s3-sedan";
		case "rs3":
			return "https://audiusa.com/models/audi-rs3";
		case "a4":
			return "https://audiusa.com/models/audi-a4";
		case "s4":
			return "https://audiusa.com/models/audi-s4";
		case "a5-sportback":
			return "https://audiusa.com/models/audi-a5-sportback";
		case "s5-sportback":
			return "https://audiusa.com/models/audi-s5-sportback";
		case "rs5-sportback":
			return "https://audiusa.com/models/audi-rs5-sportback";
		case "a6":
			return "https://audiusa.com/models/audi-a6";
		case "s6":
			return "https://audiusa.com/models/audi-s6";
		case "a7":
			return "https://audiusa.com/models/audi-a7";
		case "s7":
			return "https://audiusa.com/models/audi-s7";
		case "a8":
			return "https://audiusa.com/models/audi-a8";
		case "s8":
			return "https://audiusa.com/models/audi-s8";
		case "a5-coupe":
			return "https://audiusa.com/models/audi-a5-coupe";
		case "s5-coupe":
			return "https://audiusa.com/models/audi-s5-coupe";
		case "rs5-coupe":
			return "https://audiusa.com/models/audi-rs5-coupe";
		case "a5-cabriolet":
			return "https://audiusa.com/models/audi-a5-cabriolet";
		case "s5-cabriolet":
			return "https://audiusa.com/models/audi-s5-cabriolet";
		case "tt-coupe":
			return "https://audiusa.com/models/audi-tt-coupe";
		case "tts-coupe":
			return "https://audiusa.com/models/audi-tts-coupe";
		case "tt-rs":
			return "https://audiusa.com/models/audi-tt-rs";
		case "tt-roadster":
			return "https://audiusa.com/models/audi-tt-roadster";
		case "r8":
			return "https://audiusa.com/models/audi-r8";
		case "r8-spyder":
			return "https://audiusa.com/models/audi-r8-spyder";
		case "rs6-avant":
			return "https://audiusa.com/models/audi-rs6-avant";
		case "rs7":
			return "https://audiusa.com/models/audi-rs7";
		case "sq7":
			return "https://audiusa.com/models/audi-sq7";
		case "sq8":
			return "https://audiusa.com/models/audi-sq8";
		case "rsq8":
			return "https://audiusa.com/models/audi-rsq8";
		default:
			return "https://audiusa.com";
	}
}