function getURL(urlKeyCode){
switch (urlKeyCode){
    case 'albuquerque||a3':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'albuquerque||a3-cabriolet':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
    case 'albuquerque||a3-e-tron':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
    case 'albuquerque||a3-e-tron-sportback':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
    case 'albuquerque||a4':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
    case 'albuquerque||a5':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=A5&make=Audi";
    case 'albuquerque||a5-cabriolet':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
    case 'albuquerque||a5-coupe':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
    case 'albuquerque||a5-sportback':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
    case 'albuquerque||a6':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
    case 'albuquerque||a7':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
    case 'albuquerque||a7-hatchback':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
    case 'albuquerque||a8':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
    case 'albuquerque||allroad':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
    case 'albuquerque||q3':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
    case 'albuquerque||q5':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
    case 'albuquerque||q7':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
    case 'albuquerque||q8':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
    case 'albuquerque||r8':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
    case 'albuquerque||r8-convertible':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
    case 'albuquerque||rs5':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
    case 'albuquerque||rs5-convertible':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
    case 'albuquerque||rs7':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
    case 'albuquerque||s3':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
    case 'albuquerque||s4':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
    case 'albuquerque||s5':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
    case 'albuquerque||s5-cabriolet':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
    case 'albuquerque||s5-sportback':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
    case 'albuquerque||s6':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
    case 'albuquerque||s7':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
    case 'albuquerque||s8':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'albuquerque||sq5':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
    case 'albuquerque||tt-coupe':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
    case 'albuquerque||tt-roadster':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
    case 'albuquerque||tts-coupe':
        return "http://www.audiabq.com/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
    case 'boise||a3':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'boise||a3-cabriolet':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
    case 'boise||a3-e-tron':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
    case 'boise||a3-e-tron-sportback':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
    case 'boise||a4':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
    case 'boise||a5':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=A5&make=Audi";
    case 'boise||a5-cabriolet':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
    case 'boise||a5-coupe':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
    case 'boise||a5-sportback':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
    case 'boise||a6':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
    case 'boise||a7':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
    case 'boise||a7-hatchback':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
    case 'boise||a8':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
    case 'boise||allroad':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
    case 'boise||q3':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
    case 'boise||q5':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
    case 'boise||q7':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
    case 'boise||q8':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
    case 'boise||r8':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
    case 'boise||r8-convertible':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
    case 'boise||rs5':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
    case 'boise||rs5-convertible':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
    case 'boise||rs7':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
    case 'boise||s3':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
    case 'boise||s4':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
    case 'boise||s5':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
    case 'boise||s5-cabriolet':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
    case 'boise||s5-sportback':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
    case 'boise||s6':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
    case 'boise||s7':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
    case 'boise||s8':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'boise||sq5':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
    case 'boise||tt-coupe':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
    case 'boise||tt-roadster':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
    case 'boise||tts-coupe':
        return "https://www.audiboise.com/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
    case 'colorado-springs||a3':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'colorado-springs||a3-cabriolet':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
    case 'colorado-springs||a3-e-tron':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
    case 'colorado-springs||a3-e-tron-sportback':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
    case 'colorado-springs||a4':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
    case 'colorado-springs||a5':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=A5&make=Audi";
    case 'colorado-springs||a5-cabriolet':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
    case 'colorado-springs||a5-coupe':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
    case 'colorado-springs||a5-sportback':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
    case 'colorado-springs||a6':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
    case 'colorado-springs||a7':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
    case 'colorado-springs||a7-hatchback':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
    case 'colorado-springs||a8':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
    case 'colorado-springs||allroad':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
    case 'colorado-springs||q3':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
    case 'colorado-springs||q5':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
    case 'colorado-springs||q7':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
    case 'colorado-springs||q8':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
    case 'colorado-springs||r8':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
    case 'colorado-springs||r8-convertible':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
    case 'colorado-springs||rs5':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
    case 'colorado-springs||rs5-convertible':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
    case 'colorado-springs||rs7':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
    case 'colorado-springs||s3':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
    case 'colorado-springs||s4':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
    case 'colorado-springs||s5':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
    case 'colorado-springs||s5-cabriolet':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
    case 'colorado-springs||s5-sportback':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
    case 'colorado-springs||s6':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
    case 'colorado-springs||s7':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
    case 'colorado-springs||s8':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'colorado-springs||sq5':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
    case 'colorado-springs||tt-coupe':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
    case 'colorado-springs||tt-roadster':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
    case 'colorado-springs||tts-coupe':
        return "https://www.audicoloradosprings.com/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
    case 'denver||a3':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'denver||a3-cabriolet':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
    case 'denver||a3-e-tron':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
    case 'denver||a3-e-tron-sportback':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
    case 'denver||a4':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
    case 'denver||a5':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=A5&make=Audi";
    case 'denver||a5-cabriolet':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
    case 'denver||a5-coupe':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
    case 'denver||a5-sportback':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
    case 'denver||a6':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
    case 'denver||a7':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
    case 'denver||a7-hatchback':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
    case 'denver||a8':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
    case 'denver||allroad':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
    case 'denver||q3':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
    case 'denver||q5':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
    case 'denver||q7':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
    case 'denver||q8':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
    case 'denver||r8':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
    case 'denver||r8-convertible':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
    case 'denver||rs5':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
    case 'denver||rs5-convertible':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
    case 'denver||rs7':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
    case 'denver||s3':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
    case 'denver||s4':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
    case 'denver||s5':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
    case 'denver||s5-cabriolet':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
    case 'denver||s5-sportback':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
    case 'denver||s6':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
    case 'denver||s7':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
    case 'denver||s8':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'denver||sq5':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
    case 'denver||tt-coupe':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
    case 'denver||tt-roadster':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
    case 'denver||tts-coupe':
        return "https://www.audioffers.com/colorado/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
    case 'honolulu||a3':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'honolulu||a3-cabriolet':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
    case 'honolulu||a3-e-tron':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
    case 'honolulu||a3-e-tron-sportback':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
    case 'honolulu||a4':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
    case 'honolulu||a5':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=A5&make=Audi";
    case 'honolulu||a5-cabriolet':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
    case 'honolulu||a5-coupe':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
    case 'honolulu||a5-sportback':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
    case 'honolulu||a6':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
    case 'honolulu||a7':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
    case 'honolulu||a7-hatchback':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
    case 'honolulu||a8':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
    case 'honolulu||allroad':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
    case 'honolulu||q3':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
    case 'honolulu||q5':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
    case 'honolulu||q7':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
    case 'honolulu||q8':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
    case 'honolulu||r8':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
    case 'honolulu||r8-convertible':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
    case 'honolulu||rs5':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
    case 'honolulu||rs5-convertible':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
    case 'honolulu||rs7':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
    case 'honolulu||s3':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
    case 'honolulu||s4':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
    case 'honolulu||s5':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
    case 'honolulu||s5-cabriolet':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
    case 'honolulu||s5-sportback':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
    case 'honolulu||s6':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
    case 'honolulu||s7':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
    case 'honolulu||s8':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'honolulu||sq5':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
    case 'honolulu||tt-coupe':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
    case 'honolulu||tt-roadster':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
    case 'honolulu||tts-coupe':
        return "https://www.audihonolulu.com/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
    case 'las-vegas||a3':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'las-vegas||a3-cabriolet':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
    case 'las-vegas||a3-e-tron':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
    case 'las-vegas||a3-e-tron-sportback':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
    case 'las-vegas||a4':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
    case 'las-vegas||a5':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=A5&make=Audi";
    case 'las-vegas||a5-cabriolet':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
    case 'las-vegas||a5-coupe':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
    case 'las-vegas||a5-sportback':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
    case 'las-vegas||a6':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
    case 'las-vegas||a7':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
    case 'las-vegas||a7-hatchback':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
    case 'las-vegas||a8':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
    case 'las-vegas||allroad':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
    case 'las-vegas||q3':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
    case 'las-vegas||q5':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
    case 'las-vegas||q7':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
    case 'las-vegas||q8':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
    case 'las-vegas||r8':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
    case 'las-vegas||r8-convertible':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
    case 'las-vegas||rs5':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
    case 'las-vegas||rs5-convertible':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
    case 'las-vegas||rs7':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
    case 'las-vegas||s3':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
    case 'las-vegas||s4':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
    case 'las-vegas||s5':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
    case 'las-vegas||s5-cabriolet':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
    case 'las-vegas||s5-sportback':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
    case 'las-vegas||s6':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
    case 'las-vegas||s7':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
    case 'las-vegas||s8':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'las-vegas||sq5':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
    case 'las-vegas||tt-coupe':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
    case 'las-vegas||tt-roadster':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
    case 'las-vegas||tts-coupe':
        return "https://www.audioffers.com/las-vegas/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
    case 'los-angeles||a3':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'los-angeles||a3-cabriolet':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
    case 'los-angeles||a3-e-tron':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
    case 'los-angeles||a3-e-tron-sportback':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
    case 'los-angeles||a4':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
    case 'los-angeles||a5':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=A5&make=Audi";
    case 'los-angeles||a5-cabriolet':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
    case 'los-angeles||a5-coupe':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
    case 'los-angeles||a5-sportback':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
    case 'los-angeles||a6':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
    case 'los-angeles||a7':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
    case 'los-angeles||a7-hatchback':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
    case 'los-angeles||a8':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
    case 'los-angeles||allroad':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
    case 'los-angeles||q3':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
    case 'los-angeles||q5':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
    case 'los-angeles||q7':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
    case 'los-angeles||q8':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
    case 'los-angeles||r8':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
    case 'los-angeles||r8-convertible':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
    case 'los-angeles||rs5':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
    case 'los-angeles||rs5-convertible':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
    case 'los-angeles||rs7':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
    case 'los-angeles||s3':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
    case 'los-angeles||s4':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
    case 'los-angeles||s5':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
    case 'los-angeles||s5-cabriolet':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
    case 'los-angeles||s5-sportback':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
    case 'los-angeles||s6':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
    case 'los-angeles||s7':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
    case 'los-angeles||s8':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'los-angeles||sq5':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
    case 'los-angeles||tt-coupe':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
    case 'los-angeles||tt-roadster':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
    case 'los-angeles||tts-coupe':
        return "https://www.audioffers.com/southern-california/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
    case 'palm-springs||a3':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'palm-springs||a3-cabriolet':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
    case 'palm-springs||a3-e-tron':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
    case 'palm-springs||a3-e-tron-sportback':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
    case 'palm-springs||a4':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
    case 'palm-springs||a5':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=A5&make=Audi";
    case 'palm-springs||a5-cabriolet':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
    case 'palm-springs||a5-coupe':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
    case 'palm-springs||a5-sportback':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
    case 'palm-springs||a6':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
    case 'palm-springs||a7':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
    case 'palm-springs||a7-hatchback':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
    case 'palm-springs||a8':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
    case 'palm-springs||allroad':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
    case 'palm-springs||q3':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
    case 'palm-springs||q5':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
    case 'palm-springs||q7':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
    case 'palm-springs||q8':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
    case 'palm-springs||r8':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
    case 'palm-springs||r8-convertible':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
    case 'palm-springs||rs5':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
    case 'palm-springs||rs5-convertible':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
    case 'palm-springs||rs7':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
    case 'palm-springs||s3':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
    case 'palm-springs||s4':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
    case 'palm-springs||s5':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
    case 'palm-springs||s5-cabriolet':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
    case 'palm-springs||s5-sportback':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
    case 'palm-springs||s6':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
    case 'palm-springs||s7':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
    case 'palm-springs||s8':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'palm-springs||sq5':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
    case 'palm-springs||tt-coupe':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
    case 'palm-springs||tt-roadster':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
    case 'palm-springs||tts-coupe':
        return "https://www.audiranchomirage.com/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
    case 'phoenix||a3':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'phoenix||a3-cabriolet':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
    case 'phoenix||a3-e-tron':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
    case 'phoenix||a3-e-tron-sportback':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
    case 'phoenix||a4':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
    case 'phoenix||a5':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=A5&make=Audi";
    case 'phoenix||a5-cabriolet':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
    case 'phoenix||a5-coupe':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
    case 'phoenix||a5-sportback':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
    case 'phoenix||a6':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
    case 'phoenix||a7':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
    case 'phoenix||a7-hatchback':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
    case 'phoenix||a8':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
    case 'phoenix||allroad':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
    case 'phoenix||q3':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
    case 'phoenix||q5':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
    case 'phoenix||q7':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
    case 'phoenix||q8':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
    case 'phoenix||r8':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
    case 'phoenix||r8-convertible':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
    case 'phoenix||rs5':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
    case 'phoenix||rs5-convertible':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
    case 'phoenix||rs7':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
    case 'phoenix||s3':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
    case 'phoenix||s4':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
    case 'phoenix||s5':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
    case 'phoenix||s5-cabriolet':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
    case 'phoenix||s5-sportback':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
    case 'phoenix||s6':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
    case 'phoenix||s7':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
    case 'phoenix||s8':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'phoenix||sq5':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
    case 'phoenix||tt-coupe':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
    case 'phoenix||tt-roadster':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
    case 'phoenix||tts-coupe':
        return "https://www.audioffers.com/arizona/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
    case 'portland||a3':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'portland||a3-cabriolet':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
    case 'portland||a3-e-tron':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
    case 'portland||a3-e-tron-sportback':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
    case 'portland||a4':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
    case 'portland||a5':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=A5&make=Audi";
    case 'portland||a5-cabriolet':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
    case 'portland||a5-coupe':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
    case 'portland||a5-sportback':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
    case 'portland||a6':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
    case 'portland||a7':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
    case 'portland||a7-hatchback':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
    case 'portland||a8':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
    case 'portland||allroad':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
    case 'portland||q3':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
    case 'portland||q5':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
    case 'portland||q7':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
    case 'portland||q8':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
    case 'portland||r8':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
    case 'portland||r8-convertible':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
    case 'portland||rs5':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
    case 'portland||rs5-convertible':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
    case 'portland||rs7':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
    case 'portland||s3':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
    case 'portland||s4':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
    case 'portland||s5':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
    case 'portland||s5-cabriolet':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
    case 'portland||s5-sportback':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
    case 'portland||s6':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
    case 'portland||s7':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
    case 'portland||s8':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'portland||sq5':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
    case 'portland||tt-coupe':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
    case 'portland||tt-roadster':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
    case 'portland||tts-coupe':
        return "https://www.audioffers.com/oregon/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
    case 'reno||a3':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'reno||a3-cabriolet':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
    case 'reno||a3-e-tron':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
    case 'reno||a3-e-tron-sportback':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
    case 'reno||a4':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
    case 'reno||a5':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=A5&make=Audi";
    case 'reno||a5-cabriolet':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
    case 'reno||a5-coupe':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
    case 'reno||a5-sportback':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
    case 'reno||a6':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
    case 'reno||a7':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
    case 'reno||a7-hatchback':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
    case 'reno||a8':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
    case 'reno||allroad':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
    case 'reno||q3':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
    case 'reno||q5':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
    case 'reno||q7':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
    case 'reno||q8':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
    case 'reno||r8':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
    case 'reno||r8-convertible':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
    case 'reno||rs5':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
    case 'reno||rs5-convertible':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
    case 'reno||rs7':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
    case 'reno||s3':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
    case 'reno||s4':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
    case 'reno||s5':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
    case 'reno||s5-cabriolet':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
    case 'reno||s5-sportback':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
    case 'reno||s6':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
    case 'reno||s7':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
    case 'reno||s8':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'reno||sq5':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
    case 'reno||tt-coupe':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
    case 'reno||tt-roadster':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
    case 'reno||tts-coupe':
        return "https://www.audirenotahoe.com/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
    case 'sacramento||a3':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'sacramento||a3-cabriolet':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
    case 'sacramento||a3-e-tron':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
    case 'sacramento||a3-e-tron-sportback':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
    case 'sacramento||a4':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
    case 'sacramento||a5':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=A5&make=Audi";
    case 'sacramento||a5-cabriolet':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
    case 'sacramento||a5-coupe':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
    case 'sacramento||a5-sportback':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
    case 'sacramento||a6':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
    case 'sacramento||a7':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
    case 'sacramento||a7-hatchback':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
    case 'sacramento||a8':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
    case 'sacramento||allroad':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
    case 'sacramento||q3':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
    case 'sacramento||q5':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
    case 'sacramento||q7':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
    case 'sacramento||q8':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
    case 'sacramento||r8':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
    case 'sacramento||r8-convertible':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
    case 'sacramento||rs5':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
    case 'sacramento||rs5-convertible':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
    case 'sacramento||rs7':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
    case 'sacramento||s3':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
    case 'sacramento||s4':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
    case 'sacramento||s5':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
    case 'sacramento||s5-cabriolet':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
    case 'sacramento||s5-sportback':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
    case 'sacramento||s6':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
    case 'sacramento||s7':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
    case 'sacramento||s8':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'sacramento||sq5':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
    case 'sacramento||tt-coupe':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
    case 'sacramento||tt-roadster':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
    case 'sacramento||tts-coupe':
        return "https://www.audioffers.com/sacramento/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
    case 'salt-lake-city||a3':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'salt-lake-city||a3-cabriolet':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
    case 'salt-lake-city||a3-e-tron':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
    case 'salt-lake-city||a3-e-tron-sportback':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
    case 'salt-lake-city||a4':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
    case 'salt-lake-city||a5':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=A5&make=Audi";
    case 'salt-lake-city||a5-cabriolet':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
    case 'salt-lake-city||a5-coupe':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
    case 'salt-lake-city||a5-sportback':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
    case 'salt-lake-city||a6':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
    case 'salt-lake-city||a7':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
    case 'salt-lake-city||a7-hatchback':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
    case 'salt-lake-city||a8':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
    case 'salt-lake-city||allroad':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
    case 'salt-lake-city||q3':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
    case 'salt-lake-city||q5':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
    case 'salt-lake-city||q7':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
    case 'salt-lake-city||q8':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
    case 'salt-lake-city||r8':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
    case 'salt-lake-city||r8-convertible':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
    case 'salt-lake-city||rs5':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
    case 'salt-lake-city||rs5-convertible':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
    case 'salt-lake-city||rs7':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
    case 'salt-lake-city||s3':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
    case 'salt-lake-city||s4':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
    case 'salt-lake-city||s5':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
    case 'salt-lake-city||s5-cabriolet':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
    case 'salt-lake-city||s5-sportback':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
    case 'salt-lake-city||s6':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
    case 'salt-lake-city||s7':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
    case 'salt-lake-city||s8':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'salt-lake-city||sq5':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
    case 'salt-lake-city||tt-coupe':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
    case 'salt-lake-city||tt-roadster':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
    case 'salt-lake-city||tts-coupe':
        return "https://www.audioffers.com/utah/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
    case 'san-diego||a3':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'san-diego||a3-cabriolet':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
    case 'san-diego||a3-e-tron':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
    case 'san-diego||a3-e-tron-sportback':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
    case 'san-diego||a4':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
    case 'san-diego||a5':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=A5&make=Audi";
    case 'san-diego||a5-cabriolet':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
    case 'san-diego||a5-coupe':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
    case 'san-diego||a5-sportback':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
    case 'san-diego||a6':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
    case 'san-diego||a7':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
    case 'san-diego||a7-hatchback':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
    case 'san-diego||a8':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
    case 'san-diego||allroad':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
    case 'san-diego||q3':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
    case 'san-diego||q5':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
    case 'san-diego||q7':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
    case 'san-diego||q8':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
    case 'san-diego||r8':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
    case 'san-diego||r8-convertible':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
    case 'san-diego||rs5':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
    case 'san-diego||rs5-convertible':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
    case 'san-diego||rs7':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
    case 'san-diego||s3':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
    case 'san-diego||s4':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
    case 'san-diego||s5':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
    case 'san-diego||s5-cabriolet':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
    case 'san-diego||s5-sportback':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
    case 'san-diego||s6':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
    case 'san-diego||s7':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
    case 'san-diego||s8':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'san-diego||sq5':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
    case 'san-diego||tt-coupe':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
    case 'san-diego||tt-roadster':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
    case 'san-diego||tts-coupe':
        return "https://www.audioffers.com/san-diego/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
    case 'san-francisco||a3':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'san-francisco||a3-cabriolet':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
    case 'san-francisco||a3-e-tron':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
    case 'san-francisco||a3-e-tron-sportback':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
    case 'san-francisco||a4':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
    case 'san-francisco||a5':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=A5&make=Audi";
    case 'san-francisco||a5-cabriolet':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
    case 'san-francisco||a5-coupe':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
    case 'san-francisco||a5-sportback':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
    case 'san-francisco||a6':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
    case 'san-francisco||a7':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
    case 'san-francisco||a7-hatchback':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
    case 'san-francisco||a8':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
    case 'san-francisco||allroad':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
    case 'san-francisco||q3':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
    case 'san-francisco||q5':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
    case 'san-francisco||q7':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
    case 'san-francisco||q8':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
    case 'san-francisco||r8':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
    case 'san-francisco||r8-convertible':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
    case 'san-francisco||rs5':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
    case 'san-francisco||rs5-convertible':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
    case 'san-francisco||rs7':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
    case 'san-francisco||s3':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
    case 'san-francisco||s4':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
    case 'san-francisco||s5':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
    case 'san-francisco||s5-cabriolet':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
    case 'san-francisco||s5-sportback':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
    case 'san-francisco||s6':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
    case 'san-francisco||s7':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
    case 'san-francisco||s8':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'san-francisco||sq5':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
    case 'san-francisco||tt-coupe':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
    case 'san-francisco||tt-roadster':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
    case 'san-francisco||tts-coupe':
        return "https://www.audioffers.com/san-francisco/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
    case 'santa-barbara||a3':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'santa-barbara||a3-cabriolet':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
    case 'santa-barbara||a3-e-tron':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
    case 'santa-barbara||a3-e-tron-sportback':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
    case 'santa-barbara||a4':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
    case 'santa-barbara||a5':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=A5&make=Audi";
    case 'santa-barbara||a5-cabriolet':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
    case 'santa-barbara||a5-coupe':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
    case 'santa-barbara||a5-sportback':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
    case 'santa-barbara||a6':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
    case 'santa-barbara||a7':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
    case 'santa-barbara||a7-hatchback':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
    case 'santa-barbara||a8':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
    case 'santa-barbara||allroad':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
    case 'santa-barbara||q3':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
    case 'santa-barbara||q5':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
    case 'santa-barbara||q7':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
    case 'santa-barbara||q8':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
    case 'santa-barbara||r8':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
    case 'santa-barbara||r8-convertible':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
    case 'santa-barbara||rs5':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
    case 'santa-barbara||rs5-convertible':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
    case 'santa-barbara||rs7':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
    case 'santa-barbara||s3':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
    case 'santa-barbara||s4':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
    case 'santa-barbara||s5':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
    case 'santa-barbara||s5-cabriolet':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
    case 'santa-barbara||s5-sportback':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
    case 'santa-barbara||s6':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
    case 'santa-barbara||s7':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
    case 'santa-barbara||s8':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'santa-barbara||sq5':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
    case 'santa-barbara||tt-coupe':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
    case 'santa-barbara||tt-roadster':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
    case 'santa-barbara||tts-coupe':
        return "https://www.audisantabarbara.com/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
    case 'seattle||a3':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'seattle||a3-cabriolet':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
    case 'seattle||a3-e-tron':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
    case 'seattle||a3-e-tron-sportback':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
    case 'seattle||a4':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
    case 'seattle||a5':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=A5&make=Audi";
    case 'seattle||a5-cabriolet':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
    case 'seattle||a5-coupe':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
    case 'seattle||a5-sportback':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
    case 'seattle||a6':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
    case 'seattle||a7':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
    case 'seattle||a7-hatchback':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
    case 'seattle||a8':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
    case 'seattle||allroad':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
    case 'seattle||q3':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
    case 'seattle||q5':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
    case 'seattle||q7':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
    case 'seattle||q8':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
    case 'seattle||r8':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
    case 'seattle||r8-convertible':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
    case 'seattle||rs5':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
    case 'seattle||rs5-convertible':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
    case 'seattle||rs7':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
    case 'seattle||s3':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
    case 'seattle||s4':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
    case 'seattle||s5':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
    case 'seattle||s5-cabriolet':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
    case 'seattle||s5-sportback':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
    case 'seattle||s6':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
    case 'seattle||s7':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
    case 'seattle||s8':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'seattle||sq5':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
    case 'seattle||tt-coupe':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
    case 'seattle||tt-roadster':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
    case 'seattle||tts-coupe':
        return "https://www.audioffers.com/puget-sound/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
    case 'spokane||a3':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'spokane||a3-cabriolet':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Convertible&make=Audi";
    case 'spokane||a3-e-tron':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Sedan&make=Audi";
    case 'spokane||a3-e-tron-sportback':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=A3%20e-tron&normalBodyStyle=Hatchback&make=Audi";
    case 'spokane||a4':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=A4&normalBodyStyle=Sedan&make=Audi";
    case 'spokane||a5':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=A5&make=Audi";
    case 'spokane||a5-cabriolet':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Convertible&make=Audi";
    case 'spokane||a5-coupe':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=A5&normalBodyStyle=Coupe&make=Audi";
    case 'spokane||a5-sportback':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=A5&bodyStyle=Sportback";
    case 'spokane||a6':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=A6&normalBodyStyle=Sedan&make=Audi";
    case 'spokane||a7':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Sedan&make=Audi";
    case 'spokane||a7-hatchback':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=A7&normalBodyStyle=Hatchback&make=Audi";
    case 'spokane||a8':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=A8&normalBodyStyle=Sedan&make=Audi";
    case 'spokane||allroad':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=allroad&normalBodyStyle=SUV&make=Audi";
    case 'spokane||q3':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=Q3&normalBodyStyle=SUV&make=Audi";
    case 'spokane||q5':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=Q5&normalBodyStyle=SUV&make=Audi";
    case 'spokane||q7':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=Q7&normalBodyStyle=SUV&make=Audi";
    case 'spokane||q8':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=Q8&normalBodyStyle=SUV&make=Audi";
    case 'spokane||r8':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Coupe&make=Audi";
    case 'spokane||r8-convertible':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=R8&normalBodyStyle=Convertible&make=Audi";
    case 'spokane||rs5':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=RS%205&normalBodyStyle=Coupe&make=Audi";
    case 'spokane||rs5-convertible':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=R5&normalBodyStyle=Convertible&make=Audi";
    case 'spokane||rs7':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=RS%207&normalBodyStyle=Sedan&make=Audi";
    case 'spokane||s3':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=S3&normalBodyStyle=Sedan&make=Audi";
    case 'spokane||s4':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=S4&normalBodyStyle=Sedan&make=Audi";
    case 'spokane||s5':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Coupe&make=Audi";
    case 'spokane||s5-cabriolet':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Convertible&make=Audi";
    case 'spokane||s5-sportback':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=S5&normalBodyStyle=Hatchback&make=Audi";
    case 'spokane||s6':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=S6&normalBodyStyle=Sedan&make=Audi";
    case 'spokane||s7':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=S7&normalBodyStyle=Sedan&make=Audi";
    case 'spokane||s8':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=A3&normalBodyStyle=Sedan&make=Audi";
    case 'spokane||sq5':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=SQ5&normalBodyStyle=SUV&make=Audi";
    case 'spokane||tt-coupe':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Coupe&make=Audi";
    case 'spokane||tt-roadster':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=TT&normalBodyStyle=Convertible&make=Audi";
    case 'spokane||tts-coupe':
        return "https://www.audispokane.com/new-inventory/index.htm?gvModel=TTS&normalBodyStyle=Coupe&make=Audi";
    default:
        return "https://www.audioffers.com";
    }
}

