console.log("loaded");
function getURL(urlKeyCode){
switch (urlKeyCode){
    case 'chicago':
        return 'https://www.audioffers.com/chicagoland/index.htm';
    case 'cincinnati':
        return 'https://www.audioffers.com/cincinnati/index.htm';
    case 'cleveland':
        return 'https://www.audioffers.com/cleveland/index.htm';
    case 'columbus':
        return 'https://www.audioffers.com/columbus/index.htm';
    case 'detroit':
        return 'https://www.audioffers.com/detroit/index.htm';
    case 'grand-rapids':
        return 'https://www.audigrandrapids.com/';
    case 'indianapolis':
        return 'https://www.audiindianapolis.com/';
    case 'kansas-city':
        return 'http://www.audioffers.com/kansas-city/index.htm?geoZip=64114';
    case 'louisville':
        return 'https://www.audilouisville.com/';
    case 'minneapolis':
        return 'https://www.audioffers.com/twin-cities/index.htm?geoZip=55109';
    case 'st-louis':
        return 'https://www.audioffers.com/st-louis/index.htm';
    case 'toledo':
        return 'https://www.sylvaniaaudi.com/';
    case 'wichita':
        return 'https://www.audiwichita.com/';
    case 'atlanta':
        return 'https://www.audioffers.com/atlanta/index.htm';
    case 'austin':
        return 'https://www.audioffers.com/austin/index.htm';
    case 'baltimore':
        return 'https://www.audioffers.com/maryland/index.htm';
    case 'baton-rouge':
        return 'https://www.audibatonrouge.com/';
    case 'birmingham':
        return 'https://www.audiofbirmingham.com/';
    case 'cape-fear':
        return 'https://www.audicapefear.com/';
    case 'charlotte':
        return 'https://www.audioffers.com/charlotte/index.htm';
    case 'charlottesville':
        return 'https://www.audicharlottesville.com/';
    case 'columbia':
        return 'https://www.audicolumbia.com/';
    case 'dallas':
        return 'https://www.audioffers.com/north-texas/index.htm';
    case 'el-paso':
        return 'https://www.elpasoaudi.com/';
    case 'fort-myers':
        return 'https://www.audioffers.com/fort-meyers-naples/index.htm';
    case 'greensboro':
        return 'https://www.audioffers.com/triad/index.htm';
    case 'greenville-asheville':
        return 'https://www.audioffers.com/gsa/index.htm';
    case 'hampton-roads':
        return 'https://www.audioffers.com/hampton-roads/index.htm';
    case 'houston':
        return 'https://www.audioffers.com/houston/index.htm';
    case 'jacksonville':
        return 'http://www.audioffers.com/jacksonville/index.htm';
    case 'lafayette':
        return 'https://www.audilafayette.com/';
    case 'little-rock':
        return 'https://www.arkansasaudi.com/';
    case 'memphis':
        return 'https://www.audimemphis.com/';
    case 'nashville':
        return 'https://www.audinashville.com/';
    case 'new-orleans':
        return 'https://www.audineworleans.com/';
    case 'orlando':
        return 'https://www.audioffers.com/central-florida/index.htm';
    case 'richmond':
        return 'https://www.audirichmondva.com/';
    case 'san-antonio':
        return 'https://www.audioffers.com/San-Antonio/index.htm';
    case 'san-juan':
        return 'http://www.audisanjuan.com/';
    case 'south-florida':
        return 'https://www.audioffers.com/south-florida/index.htm';
    case 'tampa':
        return 'https://www.audioffers.com/tampa/index.htm';
    case 'tulsa':
        return 'https://www.auditulsa.com/';
    case 'washington-dc':
        return 'https://www.audioffers.com/dc/index.htm';
    case 'albany':
        return 'https://www.audialbany.com/';
    case 'delaware-valley':
        return 'https://www.audioffers.com/delaware-valley/index.htm';
    case 'hartford':
        return 'https://www.audioffers.com/hartford-new-haven/index.htm';
    case 'new-england':
        return 'https://www.audioffers.com/new-england/index.htm';
    case 'pittsburgh':
        return 'https://www.audioffers.com/pittsburgh/index.htm';
    case 'providence':
        return 'http://www.audioffers.com/east/index.htm?geoZip=02886';
    case 'tri-state':
        return 'https://www.audioffers.com/tri-state/index.htm';
    case 'albuquerque':
        return 'http://www.audiabq.com/';
    case 'boise':
        return 'https://www.audiboise.com/';
    case 'colorado-springs':
        return 'https://www.audicoloradosprings.com/';
    case 'denver':
        return 'https://www.audioffers.com/colorado/index.htm';
    case 'honolulu':
        return 'https://www.audihonolulu.com/';
    case 'las-vegas':
        return 'https://www.audioffers.com/las-vegas/index.htm';
    case 'los-angeles':
        return 'https://www.audioffers.com/southern-california/index.htm';
    case 'palm-springs':
        return 'https://www.audiranchomirage.com/';
    case 'phoenix':
        return 'https://www.audioffers.com/arizona/index.htm';
    case 'portland':
        return 'https://www.audioffers.com/oregon/index.htm';
    case 'reno':
        return 'https://www.audirenotahoe.com/';
    case 'sacramento':
        return 'https://www.audioffers.com/sacramento/index.htm';
    case 'salt-lake-city':
        return 'https://www.audioffers.com/utah/index.htm';
    case 'san-diego':
        return 'https://www.audioffers.com/san-diego/index.htm';
    case 'san-francisco':
        return 'https://www.audioffers.com/san-francisco/index.htm';
    case 'santa-barbara':
        return 'https://www.audisantabarbara.com/';
    case 'seattle':
        return 'https://www.audioffers.com/puget-sound/index.htm';
    case 'spokane':
        return 'https://www.audispokane.com/';
    default:
        return "https://audiusa.com";
    }
}

