console.log("loaded");
function getURL(urlKeyCode){
switch (urlKeyCode){
    case 'chicago||a3':
        return "https://www.audioffers.com/chicagoland/showroom/2019/Audi/A3/Sedan.htm";
    case 'chicago||a3-cabriolet':
        return "https://www.audioffers.com/chicagoland/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'chicago||a3-e-tron':
        return "https://www.audioffers.com/chicagoland/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'chicago||a4':
        return "https://www.audioffers.com/chicagoland/showroom/2019/Audi/A4/Sedan.htm";
    case 'chicago||a4-allroad':
        return "https://www.audioffers.com/chicagoland/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'chicago||a5':
        return "https://www.audioffers.com/chicagoland/showroom/2019/Audi/A5/Sedan.htm";
    case 'chicago||a5-cabriolet':
        return "https://www.audioffers.com/chicagoland/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'chicago||a5-coupe':
        return "https://www.audioffers.com/chicagoland/showroom/2019/Audi/A5/Coupe.htm";
    case 'chicago||a5-sportback':
        return "https://www.audioffers.com/chicagoland/showroom/2019/Audi/A5/Sportback.htm";
    case 'chicago||a6':
        return "https://www.audioffers.com/chicagoland/showroom/2019/Audi/A6/Sedan.htm";
    case 'chicago||a7':
        return "https://www.audioffers.com/chicagoland/showroom/2019/Audi/A7/Hatchback.htm";
    case 'chicago||a7-hatchback':
        return "https://www.audioffers.com/chicagoland/showroom/2019/Audi/A7/Hatchback.htm";
    case 'chicago||a8':
        return "https://www.audioffers.com/chicagoland/showroom/2019/Audi/A8/Sedan.htm";
    case 'chicago||q3':
        return "https://www.audioffers.com/chicagoland/showroom/2019/Audi/Q3/SUV.htm";
    case 'chicago||q5':
        return "https://www.audioffers.com/chicagoland/showroom/2019/Audi/Q5/SUV.htm";
    case 'chicago||q7':
        return "https://www.audioffers.com/chicagoland/showroom/2019/Audi/Q7/SUV.htm";
    case 'chicago||q8':
        return "https://www.audioffers.com/chicagoland/showroom/2019/Audi/Q8/SUV.htm";
    case 'chicago||rs3':
        return "https://www.audioffers.com/chicagoland/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'chicago||rs7-hatchback':
        return "https://www.audioffers.com/chicagoland/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'chicago||s3':
        return "https://www.audioffers.com/chicagoland/showroom/2019/Audi/S3/Sedan.htm";
    case 'chicago||s4':
        return "https://www.audioffers.com/chicagoland/showroom/2019/Audi/S4/Sedan.htm";
    case 'chicago||s5-cabriolet':
        return "https://www.audioffers.com/chicagoland/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'chicago||s5-coupe':
        return "https://www.audioffers.com/chicagoland/showroom/2019/Audi/S5/Coupe.htm";
    case 'chicago||s5-sportback':
        return "https://www.audioffers.com/chicagoland/showroom/2019/Audi/S5/Sportback.htm";
    case 'chicago||s6':
        return "https://www.audioffers.com/chicagoland/showroom/2019/Audi/S6/Sedan.htm";
    case 'chicago||s7-hatchback':
        return "https://www.audioffers.com/chicagoland/showroom/2019/Audi/S7/Hatchback.htm";
    case 'chicago||s8':
        return "https://www.audioffers.com/chicagoland/showroom/2019/Audi/S8/Sedan.htm";
    case 'chicago||tt-coupe':
        return "https://www.audioffers.com/chicagoland/showroom/2019/Audi/TT/Coupe.htm";
    case 'chicago||tts-coupe':
        return "https://www.audioffers.com/chicagoland/showroom/2019/Audi/TTS/Coupe.htm";
    case 'cincinnati||a3':
        return "https://www.audioffers.com/cincinnati/showroom/2019/Audi/A3/Sedan.htm";
    case 'cincinnati||a3-cabriolet':
        return "https://www.audioffers.com/cincinnati/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'cincinnati||a3-e-tron':
        return "https://www.audioffers.com/cincinnati/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'cincinnati||a4':
        return "https://www.audioffers.com/cincinnati/showroom/2019/Audi/A4/Sedan.htm";
    case 'cincinnati||a4-allroad':
        return "https://www.audioffers.com/cincinnati/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'cincinnati||a5':
        return "https://www.audioffers.com/cincinnati/showroom/2019/Audi/A5/Sedan.htm";
    case 'cincinnati||a5-cabriolet':
        return "https://www.audioffers.com/cincinnati/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'cincinnati||a5-coupe':
        return "https://www.audioffers.com/cincinnati/showroom/2019/Audi/A5/Coupe.htm";
    case 'cincinnati||a5-sportback':
        return "https://www.audioffers.com/cincinnati/showroom/2019/Audi/A5/Sportback.htm";
    case 'cincinnati||a6':
        return "https://www.audioffers.com/cincinnati/showroom/2019/Audi/A6/Sedan.htm";
    case 'cincinnati||a7':
        return "https://www.audioffers.com/cincinnati/showroom/2019/Audi/A7/Hatchback.htm";
    case 'cincinnati||a7-hatchback':
        return "https://www.audioffers.com/cincinnati/showroom/2019/Audi/A7/Hatchback.htm";
    case 'cincinnati||a8':
        return "https://www.audioffers.com/cincinnati/showroom/2019/Audi/A8/Sedan.htm";
    case 'cincinnati||q3':
        return "https://www.audioffers.com/cincinnati/showroom/2019/Audi/Q3/SUV.htm";
    case 'cincinnati||q5':
        return "https://www.audioffers.com/cincinnati/showroom/2019/Audi/Q5/SUV.htm";
    case 'cincinnati||q7':
        return "https://www.audioffers.com/cincinnati/showroom/2019/Audi/Q7/SUV.htm";
    case 'cincinnati||q8':
        return "https://www.audioffers.com/cincinnati/showroom/2019/Audi/Q8/SUV.htm";
    case 'cincinnati||rs3':
        return "https://www.audioffers.com/cincinnati/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'cincinnati||rs7-hatchback':
        return "https://www.audioffers.com/cincinnati/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'cincinnati||s3':
        return "https://www.audioffers.com/cincinnati/showroom/2019/Audi/S3/Sedan.htm";
    case 'cincinnati||s4':
        return "https://www.audioffers.com/cincinnati/showroom/2019/Audi/S4/Sedan.htm";
    case 'cincinnati||s5-cabriolet':
        return "https://www.audioffers.com/cincinnati/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'cincinnati||s5-coupe':
        return "https://www.audioffers.com/cincinnati/showroom/2019/Audi/S5/Coupe.htm";
    case 'cincinnati||s5-sportback':
        return "https://www.audioffers.com/cincinnati/showroom/2019/Audi/S5/Sportback.htm";
    case 'cincinnati||s6':
        return "https://www.audioffers.com/cincinnati/showroom/2019/Audi/S6/Sedan.htm";
    case 'cincinnati||s7-hatchback':
        return "https://www.audioffers.com/cincinnati/showroom/2019/Audi/S7/Hatchback.htm";
    case 'cincinnati||s8':
        return "https://www.audioffers.com/cincinnati/showroom/2019/Audi/S8/Sedan.htm";
    case 'cincinnati||tt-coupe':
        return "https://www.audioffers.com/cincinnati/showroom/2019/Audi/TT/Coupe.htm";
    case 'cincinnati||tts-coupe':
        return "https://www.audioffers.com/cincinnati/showroom/2019/Audi/TTS/Coupe.htm";
    case 'cleveland||a3':
        return "https://www.audioffers.com/cleveland/showroom/2019/Audi/A3/Sedan.htm";
    case 'cleveland||a3-cabriolet':
        return "https://www.audioffers.com/cleveland/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'cleveland||a3-e-tron':
        return "https://www.audioffers.com/cleveland/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'cleveland||a4':
        return "https://www.audioffers.com/cleveland/showroom/2019/Audi/A4/Sedan.htm";
    case 'cleveland||a4-allroad':
        return "https://www.audioffers.com/cleveland/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'cleveland||a5':
        return "https://www.audioffers.com/cleveland/showroom/2019/Audi/A5/Sedan.htm";
    case 'cleveland||a5-cabriolet':
        return "https://www.audioffers.com/cleveland/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'cleveland||a5-coupe':
        return "https://www.audioffers.com/cleveland/showroom/2019/Audi/A5/Coupe.htm";
    case 'cleveland||a5-sportback':
        return "https://www.audioffers.com/cleveland/showroom/2019/Audi/A5/Sportback.htm";
    case 'cleveland||a6':
        return "https://www.audioffers.com/cleveland/showroom/2019/Audi/A6/Sedan.htm";
    case 'cleveland||a7':
        return "https://www.audioffers.com/cleveland/showroom/2019/Audi/A7/Hatchback.htm";
    case 'cleveland||a7-hatchback':
        return "https://www.audioffers.com/cleveland/showroom/2019/Audi/A7/Hatchback.htm";
    case 'cleveland||a8':
        return "https://www.audioffers.com/cleveland/showroom/2019/Audi/A8/Sedan.htm";
    case 'cleveland||q3':
        return "https://www.audioffers.com/cleveland/showroom/2019/Audi/Q3/SUV.htm";
    case 'cleveland||q5':
        return "https://www.audioffers.com/cleveland/showroom/2019/Audi/Q5/SUV.htm";
    case 'cleveland||q7':
        return "https://www.audioffers.com/cleveland/showroom/2019/Audi/Q7/SUV.htm";
    case 'cleveland||q8':
        return "https://www.audioffers.com/cleveland/showroom/2019/Audi/Q8/SUV.htm";
    case 'cleveland||rs3':
        return "https://www.audioffers.com/cleveland/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'cleveland||rs7-hatchback':
        return "https://www.audioffers.com/cleveland/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'cleveland||s3':
        return "https://www.audioffers.com/cleveland/showroom/2019/Audi/S3/Sedan.htm";
    case 'cleveland||s4':
        return "https://www.audioffers.com/cleveland/showroom/2019/Audi/S4/Sedan.htm";
    case 'cleveland||s5-cabriolet':
        return "https://www.audioffers.com/cleveland/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'cleveland||s5-coupe':
        return "https://www.audioffers.com/cleveland/showroom/2019/Audi/S5/Coupe.htm";
    case 'cleveland||s5-sportback':
        return "https://www.audioffers.com/cleveland/showroom/2019/Audi/S5/Sportback.htm";
    case 'cleveland||s6':
        return "https://www.audioffers.com/cleveland/showroom/2019/Audi/S6/Sedan.htm";
    case 'cleveland||s7-hatchback':
        return "https://www.audioffers.com/cleveland/showroom/2019/Audi/S7/Hatchback.htm";
    case 'cleveland||s8':
        return "https://www.audioffers.com/cleveland/showroom/2019/Audi/S8/Sedan.htm";
    case 'cleveland||tt-coupe':
        return "https://www.audioffers.com/cleveland/showroom/2019/Audi/TT/Coupe.htm";
    case 'cleveland||tts-coupe':
        return "https://www.audioffers.com/cleveland/showroom/2019/Audi/TTS/Coupe.htm";
    case 'columbus||a3':
        return "https://www.audioffers.com/columbus/showroom/2019/Audi/A3/Sedan.htm";
    case 'columbus||a3-cabriolet':
        return "https://www.audioffers.com/columbus/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'columbus||a3-e-tron':
        return "https://www.audioffers.com/columbus/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'columbus||a4':
        return "https://www.audioffers.com/columbus/showroom/2019/Audi/A4/Sedan.htm";
    case 'columbus||a4-allroad':
        return "https://www.audioffers.com/columbus/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'columbus||a5':
        return "https://www.audioffers.com/columbus/showroom/2019/Audi/A5/Sedan.htm";
    case 'columbus||a5-cabriolet':
        return "https://www.audioffers.com/columbus/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'columbus||a5-coupe':
        return "https://www.audioffers.com/columbus/showroom/2019/Audi/A5/Coupe.htm";
    case 'columbus||a5-sportback':
        return "https://www.audioffers.com/columbus/showroom/2019/Audi/A5/Sportback.htm";
    case 'columbus||a6':
        return "https://www.audioffers.com/columbus/showroom/2019/Audi/A6/Sedan.htm";
    case 'columbus||a7':
        return "https://www.audioffers.com/columbus/showroom/2019/Audi/A7/Hatchback.htm";
    case 'columbus||a7-hatchback':
        return "https://www.audioffers.com/columbus/showroom/2019/Audi/A7/Hatchback.htm";
    case 'columbus||a8':
        return "https://www.audioffers.com/columbus/showroom/2019/Audi/A8/Sedan.htm";
    case 'columbus||q3':
        return "https://www.audioffers.com/columbus/showroom/2019/Audi/Q3/SUV.htm";
    case 'columbus||q5':
        return "https://www.audioffers.com/columbus/showroom/2019/Audi/Q5/SUV.htm";
    case 'columbus||q7':
        return "https://www.audioffers.com/columbus/showroom/2019/Audi/Q7/SUV.htm";
    case 'columbus||q8':
        return "https://www.audioffers.com/columbus/showroom/2019/Audi/Q8/SUV.htm";
    case 'columbus||rs3':
        return "https://www.audioffers.com/columbus/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'columbus||rs7-hatchback':
        return "https://www.audioffers.com/columbus/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'columbus||s3':
        return "https://www.audioffers.com/columbus/showroom/2019/Audi/S3/Sedan.htm";
    case 'columbus||s4':
        return "https://www.audioffers.com/columbus/showroom/2019/Audi/S4/Sedan.htm";
    case 'columbus||s5-cabriolet':
        return "https://www.audioffers.com/columbus/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'columbus||s5-coupe':
        return "https://www.audioffers.com/columbus/showroom/2019/Audi/S5/Coupe.htm";
    case 'columbus||s5-sportback':
        return "https://www.audioffers.com/columbus/showroom/2019/Audi/S5/Sportback.htm";
    case 'columbus||s6':
        return "https://www.audioffers.com/columbus/showroom/2019/Audi/S6/Sedan.htm";
    case 'columbus||s7-hatchback':
        return "https://www.audioffers.com/columbus/showroom/2019/Audi/S7/Hatchback.htm";
    case 'columbus||s8':
        return "https://www.audioffers.com/columbus/showroom/2019/Audi/S8/Sedan.htm";
    case 'columbus||tt-coupe':
        return "https://www.audioffers.com/columbus/showroom/2019/Audi/TT/Coupe.htm";
    case 'columbus||tts-coupe':
        return "https://www.audioffers.com/columbus/showroom/2019/Audi/TTS/Coupe.htm";
    case 'detroit||a3':
        return "https://www.audioffers.com/detroit/showroom/2019/Audi/A3/Sedan.htm";
    case 'detroit||a3-cabriolet':
        return "https://www.audioffers.com/detroit/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'detroit||a3-e-tron':
        return "https://www.audioffers.com/detroit/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'detroit||a4':
        return "https://www.audioffers.com/detroit/showroom/2019/Audi/A4/Sedan.htm";
    case 'detroit||a4-allroad':
        return "https://www.audioffers.com/detroit/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'detroit||a5':
        return "https://www.audioffers.com/detroit/showroom/2019/Audi/A5/Sedan.htm";
    case 'detroit||a5-cabriolet':
        return "https://www.audioffers.com/detroit/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'detroit||a5-coupe':
        return "https://www.audioffers.com/detroit/showroom/2019/Audi/A5/Coupe.htm";
    case 'detroit||a5-sportback':
        return "https://www.audioffers.com/detroit/showroom/2019/Audi/A5/Sportback.htm";
    case 'detroit||a6':
        return "https://www.audioffers.com/detroit/showroom/2019/Audi/A6/Sedan.htm";
    case 'detroit||a7':
        return "https://www.audioffers.com/detroit/showroom/2019/Audi/A7/Hatchback.htm";
    case 'detroit||a7-hatchback':
        return "https://www.audioffers.com/detroit/showroom/2019/Audi/A7/Hatchback.htm";
    case 'detroit||a8':
        return "https://www.audioffers.com/detroit/showroom/2019/Audi/A8/Sedan.htm";
    case 'detroit||q3':
        return "https://www.audioffers.com/detroit/showroom/2019/Audi/Q3/SUV.htm";
    case 'detroit||q5':
        return "https://www.audioffers.com/detroit/showroom/2019/Audi/Q5/SUV.htm";
    case 'detroit||q7':
        return "https://www.audioffers.com/detroit/showroom/2019/Audi/Q7/SUV.htm";
    case 'detroit||q8':
        return "https://www.audioffers.com/detroit/showroom/2019/Audi/Q8/SUV.htm";
    case 'detroit||rs3':
        return "https://www.audioffers.com/detroit/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'detroit||rs7-hatchback':
        return "https://www.audioffers.com/detroit/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'detroit||s3':
        return "https://www.audioffers.com/detroit/showroom/2019/Audi/S3/Sedan.htm";
    case 'detroit||s4':
        return "https://www.audioffers.com/detroit/showroom/2019/Audi/S4/Sedan.htm";
    case 'detroit||s5-cabriolet':
        return "https://www.audioffers.com/detroit/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'detroit||s5-coupe':
        return "https://www.audioffers.com/detroit/showroom/2019/Audi/S5/Coupe.htm";
    case 'detroit||s5-sportback':
        return "https://www.audioffers.com/detroit/showroom/2019/Audi/S5/Sportback.htm";
    case 'detroit||s6':
        return "https://www.audioffers.com/detroit/showroom/2019/Audi/S6/Sedan.htm";
    case 'detroit||s7-hatchback':
        return "https://www.audioffers.com/detroit/showroom/2019/Audi/S7/Hatchback.htm";
    case 'detroit||s8':
        return "https://www.audioffers.com/detroit/showroom/2019/Audi/S8/Sedan.htm";
    case 'detroit||tt-coupe':
        return "https://www.audioffers.com/detroit/showroom/2019/Audi/TT/Coupe.htm";
    case 'detroit||tts-coupe':
        return "https://www.audioffers.com/detroit/showroom/2019/Audi/TTS/Coupe.htm";
    case 'grand-rapids||a3':
        return "https://www.audigrandrapids.com/showroom/2019/Audi/A3/Sedan.htm";
    case 'grand-rapids||a3-cabriolet':
        return "https://www.audigrandrapids.com/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'grand-rapids||a3-e-tron':
        return "https://www.audigrandrapids.com/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'grand-rapids||a4':
        return "https://www.audigrandrapids.com/showroom/2019/Audi/A4/Sedan.htm";
    case 'grand-rapids||a4-allroad':
        return "https://www.audigrandrapids.com/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'grand-rapids||a5':
        return "https://www.audigrandrapids.com/showroom/2019/Audi/A5/Sedan.htm";
    case 'grand-rapids||a5-cabriolet':
        return "https://www.audigrandrapids.com/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'grand-rapids||a5-coupe':
        return "https://www.audigrandrapids.com/showroom/2019/Audi/A5/Coupe.htm";
    case 'grand-rapids||a5-sportback':
        return "https://www.audigrandrapids.com/showroom/2019/Audi/A5/Sportback.htm";
    case 'grand-rapids||a6':
        return "https://www.audigrandrapids.com/showroom/2019/Audi/A6/Sedan.htm";
    case 'grand-rapids||a7':
        return "https://www.audigrandrapids.com/showroom/2019/Audi/A7/Hatchback.htm";
    case 'grand-rapids||a7-hatchback':
        return "https://www.audigrandrapids.com/showroom/2019/Audi/A7/Hatchback.htm";
    case 'grand-rapids||a8':
        return "https://www.audigrandrapids.com/showroom/2019/Audi/A8/Sedan.htm";
    case 'grand-rapids||q3':
        return "https://www.audigrandrapids.com/showroom/2019/Audi/Q3/SUV.htm";
    case 'grand-rapids||q5':
        return "https://www.audigrandrapids.com/showroom/2019/Audi/Q5/SUV.htm";
    case 'grand-rapids||q7':
        return "https://www.audigrandrapids.com/showroom/2019/Audi/Q7/SUV.htm";
    case 'grand-rapids||q8':
        return "https://www.audigrandrapids.com/showroom/2019/Audi/Q8/SUV.htm";
    case 'grand-rapids||rs3':
        return "https://www.audigrandrapids.com/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'grand-rapids||rs7-hatchback':
        return "https://www.audigrandrapids.com/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'grand-rapids||s3':
        return "https://www.audigrandrapids.com/showroom/2019/Audi/S3/Sedan.htm";
    case 'grand-rapids||s4':
        return "https://www.audigrandrapids.com/showroom/2019/Audi/S4/Sedan.htm";
    case 'grand-rapids||s5-cabriolet':
        return "https://www.audigrandrapids.com/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'grand-rapids||s5-coupe':
        return "https://www.audigrandrapids.com/showroom/2019/Audi/S5/Coupe.htm";
    case 'grand-rapids||s5-sportback':
        return "https://www.audigrandrapids.com/showroom/2019/Audi/S5/Sportback.htm";
    case 'grand-rapids||s6':
        return "https://www.audigrandrapids.com/showroom/2019/Audi/S6/Sedan.htm";
    case 'grand-rapids||s7-hatchback':
        return "https://www.audigrandrapids.com/showroom/2019/Audi/S7/Hatchback.htm";
    case 'grand-rapids||s8':
        return "https://www.audigrandrapids.com/showroom/2019/Audi/S8/Sedan.htm";
    case 'grand-rapids||tt-coupe':
        return "https://www.audigrandrapids.com/showroom/2019/Audi/TT/Coupe.htm";
    case 'grand-rapids||tts-coupe':
        return "https://www.audigrandrapids.com/showroom/2019/Audi/TTS/Coupe.htm";
    case 'indianapolis||a3':
        return "https://www.audiindianapolis.com/showroom/2019/Audi/A3/Sedan.htm";
    case 'indianapolis||a3-cabriolet':
        return "https://www.audiindianapolis.com/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'indianapolis||a3-e-tron':
        return "https://www.audiindianapolis.com/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'indianapolis||a4':
        return "https://www.audiindianapolis.com/showroom/2019/Audi/A4/Sedan.htm";
    case 'indianapolis||a4-allroad':
        return "https://www.audiindianapolis.com/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'indianapolis||a5':
        return "https://www.audiindianapolis.com/showroom/2019/Audi/A5/Sedan.htm";
    case 'indianapolis||a5-cabriolet':
        return "https://www.audiindianapolis.com/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'indianapolis||a5-coupe':
        return "https://www.audiindianapolis.com/showroom/2019/Audi/A5/Coupe.htm";
    case 'indianapolis||a5-sportback':
        return "https://www.audiindianapolis.com/showroom/2019/Audi/A5/Sportback.htm";
    case 'indianapolis||a6':
        return "https://www.audiindianapolis.com/showroom/2019/Audi/A6/Sedan.htm";
    case 'indianapolis||a7':
        return "https://www.audiindianapolis.com/showroom/2019/Audi/A7/Hatchback.htm";
    case 'indianapolis||a7-hatchback':
        return "https://www.audiindianapolis.com/showroom/2019/Audi/A7/Hatchback.htm";
    case 'indianapolis||a8':
        return "https://www.audiindianapolis.com/showroom/2019/Audi/A8/Sedan.htm";
    case 'indianapolis||q3':
        return "https://www.audiindianapolis.com/showroom/2019/Audi/Q3/SUV.htm";
    case 'indianapolis||q5':
        return "https://www.audiindianapolis.com/showroom/2019/Audi/Q5/SUV.htm";
    case 'indianapolis||q7':
        return "https://www.audiindianapolis.com/showroom/2019/Audi/Q7/SUV.htm";
    case 'indianapolis||q8':
        return "https://www.audiindianapolis.com/showroom/2019/Audi/Q8/SUV.htm";
    case 'indianapolis||rs3':
        return "https://www.audiindianapolis.com/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'indianapolis||rs7-hatchback':
        return "https://www.audiindianapolis.com/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'indianapolis||s3':
        return "https://www.audiindianapolis.com/showroom/2019/Audi/S3/Sedan.htm";
    case 'indianapolis||s4':
        return "https://www.audiindianapolis.com/showroom/2019/Audi/S4/Sedan.htm";
    case 'indianapolis||s5-cabriolet':
        return "https://www.audiindianapolis.com/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'indianapolis||s5-coupe':
        return "https://www.audiindianapolis.com/showroom/2019/Audi/S5/Coupe.htm";
    case 'indianapolis||s5-sportback':
        return "https://www.audiindianapolis.com/showroom/2019/Audi/S5/Sportback.htm";
    case 'indianapolis||s6':
        return "https://www.audiindianapolis.com/showroom/2019/Audi/S6/Sedan.htm";
    case 'indianapolis||s7-hatchback':
        return "https://www.audiindianapolis.com/showroom/2019/Audi/S7/Hatchback.htm";
    case 'indianapolis||s8':
        return "https://www.audiindianapolis.com/showroom/2019/Audi/S8/Sedan.htm";
    case 'indianapolis||tt-coupe':
        return "https://www.audiindianapolis.com/showroom/2019/Audi/TT/Coupe.htm";
    case 'indianapolis||tts-coupe':
        return "https://www.audiindianapolis.com/showroom/2019/Audi/TTS/Coupe.htm";
    case 'kansas-city||a3':
        return "http://www.audioffers.com/kansas-city/showroom/2019/Audi/A3/Sedan.htm?geoZip=64114";
    case 'kansas-city||a3-cabriolet':
        return "http://www.audioffers.com/kansas-city/showroom/2019/Audi/A3/Cabriolet.htm?geoZip=64114";
    case 'kansas-city||a3-e-tron':
        return "http://www.audioffers.com/kansas-city/showroom/2019/Audi/A3+e-tron/Hatchback.htm?geoZip=64114";
    case 'kansas-city||a4':
        return "http://www.audioffers.com/kansas-city/showroom/2019/Audi/A4/Sedan.htm?geoZip=64114";
    case 'kansas-city||a4-allroad':
        return "http://www.audioffers.com/kansas-city/showroom/2019/Audi/A4+allroad/Wagon.htm?geoZip=64114";
    case 'kansas-city||a5':
        return "http://www.audioffers.com/kansas-city/showroom/2019/Audi/A5/Sedan.htm?geoZip=64114";
    case 'kansas-city||a5-cabriolet':
        return "http://www.audioffers.com/kansas-city/showroom/2019/Audi/A5/Cabriolet.htm?geoZip=64114";
    case 'kansas-city||a5-coupe':
        return "http://www.audioffers.com/kansas-city/showroom/2019/Audi/A5/Coupe.htm?geoZip=64114";
    case 'kansas-city||a5-sportback':
        return "http://www.audioffers.com/kansas-city/showroom/2019/Audi/A5/Sportback.htm?geoZip=64114";
    case 'kansas-city||a6':
        return "http://www.audioffers.com/kansas-city/showroom/2019/Audi/A6/Sedan.htm?geoZip=64114";
    case 'kansas-city||a7':
        return "http://www.audioffers.com/kansas-city/showroom/2019/Audi/A7/Hatchback.htm?geoZip=64114";
    case 'kansas-city||a7-hatchback':
        return "http://www.audioffers.com/kansas-city/showroom/2019/Audi/A7/Hatchback.htm?geoZip=64114";
    case 'kansas-city||a8':
        return "http://www.audioffers.com/kansas-city/showroom/2019/Audi/A8/Sedan.htm?geoZip=64114";
    case 'kansas-city||q3':
        return "http://www.audioffers.com/kansas-city/showroom/2019/Audi/Q3/SUV.htm?geoZip=64114";
    case 'kansas-city||q5':
        return "http://www.audioffers.com/kansas-city/showroom/2019/Audi/Q5/SUV.htm?geoZip=64114";
    case 'kansas-city||q7':
        return "http://www.audioffers.com/kansas-city/showroom/2019/Audi/Q7/SUV.htm?geoZip=64114";
    case 'kansas-city||q8':
        return "http://www.audioffers.com/kansas-city/showroom/2019/Audi/Q8/SUV.htm?geoZip=64114";
    case 'kansas-city||rs3':
        return "http://www.audioffers.com/kansas-city/showroom/2019/Audi/RS+3/Sedan.htm?geoZip=64114";
    case 'kansas-city||rs7-hatchback':
        return "http://www.audioffers.com/kansas-city/showroom/2019/Audi/RS+7/Hatchback.htm?geoZip=64114";
    case 'kansas-city||s3':
        return "http://www.audioffers.com/kansas-city/showroom/2019/Audi/S3/Sedan.htm?geoZip=64114";
    case 'kansas-city||s4':
        return "http://www.audioffers.com/kansas-city/showroom/2019/Audi/S4/Sedan.htm?geoZip=64114";
    case 'kansas-city||s5-cabriolet':
        return "http://www.audioffers.com/kansas-city/showroom/2019/Audi/S5/Cabriolet.htm?geoZip=64114";
    case 'kansas-city||s5-coupe':
        return "http://www.audioffers.com/kansas-city/showroom/2019/Audi/S5/Coupe.htm?geoZip=64114";
    case 'kansas-city||s5-sportback':
        return "http://www.audioffers.com/kansas-city/showroom/2019/Audi/S5/Sportback.htm?geoZip=64114";
    case 'kansas-city||s6':
        return "http://www.audioffers.com/kansas-city/showroom/2019/Audi/S6/Sedan.htm?geoZip=64114";
    case 'kansas-city||s7-hatchback':
        return "http://www.audioffers.com/kansas-city/showroom/2019/Audi/S7/Hatchback.htm?geoZip=64114";
    case 'kansas-city||s8':
        return "http://www.audioffers.com/kansas-city/showroom/2019/Audi/S8/Sedan.htm?geoZip=64114";
    case 'kansas-city||tt-coupe':
        return "http://www.audioffers.com/kansas-city/showroom/2019/Audi/TT/Coupe.htm?geoZip=64114";
    case 'kansas-city||tts-coupe':
        return "http://www.audioffers.com/kansas-city/showroom/2019/Audi/TTS/Coupe.htm?geoZip=64114";
    case 'louisville||a3':
        return "https://www.audilouisville.com/showroom/2019/Audi/A3/Sedan.htm";
    case 'louisville||a3-cabriolet':
        return "https://www.audilouisville.com/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'louisville||a3-e-tron':
        return "https://www.audilouisville.com/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'louisville||a4':
        return "https://www.audilouisville.com/showroom/2019/Audi/A4/Sedan.htm";
    case 'louisville||a4-allroad':
        return "https://www.audilouisville.com/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'louisville||a5':
        return "https://www.audilouisville.com/showroom/2019/Audi/A5/Sedan.htm";
    case 'louisville||a5-cabriolet':
        return "https://www.audilouisville.com/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'louisville||a5-coupe':
        return "https://www.audilouisville.com/showroom/2019/Audi/A5/Coupe.htm";
    case 'louisville||a5-sportback':
        return "https://www.audilouisville.com/showroom/2019/Audi/A5/Sportback.htm";
    case 'louisville||a6':
        return "https://www.audilouisville.com/showroom/2019/Audi/A6/Sedan.htm";
    case 'louisville||a7':
        return "https://www.audilouisville.com/showroom/2019/Audi/A7/Hatchback.htm";
    case 'louisville||a7-hatchback':
        return "https://www.audilouisville.com/showroom/2019/Audi/A7/Hatchback.htm";
    case 'louisville||a8':
        return "https://www.audilouisville.com/showroom/2019/Audi/A8/Sedan.htm";
    case 'louisville||q3':
        return "https://www.audilouisville.com/showroom/2019/Audi/Q3/SUV.htm";
    case 'louisville||q5':
        return "https://www.audilouisville.com/showroom/2019/Audi/Q5/SUV.htm";
    case 'louisville||q7':
        return "https://www.audilouisville.com/showroom/2019/Audi/Q7/SUV.htm";
    case 'louisville||q8':
        return "https://www.audilouisville.com/showroom/2019/Audi/Q8/SUV.htm";
    case 'louisville||rs3':
        return "https://www.audilouisville.com/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'louisville||rs7-hatchback':
        return "https://www.audilouisville.com/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'louisville||s3':
        return "https://www.audilouisville.com/showroom/2019/Audi/S3/Sedan.htm";
    case 'louisville||s4':
        return "https://www.audilouisville.com/showroom/2019/Audi/S4/Sedan.htm";
    case 'louisville||s5-cabriolet':
        return "https://www.audilouisville.com/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'louisville||s5-coupe':
        return "https://www.audilouisville.com/showroom/2019/Audi/S5/Coupe.htm";
    case 'louisville||s5-sportback':
        return "https://www.audilouisville.com/showroom/2019/Audi/S5/Sportback.htm";
    case 'louisville||s6':
        return "https://www.audilouisville.com/showroom/2019/Audi/S6/Sedan.htm";
    case 'louisville||s7-hatchback':
        return "https://www.audilouisville.com/showroom/2019/Audi/S7/Hatchback.htm";
    case 'louisville||s8':
        return "https://www.audilouisville.com/showroom/2019/Audi/S8/Sedan.htm";
    case 'louisville||tt-coupe':
        return "https://www.audilouisville.com/showroom/2019/Audi/TT/Coupe.htm";
    case 'louisville||tts-coupe':
        return "https://www.audilouisville.com/showroom/2019/Audi/TTS/Coupe.htm";
    case 'minneapolis||a3':
        return "https://www.audioffers.com/twin-cities/showroom/2019/Audi/A3/Sedan.htm?geoZip=55109";
    case 'minneapolis||a3-cabriolet':
        return "https://www.audioffers.com/twin-cities/showroom/2019/Audi/A3/Cabriolet.htm?geoZip=55109";
    case 'minneapolis||a3-e-tron':
        return "https://www.audioffers.com/twin-cities/showroom/2019/Audi/A3+e-tron/Hatchback.htm?geoZip=55109";
    case 'minneapolis||a4':
        return "https://www.audioffers.com/twin-cities/showroom/2019/Audi/A4/Sedan.htm?geoZip=55109";
    case 'minneapolis||a4-allroad':
        return "https://www.audioffers.com/twin-cities/showroom/2019/Audi/A4+allroad/Wagon.htm?geoZip=55109";
    case 'minneapolis||a5':
        return "https://www.audioffers.com/twin-cities/showroom/2019/Audi/A5/Sedan.htm?geoZip=55109";
    case 'minneapolis||a5-cabriolet':
        return "https://www.audioffers.com/twin-cities/showroom/2019/Audi/A5/Cabriolet.htm?geoZip=55109";
    case 'minneapolis||a5-coupe':
        return "https://www.audioffers.com/twin-cities/showroom/2019/Audi/A5/Coupe.htm?geoZip=55109";
    case 'minneapolis||a5-sportback':
        return "https://www.audioffers.com/twin-cities/showroom/2019/Audi/A5/Sportback.htm?geoZip=55109";
    case 'minneapolis||a6':
        return "https://www.audioffers.com/twin-cities/showroom/2019/Audi/A6/Sedan.htm?geoZip=55109";
    case 'minneapolis||a7':
        return "https://www.audioffers.com/twin-cities/showroom/2019/Audi/A7/Hatchback.htm?geoZip=55109";
    case 'minneapolis||a7-hatchback':
        return "https://www.audioffers.com/twin-cities/showroom/2019/Audi/A7/Hatchback.htm?geoZip=55109";
    case 'minneapolis||a8':
        return "https://www.audioffers.com/twin-cities/showroom/2019/Audi/A8/Sedan.htm?geoZip=55109";
    case 'minneapolis||q3':
        return "https://www.audioffers.com/twin-cities/showroom/2019/Audi/Q3/SUV.htm?geoZip=55109";
    case 'minneapolis||q5':
        return "https://www.audioffers.com/twin-cities/showroom/2019/Audi/Q5/SUV.htm?geoZip=55109";
    case 'minneapolis||q7':
        return "https://www.audioffers.com/twin-cities/showroom/2019/Audi/Q7/SUV.htm?geoZip=55109";
    case 'minneapolis||q8':
        return "https://www.audioffers.com/twin-cities/showroom/2019/Audi/Q8/SUV.htm?geoZip=55109";
    case 'minneapolis||rs3':
        return "https://www.audioffers.com/twin-cities/showroom/2019/Audi/RS+3/Sedan.htm?geoZip=55109";
    case 'minneapolis||rs7-hatchback':
        return "https://www.audioffers.com/twin-cities/showroom/2019/Audi/RS+7/Hatchback.htm?geoZip=55109";
    case 'minneapolis||s3':
        return "https://www.audioffers.com/twin-cities/showroom/2019/Audi/S3/Sedan.htm?geoZip=55109";
    case 'minneapolis||s4':
        return "https://www.audioffers.com/twin-cities/showroom/2019/Audi/S4/Sedan.htm?geoZip=55109";
    case 'minneapolis||s5-cabriolet':
        return "https://www.audioffers.com/twin-cities/showroom/2019/Audi/S5/Cabriolet.htm?geoZip=55109";
    case 'minneapolis||s5-coupe':
        return "https://www.audioffers.com/twin-cities/showroom/2019/Audi/S5/Coupe.htm?geoZip=55109";
    case 'minneapolis||s5-sportback':
        return "https://www.audioffers.com/twin-cities/showroom/2019/Audi/S5/Sportback.htm?geoZip=55109";
    case 'minneapolis||s6':
        return "https://www.audioffers.com/twin-cities/showroom/2019/Audi/S6/Sedan.htm?geoZip=55109";
    case 'minneapolis||s7-hatchback':
        return "https://www.audioffers.com/twin-cities/showroom/2019/Audi/S7/Hatchback.htm?geoZip=55109";
    case 'minneapolis||s8':
        return "https://www.audioffers.com/twin-cities/showroom/2019/Audi/S8/Sedan.htm?geoZip=55109";
    case 'minneapolis||tt-coupe':
        return "https://www.audioffers.com/twin-cities/showroom/2019/Audi/TT/Coupe.htm?geoZip=55109";
    case 'minneapolis||tts-coupe':
        return "https://www.audioffers.com/twin-cities/showroom/2019/Audi/TTS/Coupe.htm?geoZip=55109";
    case 'st-louis||a3':
        return "https://www.audioffers.com/st-louis/showroom/2019/Audi/A3/Sedan.htm";
    case 'st-louis||a3-cabriolet':
        return "https://www.audioffers.com/st-louis/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'st-louis||a3-e-tron':
        return "https://www.audioffers.com/st-louis/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'st-louis||a4':
        return "https://www.audioffers.com/st-louis/showroom/2019/Audi/A4/Sedan.htm";
    case 'st-louis||a4-allroad':
        return "https://www.audioffers.com/st-louis/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'st-louis||a5':
        return "https://www.audioffers.com/st-louis/showroom/2019/Audi/A5/Sedan.htm";
    case 'st-louis||a5-cabriolet':
        return "https://www.audioffers.com/st-louis/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'st-louis||a5-coupe':
        return "https://www.audioffers.com/st-louis/showroom/2019/Audi/A5/Coupe.htm";
    case 'st-louis||a5-sportback':
        return "https://www.audioffers.com/st-louis/showroom/2019/Audi/A5/Sportback.htm";
    case 'st-louis||a6':
        return "https://www.audioffers.com/st-louis/showroom/2019/Audi/A6/Sedan.htm";
    case 'st-louis||a7':
        return "https://www.audioffers.com/st-louis/showroom/2019/Audi/A7/Hatchback.htm";
    case 'st-louis||a7-hatchback':
        return "https://www.audioffers.com/st-louis/showroom/2019/Audi/A7/Hatchback.htm";
    case 'st-louis||a8':
        return "https://www.audioffers.com/st-louis/showroom/2019/Audi/A8/Sedan.htm";
    case 'st-louis||q3':
        return "https://www.audioffers.com/st-louis/showroom/2019/Audi/Q3/SUV.htm";
    case 'st-louis||q5':
        return "https://www.audioffers.com/st-louis/showroom/2019/Audi/Q5/SUV.htm";
    case 'st-louis||q7':
        return "https://www.audioffers.com/st-louis/showroom/2019/Audi/Q7/SUV.htm";
    case 'st-louis||q8':
        return "https://www.audioffers.com/st-louis/showroom/2019/Audi/Q8/SUV.htm";
    case 'st-louis||rs3':
        return "https://www.audioffers.com/st-louis/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'st-louis||rs7-hatchback':
        return "https://www.audioffers.com/st-louis/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'st-louis||s3':
        return "https://www.audioffers.com/st-louis/showroom/2019/Audi/S3/Sedan.htm";
    case 'st-louis||s4':
        return "https://www.audioffers.com/st-louis/showroom/2019/Audi/S4/Sedan.htm";
    case 'st-louis||s5-cabriolet':
        return "https://www.audioffers.com/st-louis/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'st-louis||s5-coupe':
        return "https://www.audioffers.com/st-louis/showroom/2019/Audi/S5/Coupe.htm";
    case 'st-louis||s5-sportback':
        return "https://www.audioffers.com/st-louis/showroom/2019/Audi/S5/Sportback.htm";
    case 'st-louis||s6':
        return "https://www.audioffers.com/st-louis/showroom/2019/Audi/S6/Sedan.htm";
    case 'st-louis||s7-hatchback':
        return "https://www.audioffers.com/st-louis/showroom/2019/Audi/S7/Hatchback.htm";
    case 'st-louis||s8':
        return "https://www.audioffers.com/st-louis/showroom/2019/Audi/S8/Sedan.htm";
    case 'st-louis||tt-coupe':
        return "https://www.audioffers.com/st-louis/showroom/2019/Audi/TT/Coupe.htm";
    case 'st-louis||tts-coupe':
        return "https://www.audioffers.com/st-louis/showroom/2019/Audi/TTS/Coupe.htm";
    case 'toledo||a3':
        return "https://www.sylvaniaaudi.com/showroom/2019/Audi/A3/Sedan.htm";
    case 'toledo||a3-cabriolet':
        return "https://www.sylvaniaaudi.com/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'toledo||a3-e-tron':
        return "https://www.sylvaniaaudi.com/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'toledo||a4':
        return "https://www.sylvaniaaudi.com/showroom/2019/Audi/A4/Sedan.htm";
    case 'toledo||a4-allroad':
        return "https://www.sylvaniaaudi.com/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'toledo||a5':
        return "https://www.sylvaniaaudi.com/showroom/2019/Audi/A5/Sedan.htm";
    case 'toledo||a5-cabriolet':
        return "https://www.sylvaniaaudi.com/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'toledo||a5-coupe':
        return "https://www.sylvaniaaudi.com/showroom/2019/Audi/A5/Coupe.htm";
    case 'toledo||a5-sportback':
        return "https://www.sylvaniaaudi.com/showroom/2019/Audi/A5/Sportback.htm";
    case 'toledo||a6':
        return "https://www.sylvaniaaudi.com/showroom/2019/Audi/A6/Sedan.htm";
    case 'toledo||a7':
        return "https://www.sylvaniaaudi.com/showroom/2019/Audi/A7/Hatchback.htm";
    case 'toledo||a7-hatchback':
        return "https://www.sylvaniaaudi.com/showroom/2019/Audi/A7/Hatchback.htm";
    case 'toledo||a8':
        return "https://www.sylvaniaaudi.com/showroom/2019/Audi/A8/Sedan.htm";
    case 'toledo||q3':
        return "https://www.sylvaniaaudi.com/showroom/2019/Audi/Q3/SUV.htm";
    case 'toledo||q5':
        return "https://www.sylvaniaaudi.com/showroom/2019/Audi/Q5/SUV.htm";
    case 'toledo||q7':
        return "https://www.sylvaniaaudi.com/showroom/2019/Audi/Q7/SUV.htm";
    case 'toledo||q8':
        return "https://www.sylvaniaaudi.com/showroom/2019/Audi/Q8/SUV.htm";
    case 'toledo||rs3':
        return "https://www.sylvaniaaudi.com/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'toledo||rs7-hatchback':
        return "https://www.sylvaniaaudi.com/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'toledo||s3':
        return "https://www.sylvaniaaudi.com/showroom/2019/Audi/S3/Sedan.htm";
    case 'toledo||s4':
        return "https://www.sylvaniaaudi.com/showroom/2019/Audi/S4/Sedan.htm";
    case 'toledo||s5-cabriolet':
        return "https://www.sylvaniaaudi.com/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'toledo||s5-coupe':
        return "https://www.sylvaniaaudi.com/showroom/2019/Audi/S5/Coupe.htm";
    case 'toledo||s5-sportback':
        return "https://www.sylvaniaaudi.com/showroom/2019/Audi/S5/Sportback.htm";
    case 'toledo||s6':
        return "https://www.sylvaniaaudi.com/showroom/2019/Audi/S6/Sedan.htm";
    case 'toledo||s7-hatchback':
        return "https://www.sylvaniaaudi.com/showroom/2019/Audi/S7/Hatchback.htm";
    case 'toledo||s8':
        return "https://www.sylvaniaaudi.com/showroom/2019/Audi/S8/Sedan.htm";
    case 'toledo||tt-coupe':
        return "https://www.sylvaniaaudi.com/showroom/2019/Audi/TT/Coupe.htm";
    case 'toledo||tts-coupe':
        return "https://www.sylvaniaaudi.com/showroom/2019/Audi/TTS/Coupe.htm";
    case 'wichita||a3':
        return "https://www.audiwichita.com/showroom/2019/Audi/A3/Sedan.htm";
    case 'wichita||a3-cabriolet':
        return "https://www.audiwichita.com/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'wichita||a3-e-tron':
        return "https://www.audiwichita.com/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'wichita||a4':
        return "https://www.audiwichita.com/showroom/2019/Audi/A4/Sedan.htm";
    case 'wichita||a4-allroad':
        return "https://www.audiwichita.com/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'wichita||a5':
        return "https://www.audiwichita.com/showroom/2019/Audi/A5/Sedan.htm";
    case 'wichita||a5-cabriolet':
        return "https://www.audiwichita.com/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'wichita||a5-coupe':
        return "https://www.audiwichita.com/showroom/2019/Audi/A5/Coupe.htm";
    case 'wichita||a5-sportback':
        return "https://www.audiwichita.com/showroom/2019/Audi/A5/Sportback.htm";
    case 'wichita||a6':
        return "https://www.audiwichita.com/showroom/2019/Audi/A6/Sedan.htm";
    case 'wichita||a7':
        return "https://www.audiwichita.com/showroom/2019/Audi/A7/Hatchback.htm";
    case 'wichita||a7-hatchback':
        return "https://www.audiwichita.com/showroom/2019/Audi/A7/Hatchback.htm";
    case 'wichita||a8':
        return "https://www.audiwichita.com/showroom/2019/Audi/A8/Sedan.htm";
    case 'wichita||q3':
        return "https://www.audiwichita.com/showroom/2019/Audi/Q3/SUV.htm";
    case 'wichita||q5':
        return "https://www.audiwichita.com/showroom/2019/Audi/Q5/SUV.htm";
    case 'wichita||q7':
        return "https://www.audiwichita.com/showroom/2019/Audi/Q7/SUV.htm";
    case 'wichita||q8':
        return "https://www.audiwichita.com/showroom/2019/Audi/Q8/SUV.htm";
    case 'wichita||rs3':
        return "https://www.audiwichita.com/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'wichita||rs7-hatchback':
        return "https://www.audiwichita.com/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'wichita||s3':
        return "https://www.audiwichita.com/showroom/2019/Audi/S3/Sedan.htm";
    case 'wichita||s4':
        return "https://www.audiwichita.com/showroom/2019/Audi/S4/Sedan.htm";
    case 'wichita||s5-cabriolet':
        return "https://www.audiwichita.com/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'wichita||s5-coupe':
        return "https://www.audiwichita.com/showroom/2019/Audi/S5/Coupe.htm";
    case 'wichita||s5-sportback':
        return "https://www.audiwichita.com/showroom/2019/Audi/S5/Sportback.htm";
    case 'wichita||s6':
        return "https://www.audiwichita.com/showroom/2019/Audi/S6/Sedan.htm";
    case 'wichita||s7-hatchback':
        return "https://www.audiwichita.com/showroom/2019/Audi/S7/Hatchback.htm";
    case 'wichita||s8':
        return "https://www.audiwichita.com/showroom/2019/Audi/S8/Sedan.htm";
    case 'wichita||tt-coupe':
        return "https://www.audiwichita.com/showroom/2019/Audi/TT/Coupe.htm";
    case 'wichita||tts-coupe':
        return "https://www.audiwichita.com/showroom/2019/Audi/TTS/Coupe.htm";
    case 'chicago||a6':
        return "https://www.audioffers.com/chicagoland/showroom/2020/Audi/A6/Sedan.htm";
    case 'cincinnati||a6':
        return "https://www.audioffers.com/cincinnati/showroom/2020/Audi/A6/Sedan.htm";
    case 'cleveland||a6':
        return "https://www.audioffers.com/cleveland/showroom/2020/Audi/A6/Sedan.htm";
    case 'columbus||a6':
        return "https://www.audioffers.com/columbus/showroom/2020/Audi/A6/Sedan.htm";
    case 'detroit||a6':
        return "https://www.audioffers.com/detroit/showroom/2020/Audi/A6/Sedan.htm";
    case 'grand-rapids||a6':
        return "https://www.audigrandrapids.com/showroom/2020/Audi/A6/Sedan.htm";
    case 'indianapolis||a6':
        return "https://www.audiindianapolis.com/showroom/2020/Audi/A6/Sedan.htm";
    case 'kansas-city||a6':
        return "http://www.audioffers.com/kansas-city/showroom/2020/Audi/A6/Sedan.htm?geoZip=64114";
    case 'louisville||a6':
        return "https://www.audilouisville.com/showroom/2020/Audi/A6/Sedan.htm";
    case 'minneapolis||a6':
        return "https://www.audioffers.com/twin-cities/showroom/2020/Audi/A6/Sedan.htm?geoZip=55109";
    case 'st-louis||a6':
        return "https://www.audioffers.com/st-louis/showroom/2020/Audi/A6/Sedan.htm";
    case 'toledo||a6':
        return "https://www.sylvaniaaudi.com/showroom/2020/Audi/A6/Sedan.htm";
    case 'wichita||a6':
        return "https://www.audiwichita.com/showroom/2020/Audi/A6/Sedan.htm";
    case 'chicago||a7-hatchback':
        return "https://www.audioffers.com/chicagoland/showroom/2020/Audi/A7/Hatchback.htm";
    case 'chicago||q3':
        return "https://www.audioffers.com/chicagoland/showroom/2020/Audi/Q3/SUV.htm";
    case 'chicago||q5':
        return "https://www.audioffers.com/chicagoland/showroom/2020/Audi/Q5/SUV.htm";
    case 'chicago||q8':
        return "https://www.audioffers.com/chicagoland/showroom/2020/Audi/Q8/SUV.htm";
    case 'cincinnati||a7-hatchback':
        return "https://www.audioffers.com/cincinnati/showroom/2020/Audi/A7/Hatchback.htm";
    case 'cincinnati||q3':
        return "https://www.audioffers.com/cincinnati/showroom/2020/Audi/Q3/SUV.htm";
    case 'cincinnati||q5':
        return "https://www.audioffers.com/cincinnati/showroom/2020/Audi/Q5/SUV.htm";
    case 'cincinnati||q8':
        return "https://www.audioffers.com/cincinnati/showroom/2020/Audi/Q8/SUV.htm";
    case 'cleveland||a7-hatchback':
        return "https://www.audioffers.com/cleveland/showroom/2020/Audi/A7/Hatchback.htm";
    case 'cleveland||q3':
        return "https://www.audioffers.com/cleveland/showroom/2020/Audi/Q3/SUV.htm";
    case 'cleveland||q5':
        return "https://www.audioffers.com/cleveland/showroom/2020/Audi/Q5/SUV.htm";
    case 'cleveland||q8':
        return "https://www.audioffers.com/cleveland/showroom/2020/Audi/Q8/SUV.htm";
    case 'columbus||a7-hatchback':
        return "https://www.audioffers.com/columbus/showroom/2020/Audi/A7/Hatchback.htm";
    case 'columbus||q3':
        return "https://www.audioffers.com/columbus/showroom/2020/Audi/Q3/SUV.htm";
    case 'columbus||q5':
        return "https://www.audioffers.com/columbus/showroom/2020/Audi/Q5/SUV.htm";
    case 'columbus||q8':
        return "https://www.audioffers.com/columbus/showroom/2020/Audi/Q8/SUV.htm";
    case 'detroit||a7-hatchback':
        return "https://www.audioffers.com/detroit/showroom/2020/Audi/A7/Hatchback.htm";
    case 'detroit||q3':
        return "https://www.audioffers.com/detroit/showroom/2020/Audi/Q3/SUV.htm";
    case 'detroit||q5':
        return "https://www.audioffers.com/detroit/showroom/2020/Audi/Q5/SUV.htm";
    case 'detroit||q8':
        return "https://www.audioffers.com/detroit/showroom/2020/Audi/Q8/SUV.htm";
    case 'grand-rapids||a7-hatchback':
        return "https://www.audigrandrapids.com/showroom/2020/Audi/A7/Hatchback.htm";
    case 'grand-rapids||q3':
        return "https://www.audigrandrapids.com/showroom/2020/Audi/Q3/SUV.htm";
    case 'grand-rapids||q5':
        return "https://www.audigrandrapids.com/showroom/2020/Audi/Q5/SUV.htm";
    case 'grand-rapids||q8':
        return "https://www.audigrandrapids.com/showroom/2020/Audi/Q8/SUV.htm";
    case 'indianapolis||a7-hatchback':
        return "https://www.audiindianapolis.com/showroom/2020/Audi/A7/Hatchback.htm";
    case 'indianapolis||q3':
        return "https://www.audiindianapolis.com/showroom/2020/Audi/Q3/SUV.htm";
    case 'indianapolis||q5':
        return "https://www.audiindianapolis.com/showroom/2020/Audi/Q5/SUV.htm";
    case 'indianapolis||q8':
        return "https://www.audiindianapolis.com/showroom/2020/Audi/Q8/SUV.htm";
    case 'kansas-city||a7-hatchback':
        return "http://www.audioffers.com/kansas-city/showroom/2020/Audi/A7/Hatchback.htm?geoZip=64114";
    case 'kansas-city||q3':
        return "http://www.audioffers.com/kansas-city/showroom/2020/Audi/Q3/SUV.htm?geoZip=64114";
    case 'kansas-city||q5':
        return "http://www.audioffers.com/kansas-city/showroom/2020/Audi/Q5/SUV.htm?geoZip=64114";
    case 'kansas-city||q8':
        return "http://www.audioffers.com/kansas-city/showroom/2020/Audi/Q8/SUV.htm?geoZip=64114";
    case 'louisville||a7-hatchback':
        return "https://www.audilouisville.com/showroom/2020/Audi/A7/Hatchback.htm";
    case 'louisville||q3':
        return "https://www.audilouisville.com/showroom/2020/Audi/Q3/SUV.htm";
    case 'louisville||q5':
        return "https://www.audilouisville.com/showroom/2020/Audi/Q5/SUV.htm";
    case 'louisville||q8':
        return "https://www.audilouisville.com/showroom/2020/Audi/Q8/SUV.htm";
    case 'minneapolis||a7-hatchback':
        return "https://www.audioffers.com/twin-cities/showroom/2020/Audi/A7/Hatchback.htm?geoZip=55109";
    case 'minneapolis||q3':
        return "https://www.audioffers.com/twin-cities/showroom/2020/Audi/Q3/SUV.htm?geoZip=55109";
    case 'minneapolis||q5':
        return "https://www.audioffers.com/twin-cities/showroom/2020/Audi/Q5/SUV.htm?geoZip=55109";
    case 'minneapolis||q8':
        return "https://www.audioffers.com/twin-cities/showroom/2020/Audi/Q8/SUV.htm?geoZip=55109";
    case 'st-louis||a7-hatchback':
        return "https://www.audioffers.com/st-louis/showroom/2020/Audi/A7/Hatchback.htm";
    case 'st-louis||q3':
        return "https://www.audioffers.com/st-louis/showroom/2020/Audi/Q3/SUV.htm";
    case 'st-louis||q5':
        return "https://www.audioffers.com/st-louis/showroom/2020/Audi/Q5/SUV.htm";
    case 'st-louis||q8':
        return "https://www.audioffers.com/st-louis/showroom/2020/Audi/Q8/SUV.htm";
    case 'toledo||a7-hatchback':
        return "https://www.sylvaniaaudi.com/showroom/2020/Audi/A7/Hatchback.htm";
    case 'toledo||q3':
        return "https://www.sylvaniaaudi.com/showroom/2020/Audi/Q3/SUV.htm";
    case 'toledo||q5':
        return "https://www.sylvaniaaudi.com/showroom/2020/Audi/Q5/SUV.htm";
    case 'toledo||q8':
        return "https://www.sylvaniaaudi.com/showroom/2020/Audi/Q8/SUV.htm";
    case 'wichita||a7-hatchback':
        return "https://www.audiwichita.com/showroom/2020/Audi/A7/Hatchback.htm";
    case 'wichita||q3':
        return "https://www.audiwichita.com/showroom/2020/Audi/Q3/SUV.htm";
    case 'wichita||q5':
        return "https://www.audiwichita.com/showroom/2020/Audi/Q5/SUV.htm";
    case 'wichita||q8':
        return "https://www.audiwichita.com/showroom/2020/Audi/Q8/SUV.htm";
    case 'chicago||s6':
        return "https://www.audioffers.com/chicagoland/showroom/2020/Audi/S6/Sedan.htm";
    case 'cincinnati||s6':
        return "https://www.audioffers.com/cincinnati/showroom/2020/Audi/S6/Sedan.htm";
    case 'cleveland||s6':
        return "https://www.audioffers.com/cleveland/showroom/2020/Audi/S6/Sedan.htm";
    case 'columbus||s6':
        return "https://www.audioffers.com/columbus/showroom/2020/Audi/S6/Sedan.htm";
    case 'detroit||s6':
        return "https://www.audioffers.com/detroit/showroom/2020/Audi/S6/Sedan.htm";
    case 'grand-rapids||s6':
        return "https://www.audigrandrapids.com/showroom/2020/Audi/S6/Sedan.htm";
    case 'indianapolis||s6':
        return "https://www.audiindianapolis.com/showroom/2020/Audi/S6/Sedan.htm";
    case 'kansas-city||s6':
        return "http://www.audioffers.com/kansas-city/showroom/2020/Audi/S6/Sedan.htm?geoZip=64114";
    case 'louisville||s6':
        return "https://www.audilouisville.com/showroom/2020/Audi/S6/Sedan.htm";
    case 'minneapolis||s6':
        return "https://www.audioffers.com/twin-cities/showroom/2020/Audi/S6/Sedan.htm?geoZip=55109";
    case 'st-louis||s6':
        return "https://www.audioffers.com/st-louis/showroom/2020/Audi/S6/Sedan.htm";
    case 'toledo||s6':
        return "https://www.sylvaniaaudi.com/showroom/2020/Audi/S6/Sedan.htm";
    case 'wichita||s6':
        return "https://www.audiwichita.com/showroom/2020/Audi/S6/Sedan.htm";
    default:
        return "https://www.audioffers.com";
    }
}

