console.log("loaded");
function getURL(urlKeyCode){
switch (urlKeyCode){
    case 'albuquerque||a3':
        return "http://www.audiabq.com/showroom/2019/Audi/A3/Sedan.htm";
    case 'albuquerque||a3-cabriolet':
        return "http://www.audiabq.com/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'albuquerque||a3-e-tron':
        return "http://www.audiabq.com/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'albuquerque||a4':
        return "http://www.audiabq.com/showroom/2019/Audi/A4/Sedan.htm";
    case 'albuquerque||a4-allroad':
        return "http://www.audiabq.com/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'albuquerque||a5':
        return "http://www.audiabq.com/showroom/2019/Audi/A5/Sedan.htm";
    case 'albuquerque||a5-cabriolet':
        return "http://www.audiabq.com/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'albuquerque||a5-coupe':
        return "http://www.audiabq.com/showroom/2019/Audi/A5/Coupe.htm";
    case 'albuquerque||a5-sportback':
        return "http://www.audiabq.com/showroom/2019/Audi/A5/Sportback.htm";
    case 'albuquerque||a6':
        return "http://www.audiabq.com/showroom/2019/Audi/A6/Sedan.htm";
    case 'albuquerque||a7':
        return "http://www.audiabq.com/showroom/2019/Audi/A7/Hatchback.htm";
    case 'albuquerque||a7-hatchback':
        return "http://www.audiabq.com/showroom/2019/Audi/A7/Hatchback.htm";
    case 'albuquerque||a8':
        return "http://www.audiabq.com/showroom/2019/Audi/A8/Sedan.htm";
    case 'albuquerque||q3':
        return "http://www.audiabq.com/showroom/2019/Audi/Q3/SUV.htm";
    case 'albuquerque||q5':
        return "http://www.audiabq.com/showroom/2019/Audi/Q5/SUV.htm";
    case 'albuquerque||q7':
        return "http://www.audiabq.com/showroom/2019/Audi/Q7/SUV.htm";
    case 'albuquerque||q8':
        return "http://www.audiabq.com/showroom/2019/Audi/Q8/SUV.htm";
    case 'albuquerque||rs3':
        return "http://www.audiabq.com/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'albuquerque||rs7-hatchback':
        return "http://www.audiabq.com/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'albuquerque||s3':
        return "http://www.audiabq.com/showroom/2019/Audi/S3/Sedan.htm";
    case 'albuquerque||s4':
        return "http://www.audiabq.com/showroom/2019/Audi/S4/Sedan.htm";
    case 'albuquerque||s5-cabriolet':
        return "http://www.audiabq.com/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'albuquerque||s5-coupe':
        return "http://www.audiabq.com/showroom/2019/Audi/S5/Coupe.htm";
    case 'albuquerque||s5-sportback':
        return "http://www.audiabq.com/showroom/2019/Audi/S5/Sportback.htm";
    case 'albuquerque||s6':
        return "http://www.audiabq.com/showroom/2019/Audi/S6/Sedan.htm";
    case 'albuquerque||s7-hatchback':
        return "http://www.audiabq.com/showroom/2019/Audi/S7/Hatchback.htm";
    case 'albuquerque||s8':
        return "http://www.audiabq.com/showroom/2019/Audi/S8/Sedan.htm";
    case 'albuquerque||tt-coupe':
        return "http://www.audiabq.com/showroom/2019/Audi/TT/Coupe.htm";
    case 'albuquerque||tts-coupe':
        return "http://www.audiabq.com/showroom/2019/Audi/TTS/Coupe.htm";
    case 'boise||a3':
        return "https://www.audiboise.com/showroom/2019/Audi/A3/Sedan.htm";
    case 'boise||a3-cabriolet':
        return "https://www.audiboise.com/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'boise||a3-e-tron':
        return "https://www.audiboise.com/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'boise||a4':
        return "https://www.audiboise.com/showroom/2019/Audi/A4/Sedan.htm";
    case 'boise||a4-allroad':
        return "https://www.audiboise.com/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'boise||a5':
        return "https://www.audiboise.com/showroom/2019/Audi/A5/Sedan.htm";
    case 'boise||a5-cabriolet':
        return "https://www.audiboise.com/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'boise||a5-coupe':
        return "https://www.audiboise.com/showroom/2019/Audi/A5/Coupe.htm";
    case 'boise||a5-sportback':
        return "https://www.audiboise.com/showroom/2019/Audi/A5/Sportback.htm";
    case 'boise||a6':
        return "https://www.audiboise.com/showroom/2019/Audi/A6/Sedan.htm";
    case 'boise||a7':
        return "https://www.audiboise.com/showroom/2019/Audi/A7/Hatchback.htm";
    case 'boise||a7-hatchback':
        return "https://www.audiboise.com/showroom/2019/Audi/A7/Hatchback.htm";
    case 'boise||a8':
        return "https://www.audiboise.com/showroom/2019/Audi/A8/Sedan.htm";
    case 'boise||q3':
        return "https://www.audiboise.com/showroom/2019/Audi/Q3/SUV.htm";
    case 'boise||q5':
        return "https://www.audiboise.com/showroom/2019/Audi/Q5/SUV.htm";
    case 'boise||q7':
        return "https://www.audiboise.com/showroom/2019/Audi/Q7/SUV.htm";
    case 'boise||q8':
        return "https://www.audiboise.com/showroom/2019/Audi/Q8/SUV.htm";
    case 'boise||rs3':
        return "https://www.audiboise.com/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'boise||rs7-hatchback':
        return "https://www.audiboise.com/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'boise||s3':
        return "https://www.audiboise.com/showroom/2019/Audi/S3/Sedan.htm";
    case 'boise||s4':
        return "https://www.audiboise.com/showroom/2019/Audi/S4/Sedan.htm";
    case 'boise||s5-cabriolet':
        return "https://www.audiboise.com/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'boise||s5-coupe':
        return "https://www.audiboise.com/showroom/2019/Audi/S5/Coupe.htm";
    case 'boise||s5-sportback':
        return "https://www.audiboise.com/showroom/2019/Audi/S5/Sportback.htm";
    case 'boise||s6':
        return "https://www.audiboise.com/showroom/2019/Audi/S6/Sedan.htm";
    case 'boise||s7-hatchback':
        return "https://www.audiboise.com/showroom/2019/Audi/S7/Hatchback.htm";
    case 'boise||s8':
        return "https://www.audiboise.com/showroom/2019/Audi/S8/Sedan.htm";
    case 'boise||tt-coupe':
        return "https://www.audiboise.com/showroom/2019/Audi/TT/Coupe.htm";
    case 'boise||tts-coupe':
        return "https://www.audiboise.com/showroom/2019/Audi/TTS/Coupe.htm";
    case 'colorado-springs||a3':
        return "https://www.audicoloradosprings.com/showroom/2019/Audi/A3/Sedan.htm";
    case 'colorado-springs||a3-cabriolet':
        return "https://www.audicoloradosprings.com/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'colorado-springs||a3-e-tron':
        return "https://www.audicoloradosprings.com/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'colorado-springs||a4':
        return "https://www.audicoloradosprings.com/showroom/2019/Audi/A4/Sedan.htm";
    case 'colorado-springs||a4-allroad':
        return "https://www.audicoloradosprings.com/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'colorado-springs||a5':
        return "https://www.audicoloradosprings.com/showroom/2019/Audi/A5/Sedan.htm";
    case 'colorado-springs||a5-cabriolet':
        return "https://www.audicoloradosprings.com/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'colorado-springs||a5-coupe':
        return "https://www.audicoloradosprings.com/showroom/2019/Audi/A5/Coupe.htm";
    case 'colorado-springs||a5-sportback':
        return "https://www.audicoloradosprings.com/showroom/2019/Audi/A5/Sportback.htm";
    case 'colorado-springs||a6':
        return "https://www.audicoloradosprings.com/showroom/2019/Audi/A6/Sedan.htm";
    case 'colorado-springs||a7':
        return "https://www.audicoloradosprings.com/showroom/2019/Audi/A7/Hatchback.htm";
    case 'colorado-springs||a7-hatchback':
        return "https://www.audicoloradosprings.com/showroom/2019/Audi/A7/Hatchback.htm";
    case 'colorado-springs||a8':
        return "https://www.audicoloradosprings.com/showroom/2019/Audi/A8/Sedan.htm";
    case 'colorado-springs||q3':
        return "https://www.audicoloradosprings.com/showroom/2019/Audi/Q3/SUV.htm";
    case 'colorado-springs||q5':
        return "https://www.audicoloradosprings.com/showroom/2019/Audi/Q5/SUV.htm";
    case 'colorado-springs||q7':
        return "https://www.audicoloradosprings.com/showroom/2019/Audi/Q7/SUV.htm";
    case 'colorado-springs||q8':
        return "https://www.audicoloradosprings.com/showroom/2019/Audi/Q8/SUV.htm";
    case 'colorado-springs||rs3':
        return "https://www.audicoloradosprings.com/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'colorado-springs||rs7-hatchback':
        return "https://www.audicoloradosprings.com/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'colorado-springs||s3':
        return "https://www.audicoloradosprings.com/showroom/2019/Audi/S3/Sedan.htm";
    case 'colorado-springs||s4':
        return "https://www.audicoloradosprings.com/showroom/2019/Audi/S4/Sedan.htm";
    case 'colorado-springs||s5-cabriolet':
        return "https://www.audicoloradosprings.com/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'colorado-springs||s5-coupe':
        return "https://www.audicoloradosprings.com/showroom/2019/Audi/S5/Coupe.htm";
    case 'colorado-springs||s5-sportback':
        return "https://www.audicoloradosprings.com/showroom/2019/Audi/S5/Sportback.htm";
    case 'colorado-springs||s6':
        return "https://www.audicoloradosprings.com/showroom/2019/Audi/S6/Sedan.htm";
    case 'colorado-springs||s7-hatchback':
        return "https://www.audicoloradosprings.com/showroom/2019/Audi/S7/Hatchback.htm";
    case 'colorado-springs||s8':
        return "https://www.audicoloradosprings.com/showroom/2019/Audi/S8/Sedan.htm";
    case 'colorado-springs||tt-coupe':
        return "https://www.audicoloradosprings.com/showroom/2019/Audi/TT/Coupe.htm";
    case 'colorado-springs||tts-coupe':
        return "https://www.audicoloradosprings.com/showroom/2019/Audi/TTS/Coupe.htm";
    case 'denver||a3':
        return "https://www.audioffers.com/colorado/showroom/2019/Audi/A3/Sedan.htm";
    case 'denver||a3-cabriolet':
        return "https://www.audioffers.com/colorado/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'denver||a3-e-tron':
        return "https://www.audioffers.com/colorado/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'denver||a4':
        return "https://www.audioffers.com/colorado/showroom/2019/Audi/A4/Sedan.htm";
    case 'denver||a4-allroad':
        return "https://www.audioffers.com/colorado/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'denver||a5':
        return "https://www.audioffers.com/colorado/showroom/2019/Audi/A5/Sedan.htm";
    case 'denver||a5-cabriolet':
        return "https://www.audioffers.com/colorado/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'denver||a5-coupe':
        return "https://www.audioffers.com/colorado/showroom/2019/Audi/A5/Coupe.htm";
    case 'denver||a5-sportback':
        return "https://www.audioffers.com/colorado/showroom/2019/Audi/A5/Sportback.htm";
    case 'denver||a6':
        return "https://www.audioffers.com/colorado/showroom/2019/Audi/A6/Sedan.htm";
    case 'denver||a7':
        return "https://www.audioffers.com/colorado/showroom/2019/Audi/A7/Hatchback.htm";
    case 'denver||a7-hatchback':
        return "https://www.audioffers.com/colorado/showroom/2019/Audi/A7/Hatchback.htm";
    case 'denver||a8':
        return "https://www.audioffers.com/colorado/showroom/2019/Audi/A8/Sedan.htm";
    case 'denver||q3':
        return "https://www.audioffers.com/colorado/showroom/2019/Audi/Q3/SUV.htm";
    case 'denver||q5':
        return "https://www.audioffers.com/colorado/showroom/2019/Audi/Q5/SUV.htm";
    case 'denver||q7':
        return "https://www.audioffers.com/colorado/showroom/2019/Audi/Q7/SUV.htm";
    case 'denver||q8':
        return "https://www.audioffers.com/colorado/showroom/2019/Audi/Q8/SUV.htm";
    case 'denver||rs3':
        return "https://www.audioffers.com/colorado/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'denver||rs7-hatchback':
        return "https://www.audioffers.com/colorado/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'denver||s3':
        return "https://www.audioffers.com/colorado/showroom/2019/Audi/S3/Sedan.htm";
    case 'denver||s4':
        return "https://www.audioffers.com/colorado/showroom/2019/Audi/S4/Sedan.htm";
    case 'denver||s5-cabriolet':
        return "https://www.audioffers.com/colorado/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'denver||s5-coupe':
        return "https://www.audioffers.com/colorado/showroom/2019/Audi/S5/Coupe.htm";
    case 'denver||s5-sportback':
        return "https://www.audioffers.com/colorado/showroom/2019/Audi/S5/Sportback.htm";
    case 'denver||s6':
        return "https://www.audioffers.com/colorado/showroom/2019/Audi/S6/Sedan.htm";
    case 'denver||s7-hatchback':
        return "https://www.audioffers.com/colorado/showroom/2019/Audi/S7/Hatchback.htm";
    case 'denver||s8':
        return "https://www.audioffers.com/colorado/showroom/2019/Audi/S8/Sedan.htm";
    case 'denver||tt-coupe':
        return "https://www.audioffers.com/colorado/showroom/2019/Audi/TT/Coupe.htm";
    case 'denver||tts-coupe':
        return "https://www.audioffers.com/colorado/showroom/2019/Audi/TTS/Coupe.htm";
    case 'honolulu||a3':
        return "https://www.audihonolulu.com/showroom/2019/Audi/A3/Sedan.htm";
    case 'honolulu||a3-cabriolet':
        return "https://www.audihonolulu.com/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'honolulu||a3-e-tron':
        return "https://www.audihonolulu.com/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'honolulu||a4':
        return "https://www.audihonolulu.com/showroom/2019/Audi/A4/Sedan.htm";
    case 'honolulu||a4-allroad':
        return "https://www.audihonolulu.com/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'honolulu||a5':
        return "https://www.audihonolulu.com/showroom/2019/Audi/A5/Sedan.htm";
    case 'honolulu||a5-cabriolet':
        return "https://www.audihonolulu.com/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'honolulu||a5-coupe':
        return "https://www.audihonolulu.com/showroom/2019/Audi/A5/Coupe.htm";
    case 'honolulu||a5-sportback':
        return "https://www.audihonolulu.com/showroom/2019/Audi/A5/Sportback.htm";
    case 'honolulu||a6':
        return "https://www.audihonolulu.com/showroom/2019/Audi/A6/Sedan.htm";
    case 'honolulu||a7':
        return "https://www.audihonolulu.com/showroom/2019/Audi/A7/Hatchback.htm";
    case 'honolulu||a7-hatchback':
        return "https://www.audihonolulu.com/showroom/2019/Audi/A7/Hatchback.htm";
    case 'honolulu||a8':
        return "https://www.audihonolulu.com/showroom/2019/Audi/A8/Sedan.htm";
    case 'honolulu||q3':
        return "https://www.audihonolulu.com/showroom/2019/Audi/Q3/SUV.htm";
    case 'honolulu||q5':
        return "https://www.audihonolulu.com/showroom/2019/Audi/Q5/SUV.htm";
    case 'honolulu||q7':
        return "https://www.audihonolulu.com/showroom/2019/Audi/Q7/SUV.htm";
    case 'honolulu||q8':
        return "https://www.audihonolulu.com/showroom/2019/Audi/Q8/SUV.htm";
    case 'honolulu||rs3':
        return "https://www.audihonolulu.com/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'honolulu||rs7-hatchback':
        return "https://www.audihonolulu.com/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'honolulu||s3':
        return "https://www.audihonolulu.com/showroom/2019/Audi/S3/Sedan.htm";
    case 'honolulu||s4':
        return "https://www.audihonolulu.com/showroom/2019/Audi/S4/Sedan.htm";
    case 'honolulu||s5-cabriolet':
        return "https://www.audihonolulu.com/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'honolulu||s5-coupe':
        return "https://www.audihonolulu.com/showroom/2019/Audi/S5/Coupe.htm";
    case 'honolulu||s5-sportback':
        return "https://www.audihonolulu.com/showroom/2019/Audi/S5/Sportback.htm";
    case 'honolulu||s6':
        return "https://www.audihonolulu.com/showroom/2019/Audi/S6/Sedan.htm";
    case 'honolulu||s7-hatchback':
        return "https://www.audihonolulu.com/showroom/2019/Audi/S7/Hatchback.htm";
    case 'honolulu||s8':
        return "https://www.audihonolulu.com/showroom/2019/Audi/S8/Sedan.htm";
    case 'honolulu||tt-coupe':
        return "https://www.audihonolulu.com/showroom/2019/Audi/TT/Coupe.htm";
    case 'honolulu||tts-coupe':
        return "https://www.audihonolulu.com/showroom/2019/Audi/TTS/Coupe.htm";
    case 'las-vegas||a3':
        return "https://www.audioffers.com/las-vegas/showroom/2019/Audi/A3/Sedan.htm";
    case 'las-vegas||a3-cabriolet':
        return "https://www.audioffers.com/las-vegas/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'las-vegas||a3-e-tron':
        return "https://www.audioffers.com/las-vegas/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'las-vegas||a4':
        return "https://www.audioffers.com/las-vegas/showroom/2019/Audi/A4/Sedan.htm";
    case 'las-vegas||a4-allroad':
        return "https://www.audioffers.com/las-vegas/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'las-vegas||a5':
        return "https://www.audioffers.com/las-vegas/showroom/2019/Audi/A5/Sedan.htm";
    case 'las-vegas||a5-cabriolet':
        return "https://www.audioffers.com/las-vegas/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'las-vegas||a5-coupe':
        return "https://www.audioffers.com/las-vegas/showroom/2019/Audi/A5/Coupe.htm";
    case 'las-vegas||a5-sportback':
        return "https://www.audioffers.com/las-vegas/showroom/2019/Audi/A5/Sportback.htm";
    case 'las-vegas||a6':
        return "https://www.audioffers.com/las-vegas/showroom/2019/Audi/A6/Sedan.htm";
    case 'las-vegas||a7':
        return "https://www.audioffers.com/las-vegas/showroom/2019/Audi/A7/Hatchback.htm";
    case 'las-vegas||a7-hatchback':
        return "https://www.audioffers.com/las-vegas/showroom/2019/Audi/A7/Hatchback.htm";
    case 'las-vegas||a8':
        return "https://www.audioffers.com/las-vegas/showroom/2019/Audi/A8/Sedan.htm";
    case 'las-vegas||q3':
        return "https://www.audioffers.com/las-vegas/showroom/2019/Audi/Q3/SUV.htm";
    case 'las-vegas||q5':
        return "https://www.audioffers.com/las-vegas/showroom/2019/Audi/Q5/SUV.htm";
    case 'las-vegas||q7':
        return "https://www.audioffers.com/las-vegas/showroom/2019/Audi/Q7/SUV.htm";
    case 'las-vegas||q8':
        return "https://www.audioffers.com/las-vegas/showroom/2019/Audi/Q8/SUV.htm";
    case 'las-vegas||rs3':
        return "https://www.audioffers.com/las-vegas/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'las-vegas||rs7-hatchback':
        return "https://www.audioffers.com/las-vegas/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'las-vegas||s3':
        return "https://www.audioffers.com/las-vegas/showroom/2019/Audi/S3/Sedan.htm";
    case 'las-vegas||s4':
        return "https://www.audioffers.com/las-vegas/showroom/2019/Audi/S4/Sedan.htm";
    case 'las-vegas||s5-cabriolet':
        return "https://www.audioffers.com/las-vegas/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'las-vegas||s5-coupe':
        return "https://www.audioffers.com/las-vegas/showroom/2019/Audi/S5/Coupe.htm";
    case 'las-vegas||s5-sportback':
        return "https://www.audioffers.com/las-vegas/showroom/2019/Audi/S5/Sportback.htm";
    case 'las-vegas||s6':
        return "https://www.audioffers.com/las-vegas/showroom/2019/Audi/S6/Sedan.htm";
    case 'las-vegas||s7-hatchback':
        return "https://www.audioffers.com/las-vegas/showroom/2019/Audi/S7/Hatchback.htm";
    case 'las-vegas||s8':
        return "https://www.audioffers.com/las-vegas/showroom/2019/Audi/S8/Sedan.htm";
    case 'las-vegas||tt-coupe':
        return "https://www.audioffers.com/las-vegas/showroom/2019/Audi/TT/Coupe.htm";
    case 'las-vegas||tts-coupe':
        return "https://www.audioffers.com/las-vegas/showroom/2019/Audi/TTS/Coupe.htm";
    case 'los-angeles||a3':
        return "https://www.audioffers.com/southern-california/showroom/2019/Audi/A3/Sedan.htm";
    case 'los-angeles||a3-cabriolet':
        return "https://www.audioffers.com/southern-california/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'los-angeles||a3-e-tron':
        return "https://www.audioffers.com/southern-california/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'los-angeles||a4':
        return "https://www.audioffers.com/southern-california/showroom/2019/Audi/A4/Sedan.htm";
    case 'los-angeles||a4-allroad':
        return "https://www.audioffers.com/southern-california/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'los-angeles||a5':
        return "https://www.audioffers.com/southern-california/showroom/2019/Audi/A5/Sedan.htm";
    case 'los-angeles||a5-cabriolet':
        return "https://www.audioffers.com/southern-california/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'los-angeles||a5-coupe':
        return "https://www.audioffers.com/southern-california/showroom/2019/Audi/A5/Coupe.htm";
    case 'los-angeles||a5-sportback':
        return "https://www.audioffers.com/southern-california/showroom/2019/Audi/A5/Sportback.htm";
    case 'los-angeles||a6':
        return "https://www.audioffers.com/southern-california/showroom/2019/Audi/A6/Sedan.htm";
    case 'los-angeles||a7':
        return "https://www.audioffers.com/southern-california/showroom/2019/Audi/A7/Hatchback.htm";
    case 'los-angeles||a7-hatchback':
        return "https://www.audioffers.com/southern-california/showroom/2019/Audi/A7/Hatchback.htm";
    case 'los-angeles||a8':
        return "https://www.audioffers.com/southern-california/showroom/2019/Audi/A8/Sedan.htm";
    case 'los-angeles||q3':
        return "https://www.audioffers.com/southern-california/showroom/2019/Audi/Q3/SUV.htm";
    case 'los-angeles||q5':
        return "https://www.audioffers.com/southern-california/showroom/2019/Audi/Q5/SUV.htm";
    case 'los-angeles||q7':
        return "https://www.audioffers.com/southern-california/showroom/2019/Audi/Q7/SUV.htm";
    case 'los-angeles||q8':
        return "https://www.audioffers.com/southern-california/showroom/2019/Audi/Q8/SUV.htm";
    case 'los-angeles||rs3':
        return "https://www.audioffers.com/southern-california/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'los-angeles||rs7-hatchback':
        return "https://www.audioffers.com/southern-california/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'los-angeles||s3':
        return "https://www.audioffers.com/southern-california/showroom/2019/Audi/S3/Sedan.htm";
    case 'los-angeles||s4':
        return "https://www.audioffers.com/southern-california/showroom/2019/Audi/S4/Sedan.htm";
    case 'los-angeles||s5-cabriolet':
        return "https://www.audioffers.com/southern-california/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'los-angeles||s5-coupe':
        return "https://www.audioffers.com/southern-california/showroom/2019/Audi/S5/Coupe.htm";
    case 'los-angeles||s5-sportback':
        return "https://www.audioffers.com/southern-california/showroom/2019/Audi/S5/Sportback.htm";
    case 'los-angeles||s6':
        return "https://www.audioffers.com/southern-california/showroom/2019/Audi/S6/Sedan.htm";
    case 'los-angeles||s7-hatchback':
        return "https://www.audioffers.com/southern-california/showroom/2019/Audi/S7/Hatchback.htm";
    case 'los-angeles||s8':
        return "https://www.audioffers.com/southern-california/showroom/2019/Audi/S8/Sedan.htm";
    case 'los-angeles||tt-coupe':
        return "https://www.audioffers.com/southern-california/showroom/2019/Audi/TT/Coupe.htm";
    case 'los-angeles||tts-coupe':
        return "https://www.audioffers.com/southern-california/showroom/2019/Audi/TTS/Coupe.htm";
    case 'palm-springs||a3':
        return "https://www.audiranchomirage.com/showroom/2019/Audi/A3/Sedan.htm";
    case 'palm-springs||a3-cabriolet':
        return "https://www.audiranchomirage.com/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'palm-springs||a3-e-tron':
        return "https://www.audiranchomirage.com/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'palm-springs||a4':
        return "https://www.audiranchomirage.com/showroom/2019/Audi/A4/Sedan.htm";
    case 'palm-springs||a4-allroad':
        return "https://www.audiranchomirage.com/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'palm-springs||a5':
        return "https://www.audiranchomirage.com/showroom/2019/Audi/A5/Sedan.htm";
    case 'palm-springs||a5-cabriolet':
        return "https://www.audiranchomirage.com/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'palm-springs||a5-coupe':
        return "https://www.audiranchomirage.com/showroom/2019/Audi/A5/Coupe.htm";
    case 'palm-springs||a5-sportback':
        return "https://www.audiranchomirage.com/showroom/2019/Audi/A5/Sportback.htm";
    case 'palm-springs||a6':
        return "https://www.audiranchomirage.com/showroom/2019/Audi/A6/Sedan.htm";
    case 'palm-springs||a7':
        return "https://www.audiranchomirage.com/showroom/2019/Audi/A7/Hatchback.htm";
    case 'palm-springs||a7-hatchback':
        return "https://www.audiranchomirage.com/showroom/2019/Audi/A7/Hatchback.htm";
    case 'palm-springs||a8':
        return "https://www.audiranchomirage.com/showroom/2019/Audi/A8/Sedan.htm";
    case 'palm-springs||q3':
        return "https://www.audiranchomirage.com/showroom/2019/Audi/Q3/SUV.htm";
    case 'palm-springs||q5':
        return "https://www.audiranchomirage.com/showroom/2019/Audi/Q5/SUV.htm";
    case 'palm-springs||q7':
        return "https://www.audiranchomirage.com/showroom/2019/Audi/Q7/SUV.htm";
    case 'palm-springs||q8':
        return "https://www.audiranchomirage.com/showroom/2019/Audi/Q8/SUV.htm";
    case 'palm-springs||rs3':
        return "https://www.audiranchomirage.com/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'palm-springs||rs7-hatchback':
        return "https://www.audiranchomirage.com/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'palm-springs||s3':
        return "https://www.audiranchomirage.com/showroom/2019/Audi/S3/Sedan.htm";
    case 'palm-springs||s4':
        return "https://www.audiranchomirage.com/showroom/2019/Audi/S4/Sedan.htm";
    case 'palm-springs||s5-cabriolet':
        return "https://www.audiranchomirage.com/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'palm-springs||s5-coupe':
        return "https://www.audiranchomirage.com/showroom/2019/Audi/S5/Coupe.htm";
    case 'palm-springs||s5-sportback':
        return "https://www.audiranchomirage.com/showroom/2019/Audi/S5/Sportback.htm";
    case 'palm-springs||s6':
        return "https://www.audiranchomirage.com/showroom/2019/Audi/S6/Sedan.htm";
    case 'palm-springs||s7-hatchback':
        return "https://www.audiranchomirage.com/showroom/2019/Audi/S7/Hatchback.htm";
    case 'palm-springs||s8':
        return "https://www.audiranchomirage.com/showroom/2019/Audi/S8/Sedan.htm";
    case 'palm-springs||tt-coupe':
        return "https://www.audiranchomirage.com/showroom/2019/Audi/TT/Coupe.htm";
    case 'palm-springs||tts-coupe':
        return "https://www.audiranchomirage.com/showroom/2019/Audi/TTS/Coupe.htm";
    case 'phoenix||a3':
        return "https://www.audioffers.com/arizona/showroom/2019/Audi/A3/Sedan.htm";
    case 'phoenix||a3-cabriolet':
        return "https://www.audioffers.com/arizona/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'phoenix||a3-e-tron':
        return "https://www.audioffers.com/arizona/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'phoenix||a4':
        return "https://www.audioffers.com/arizona/showroom/2019/Audi/A4/Sedan.htm";
    case 'phoenix||a4-allroad':
        return "https://www.audioffers.com/arizona/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'phoenix||a5':
        return "https://www.audioffers.com/arizona/showroom/2019/Audi/A5/Sedan.htm";
    case 'phoenix||a5-cabriolet':
        return "https://www.audioffers.com/arizona/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'phoenix||a5-coupe':
        return "https://www.audioffers.com/arizona/showroom/2019/Audi/A5/Coupe.htm";
    case 'phoenix||a5-sportback':
        return "https://www.audioffers.com/arizona/showroom/2019/Audi/A5/Sportback.htm";
    case 'phoenix||a6':
        return "https://www.audioffers.com/arizona/showroom/2019/Audi/A6/Sedan.htm";
    case 'phoenix||a7':
        return "https://www.audioffers.com/arizona/showroom/2019/Audi/A7/Hatchback.htm";
    case 'phoenix||a7-hatchback':
        return "https://www.audioffers.com/arizona/showroom/2019/Audi/A7/Hatchback.htm";
    case 'phoenix||a8':
        return "https://www.audioffers.com/arizona/showroom/2019/Audi/A8/Sedan.htm";
    case 'phoenix||q3':
        return "https://www.audioffers.com/arizona/showroom/2019/Audi/Q3/SUV.htm";
    case 'phoenix||q5':
        return "https://www.audioffers.com/arizona/showroom/2019/Audi/Q5/SUV.htm";
    case 'phoenix||q7':
        return "https://www.audioffers.com/arizona/showroom/2019/Audi/Q7/SUV.htm";
    case 'phoenix||q8':
        return "https://www.audioffers.com/arizona/showroom/2019/Audi/Q8/SUV.htm";
    case 'phoenix||rs3':
        return "https://www.audioffers.com/arizona/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'phoenix||rs7-hatchback':
        return "https://www.audioffers.com/arizona/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'phoenix||s3':
        return "https://www.audioffers.com/arizona/showroom/2019/Audi/S3/Sedan.htm";
    case 'phoenix||s4':
        return "https://www.audioffers.com/arizona/showroom/2019/Audi/S4/Sedan.htm";
    case 'phoenix||s5-cabriolet':
        return "https://www.audioffers.com/arizona/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'phoenix||s5-coupe':
        return "https://www.audioffers.com/arizona/showroom/2019/Audi/S5/Coupe.htm";
    case 'phoenix||s5-sportback':
        return "https://www.audioffers.com/arizona/showroom/2019/Audi/S5/Sportback.htm";
    case 'phoenix||s6':
        return "https://www.audioffers.com/arizona/showroom/2019/Audi/S6/Sedan.htm";
    case 'phoenix||s7-hatchback':
        return "https://www.audioffers.com/arizona/showroom/2019/Audi/S7/Hatchback.htm";
    case 'phoenix||s8':
        return "https://www.audioffers.com/arizona/showroom/2019/Audi/S8/Sedan.htm";
    case 'phoenix||tt-coupe':
        return "https://www.audioffers.com/arizona/showroom/2019/Audi/TT/Coupe.htm";
    case 'phoenix||tts-coupe':
        return "https://www.audioffers.com/arizona/showroom/2019/Audi/TTS/Coupe.htm";
    case 'portland||a3':
        return "https://www.audioffers.com/oregon/showroom/2019/Audi/A3/Sedan.htm";
    case 'portland||a3-cabriolet':
        return "https://www.audioffers.com/oregon/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'portland||a3-e-tron':
        return "https://www.audioffers.com/oregon/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'portland||a4':
        return "https://www.audioffers.com/oregon/showroom/2019/Audi/A4/Sedan.htm";
    case 'portland||a4-allroad':
        return "https://www.audioffers.com/oregon/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'portland||a5':
        return "https://www.audioffers.com/oregon/showroom/2019/Audi/A5/Sedan.htm";
    case 'portland||a5-cabriolet':
        return "https://www.audioffers.com/oregon/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'portland||a5-coupe':
        return "https://www.audioffers.com/oregon/showroom/2019/Audi/A5/Coupe.htm";
    case 'portland||a5-sportback':
        return "https://www.audioffers.com/oregon/showroom/2019/Audi/A5/Sportback.htm";
    case 'portland||a6':
        return "https://www.audioffers.com/oregon/showroom/2019/Audi/A6/Sedan.htm";
    case 'portland||a7':
        return "https://www.audioffers.com/oregon/showroom/2019/Audi/A7/Hatchback.htm";
    case 'portland||a7-hatchback':
        return "https://www.audioffers.com/oregon/showroom/2019/Audi/A7/Hatchback.htm";
    case 'portland||a8':
        return "https://www.audioffers.com/oregon/showroom/2019/Audi/A8/Sedan.htm";
    case 'portland||q3':
        return "https://www.audioffers.com/oregon/showroom/2019/Audi/Q3/SUV.htm";
    case 'portland||q5':
        return "https://www.audioffers.com/oregon/showroom/2019/Audi/Q5/SUV.htm";
    case 'portland||q7':
        return "https://www.audioffers.com/oregon/showroom/2019/Audi/Q7/SUV.htm";
    case 'portland||q8':
        return "https://www.audioffers.com/oregon/showroom/2019/Audi/Q8/SUV.htm";
    case 'portland||rs3':
        return "https://www.audioffers.com/oregon/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'portland||rs7-hatchback':
        return "https://www.audioffers.com/oregon/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'portland||s3':
        return "https://www.audioffers.com/oregon/showroom/2019/Audi/S3/Sedan.htm";
    case 'portland||s4':
        return "https://www.audioffers.com/oregon/showroom/2019/Audi/S4/Sedan.htm";
    case 'portland||s5-cabriolet':
        return "https://www.audioffers.com/oregon/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'portland||s5-coupe':
        return "https://www.audioffers.com/oregon/showroom/2019/Audi/S5/Coupe.htm";
    case 'portland||s5-sportback':
        return "https://www.audioffers.com/oregon/showroom/2019/Audi/S5/Sportback.htm";
    case 'portland||s6':
        return "https://www.audioffers.com/oregon/showroom/2019/Audi/S6/Sedan.htm";
    case 'portland||s7-hatchback':
        return "https://www.audioffers.com/oregon/showroom/2019/Audi/S7/Hatchback.htm";
    case 'portland||s8':
        return "https://www.audioffers.com/oregon/showroom/2019/Audi/S8/Sedan.htm";
    case 'portland||tt-coupe':
        return "https://www.audioffers.com/oregon/showroom/2019/Audi/TT/Coupe.htm";
    case 'portland||tts-coupe':
        return "https://www.audioffers.com/oregon/showroom/2019/Audi/TTS/Coupe.htm";
    case 'reno||a3':
        return "https://www.audirenotahoe.com/showroom/2019/Audi/A3/Sedan.htm";
    case 'reno||a3-cabriolet':
        return "https://www.audirenotahoe.com/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'reno||a3-e-tron':
        return "https://www.audirenotahoe.com/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'reno||a4':
        return "https://www.audirenotahoe.com/showroom/2019/Audi/A4/Sedan.htm";
    case 'reno||a4-allroad':
        return "https://www.audirenotahoe.com/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'reno||a5':
        return "https://www.audirenotahoe.com/showroom/2019/Audi/A5/Sedan.htm";
    case 'reno||a5-cabriolet':
        return "https://www.audirenotahoe.com/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'reno||a5-coupe':
        return "https://www.audirenotahoe.com/showroom/2019/Audi/A5/Coupe.htm";
    case 'reno||a5-sportback':
        return "https://www.audirenotahoe.com/showroom/2019/Audi/A5/Sportback.htm";
    case 'reno||a6':
        return "https://www.audirenotahoe.com/showroom/2019/Audi/A6/Sedan.htm";
    case 'reno||a7':
        return "https://www.audirenotahoe.com/showroom/2019/Audi/A7/Hatchback.htm";
    case 'reno||a7-hatchback':
        return "https://www.audirenotahoe.com/showroom/2019/Audi/A7/Hatchback.htm";
    case 'reno||a8':
        return "https://www.audirenotahoe.com/showroom/2019/Audi/A8/Sedan.htm";
    case 'reno||q3':
        return "https://www.audirenotahoe.com/showroom/2019/Audi/Q3/SUV.htm";
    case 'reno||q5':
        return "https://www.audirenotahoe.com/showroom/2019/Audi/Q5/SUV.htm";
    case 'reno||q7':
        return "https://www.audirenotahoe.com/showroom/2019/Audi/Q7/SUV.htm";
    case 'reno||q8':
        return "https://www.audirenotahoe.com/showroom/2019/Audi/Q8/SUV.htm";
    case 'reno||rs3':
        return "https://www.audirenotahoe.com/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'reno||rs7-hatchback':
        return "https://www.audirenotahoe.com/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'reno||s3':
        return "https://www.audirenotahoe.com/showroom/2019/Audi/S3/Sedan.htm";
    case 'reno||s4':
        return "https://www.audirenotahoe.com/showroom/2019/Audi/S4/Sedan.htm";
    case 'reno||s5-cabriolet':
        return "https://www.audirenotahoe.com/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'reno||s5-coupe':
        return "https://www.audirenotahoe.com/showroom/2019/Audi/S5/Coupe.htm";
    case 'reno||s5-sportback':
        return "https://www.audirenotahoe.com/showroom/2019/Audi/S5/Sportback.htm";
    case 'reno||s6':
        return "https://www.audirenotahoe.com/showroom/2019/Audi/S6/Sedan.htm";
    case 'reno||s7-hatchback':
        return "https://www.audirenotahoe.com/showroom/2019/Audi/S7/Hatchback.htm";
    case 'reno||s8':
        return "https://www.audirenotahoe.com/showroom/2019/Audi/S8/Sedan.htm";
    case 'reno||tt-coupe':
        return "https://www.audirenotahoe.com/showroom/2019/Audi/TT/Coupe.htm";
    case 'reno||tts-coupe':
        return "https://www.audirenotahoe.com/showroom/2019/Audi/TTS/Coupe.htm";
    case 'sacramento||a3':
        return "https://www.audioffers.com/sacramento/showroom/2019/Audi/A3/Sedan.htm";
    case 'sacramento||a3-cabriolet':
        return "https://www.audioffers.com/sacramento/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'sacramento||a3-e-tron':
        return "https://www.audioffers.com/sacramento/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'sacramento||a4':
        return "https://www.audioffers.com/sacramento/showroom/2019/Audi/A4/Sedan.htm";
    case 'sacramento||a4-allroad':
        return "https://www.audioffers.com/sacramento/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'sacramento||a5':
        return "https://www.audioffers.com/sacramento/showroom/2019/Audi/A5/Sedan.htm";
    case 'sacramento||a5-cabriolet':
        return "https://www.audioffers.com/sacramento/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'sacramento||a5-coupe':
        return "https://www.audioffers.com/sacramento/showroom/2019/Audi/A5/Coupe.htm";
    case 'sacramento||a5-sportback':
        return "https://www.audioffers.com/sacramento/showroom/2019/Audi/A5/Sportback.htm";
    case 'sacramento||a6':
        return "https://www.audioffers.com/sacramento/showroom/2019/Audi/A6/Sedan.htm";
    case 'sacramento||a7':
        return "https://www.audioffers.com/sacramento/showroom/2019/Audi/A7/Hatchback.htm";
    case 'sacramento||a7-hatchback':
        return "https://www.audioffers.com/sacramento/showroom/2019/Audi/A7/Hatchback.htm";
    case 'sacramento||a8':
        return "https://www.audioffers.com/sacramento/showroom/2019/Audi/A8/Sedan.htm";
    case 'sacramento||q3':
        return "https://www.audioffers.com/sacramento/showroom/2019/Audi/Q3/SUV.htm";
    case 'sacramento||q5':
        return "https://www.audioffers.com/sacramento/showroom/2019/Audi/Q5/SUV.htm";
    case 'sacramento||q7':
        return "https://www.audioffers.com/sacramento/showroom/2019/Audi/Q7/SUV.htm";
    case 'sacramento||q8':
        return "https://www.audioffers.com/sacramento/showroom/2019/Audi/Q8/SUV.htm";
    case 'sacramento||rs3':
        return "https://www.audioffers.com/sacramento/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'sacramento||rs7-hatchback':
        return "https://www.audioffers.com/sacramento/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'sacramento||s3':
        return "https://www.audioffers.com/sacramento/showroom/2019/Audi/S3/Sedan.htm";
    case 'sacramento||s4':
        return "https://www.audioffers.com/sacramento/showroom/2019/Audi/S4/Sedan.htm";
    case 'sacramento||s5-cabriolet':
        return "https://www.audioffers.com/sacramento/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'sacramento||s5-coupe':
        return "https://www.audioffers.com/sacramento/showroom/2019/Audi/S5/Coupe.htm";
    case 'sacramento||s5-sportback':
        return "https://www.audioffers.com/sacramento/showroom/2019/Audi/S5/Sportback.htm";
    case 'sacramento||s6':
        return "https://www.audioffers.com/sacramento/showroom/2019/Audi/S6/Sedan.htm";
    case 'sacramento||s7-hatchback':
        return "https://www.audioffers.com/sacramento/showroom/2019/Audi/S7/Hatchback.htm";
    case 'sacramento||s8':
        return "https://www.audioffers.com/sacramento/showroom/2019/Audi/S8/Sedan.htm";
    case 'sacramento||tt-coupe':
        return "https://www.audioffers.com/sacramento/showroom/2019/Audi/TT/Coupe.htm";
    case 'sacramento||tts-coupe':
        return "https://www.audioffers.com/sacramento/showroom/2019/Audi/TTS/Coupe.htm";
    case 'salt-lake-city||a3':
        return "https://www.audioffers.com/utah/showroom/2019/Audi/A3/Sedan.htm";
    case 'salt-lake-city||a3-cabriolet':
        return "https://www.audioffers.com/utah/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'salt-lake-city||a3-e-tron':
        return "https://www.audioffers.com/utah/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'salt-lake-city||a4':
        return "https://www.audioffers.com/utah/showroom/2019/Audi/A4/Sedan.htm";
    case 'salt-lake-city||a4-allroad':
        return "https://www.audioffers.com/utah/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'salt-lake-city||a5':
        return "https://www.audioffers.com/utah/showroom/2019/Audi/A5/Sedan.htm";
    case 'salt-lake-city||a5-cabriolet':
        return "https://www.audioffers.com/utah/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'salt-lake-city||a5-coupe':
        return "https://www.audioffers.com/utah/showroom/2019/Audi/A5/Coupe.htm";
    case 'salt-lake-city||a5-sportback':
        return "https://www.audioffers.com/utah/showroom/2019/Audi/A5/Sportback.htm";
    case 'salt-lake-city||a6':
        return "https://www.audioffers.com/utah/showroom/2019/Audi/A6/Sedan.htm";
    case 'salt-lake-city||a7':
        return "https://www.audioffers.com/utah/showroom/2019/Audi/A7/Hatchback.htm";
    case 'salt-lake-city||a7-hatchback':
        return "https://www.audioffers.com/utah/showroom/2019/Audi/A7/Hatchback.htm";
    case 'salt-lake-city||a8':
        return "https://www.audioffers.com/utah/showroom/2019/Audi/A8/Sedan.htm";
    case 'salt-lake-city||q3':
        return "https://www.audioffers.com/utah/showroom/2019/Audi/Q3/SUV.htm";
    case 'salt-lake-city||q5':
        return "https://www.audioffers.com/utah/showroom/2019/Audi/Q5/SUV.htm";
    case 'salt-lake-city||q7':
        return "https://www.audioffers.com/utah/showroom/2019/Audi/Q7/SUV.htm";
    case 'salt-lake-city||q8':
        return "https://www.audioffers.com/utah/showroom/2019/Audi/Q8/SUV.htm";
    case 'salt-lake-city||rs3':
        return "https://www.audioffers.com/utah/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'salt-lake-city||rs7-hatchback':
        return "https://www.audioffers.com/utah/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'salt-lake-city||s3':
        return "https://www.audioffers.com/utah/showroom/2019/Audi/S3/Sedan.htm";
    case 'salt-lake-city||s4':
        return "https://www.audioffers.com/utah/showroom/2019/Audi/S4/Sedan.htm";
    case 'salt-lake-city||s5-cabriolet':
        return "https://www.audioffers.com/utah/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'salt-lake-city||s5-coupe':
        return "https://www.audioffers.com/utah/showroom/2019/Audi/S5/Coupe.htm";
    case 'salt-lake-city||s5-sportback':
        return "https://www.audioffers.com/utah/showroom/2019/Audi/S5/Sportback.htm";
    case 'salt-lake-city||s6':
        return "https://www.audioffers.com/utah/showroom/2019/Audi/S6/Sedan.htm";
    case 'salt-lake-city||s7-hatchback':
        return "https://www.audioffers.com/utah/showroom/2019/Audi/S7/Hatchback.htm";
    case 'salt-lake-city||s8':
        return "https://www.audioffers.com/utah/showroom/2019/Audi/S8/Sedan.htm";
    case 'salt-lake-city||tt-coupe':
        return "https://www.audioffers.com/utah/showroom/2019/Audi/TT/Coupe.htm";
    case 'salt-lake-city||tts-coupe':
        return "https://www.audioffers.com/utah/showroom/2019/Audi/TTS/Coupe.htm";
    case 'san-diego||a3':
        return "https://www.audioffers.com/san-diego/showroom/2019/Audi/A3/Sedan.htm";
    case 'san-diego||a3-cabriolet':
        return "https://www.audioffers.com/san-diego/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'san-diego||a3-e-tron':
        return "https://www.audioffers.com/san-diego/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'san-diego||a4':
        return "https://www.audioffers.com/san-diego/showroom/2019/Audi/A4/Sedan.htm";
    case 'san-diego||a4-allroad':
        return "https://www.audioffers.com/san-diego/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'san-diego||a5':
        return "https://www.audioffers.com/san-diego/showroom/2019/Audi/A5/Sedan.htm";
    case 'san-diego||a5-cabriolet':
        return "https://www.audioffers.com/san-diego/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'san-diego||a5-coupe':
        return "https://www.audioffers.com/san-diego/showroom/2019/Audi/A5/Coupe.htm";
    case 'san-diego||a5-sportback':
        return "https://www.audioffers.com/san-diego/showroom/2019/Audi/A5/Sportback.htm";
    case 'san-diego||a6':
        return "https://www.audioffers.com/san-diego/showroom/2019/Audi/A6/Sedan.htm";
    case 'san-diego||a7':
        return "https://www.audioffers.com/san-diego/showroom/2019/Audi/A7/Hatchback.htm";
    case 'san-diego||a7-hatchback':
        return "https://www.audioffers.com/san-diego/showroom/2019/Audi/A7/Hatchback.htm";
    case 'san-diego||a8':
        return "https://www.audioffers.com/san-diego/showroom/2019/Audi/A8/Sedan.htm";
    case 'san-diego||q3':
        return "https://www.audioffers.com/san-diego/showroom/2019/Audi/Q3/SUV.htm";
    case 'san-diego||q5':
        return "https://www.audioffers.com/san-diego/showroom/2019/Audi/Q5/SUV.htm";
    case 'san-diego||q7':
        return "https://www.audioffers.com/san-diego/showroom/2019/Audi/Q7/SUV.htm";
    case 'san-diego||q8':
        return "https://www.audioffers.com/san-diego/showroom/2019/Audi/Q8/SUV.htm";
    case 'san-diego||rs3':
        return "https://www.audioffers.com/san-diego/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'san-diego||rs7-hatchback':
        return "https://www.audioffers.com/san-diego/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'san-diego||s3':
        return "https://www.audioffers.com/san-diego/showroom/2019/Audi/S3/Sedan.htm";
    case 'san-diego||s4':
        return "https://www.audioffers.com/san-diego/showroom/2019/Audi/S4/Sedan.htm";
    case 'san-diego||s5-cabriolet':
        return "https://www.audioffers.com/san-diego/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'san-diego||s5-coupe':
        return "https://www.audioffers.com/san-diego/showroom/2019/Audi/S5/Coupe.htm";
    case 'san-diego||s5-sportback':
        return "https://www.audioffers.com/san-diego/showroom/2019/Audi/S5/Sportback.htm";
    case 'san-diego||s6':
        return "https://www.audioffers.com/san-diego/showroom/2019/Audi/S6/Sedan.htm";
    case 'san-diego||s7-hatchback':
        return "https://www.audioffers.com/san-diego/showroom/2019/Audi/S7/Hatchback.htm";
    case 'san-diego||s8':
        return "https://www.audioffers.com/san-diego/showroom/2019/Audi/S8/Sedan.htm";
    case 'san-diego||tt-coupe':
        return "https://www.audioffers.com/san-diego/showroom/2019/Audi/TT/Coupe.htm";
    case 'san-diego||tts-coupe':
        return "https://www.audioffers.com/san-diego/showroom/2019/Audi/TTS/Coupe.htm";
    case 'san-francisco||a3':
        return "https://www.audioffers.com/san-francisco/showroom/2019/Audi/A3/Sedan.htm";
    case 'san-francisco||a3-cabriolet':
        return "https://www.audioffers.com/san-francisco/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'san-francisco||a3-e-tron':
        return "https://www.audioffers.com/san-francisco/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'san-francisco||a4':
        return "https://www.audioffers.com/san-francisco/showroom/2019/Audi/A4/Sedan.htm";
    case 'san-francisco||a4-allroad':
        return "https://www.audioffers.com/san-francisco/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'san-francisco||a5':
        return "https://www.audioffers.com/san-francisco/showroom/2019/Audi/A5/Sedan.htm";
    case 'san-francisco||a5-cabriolet':
        return "https://www.audioffers.com/san-francisco/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'san-francisco||a5-coupe':
        return "https://www.audioffers.com/san-francisco/showroom/2019/Audi/A5/Coupe.htm";
    case 'san-francisco||a5-sportback':
        return "https://www.audioffers.com/san-francisco/showroom/2019/Audi/A5/Sportback.htm";
    case 'san-francisco||a6':
        return "https://www.audioffers.com/san-francisco/showroom/2019/Audi/A6/Sedan.htm";
    case 'san-francisco||a7':
        return "https://www.audioffers.com/san-francisco/showroom/2019/Audi/A7/Hatchback.htm";
    case 'san-francisco||a7-hatchback':
        return "https://www.audioffers.com/san-francisco/showroom/2019/Audi/A7/Hatchback.htm";
    case 'san-francisco||a8':
        return "https://www.audioffers.com/san-francisco/showroom/2019/Audi/A8/Sedan.htm";
    case 'san-francisco||q3':
        return "https://www.audioffers.com/san-francisco/showroom/2019/Audi/Q3/SUV.htm";
    case 'san-francisco||q5':
        return "https://www.audioffers.com/san-francisco/showroom/2019/Audi/Q5/SUV.htm";
    case 'san-francisco||q7':
        return "https://www.audioffers.com/san-francisco/showroom/2019/Audi/Q7/SUV.htm";
    case 'san-francisco||q8':
        return "https://www.audioffers.com/san-francisco/showroom/2019/Audi/Q8/SUV.htm";
    case 'san-francisco||rs3':
        return "https://www.audioffers.com/san-francisco/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'san-francisco||rs7-hatchback':
        return "https://www.audioffers.com/san-francisco/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'san-francisco||s3':
        return "https://www.audioffers.com/san-francisco/showroom/2019/Audi/S3/Sedan.htm";
    case 'san-francisco||s4':
        return "https://www.audioffers.com/san-francisco/showroom/2019/Audi/S4/Sedan.htm";
    case 'san-francisco||s5-cabriolet':
        return "https://www.audioffers.com/san-francisco/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'san-francisco||s5-coupe':
        return "https://www.audioffers.com/san-francisco/showroom/2019/Audi/S5/Coupe.htm";
    case 'san-francisco||s5-sportback':
        return "https://www.audioffers.com/san-francisco/showroom/2019/Audi/S5/Sportback.htm";
    case 'san-francisco||s6':
        return "https://www.audioffers.com/san-francisco/showroom/2019/Audi/S6/Sedan.htm";
    case 'san-francisco||s7-hatchback':
        return "https://www.audioffers.com/san-francisco/showroom/2019/Audi/S7/Hatchback.htm";
    case 'san-francisco||s8':
        return "https://www.audioffers.com/san-francisco/showroom/2019/Audi/S8/Sedan.htm";
    case 'san-francisco||tt-coupe':
        return "https://www.audioffers.com/san-francisco/showroom/2019/Audi/TT/Coupe.htm";
    case 'san-francisco||tts-coupe':
        return "https://www.audioffers.com/san-francisco/showroom/2019/Audi/TTS/Coupe.htm";
    case 'santa-barbara||a3':
        return "https://www.audisantabarbara.com/showroom/2019/Audi/A3/Sedan.htm";
    case 'santa-barbara||a3-cabriolet':
        return "https://www.audisantabarbara.com/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'santa-barbara||a3-e-tron':
        return "https://www.audisantabarbara.com/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'santa-barbara||a4':
        return "https://www.audisantabarbara.com/showroom/2019/Audi/A4/Sedan.htm";
    case 'santa-barbara||a4-allroad':
        return "https://www.audisantabarbara.com/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'santa-barbara||a5':
        return "https://www.audisantabarbara.com/showroom/2019/Audi/A5/Sedan.htm";
    case 'santa-barbara||a5-cabriolet':
        return "https://www.audisantabarbara.com/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'santa-barbara||a5-coupe':
        return "https://www.audisantabarbara.com/showroom/2019/Audi/A5/Coupe.htm";
    case 'santa-barbara||a5-sportback':
        return "https://www.audisantabarbara.com/showroom/2019/Audi/A5/Sportback.htm";
    case 'santa-barbara||a6':
        return "https://www.audisantabarbara.com/showroom/2019/Audi/A6/Sedan.htm";
    case 'santa-barbara||a7':
        return "https://www.audisantabarbara.com/showroom/2019/Audi/A7/Hatchback.htm";
    case 'santa-barbara||a7-hatchback':
        return "https://www.audisantabarbara.com/showroom/2019/Audi/A7/Hatchback.htm";
    case 'santa-barbara||a8':
        return "https://www.audisantabarbara.com/showroom/2019/Audi/A8/Sedan.htm";
    case 'santa-barbara||q3':
        return "https://www.audisantabarbara.com/showroom/2019/Audi/Q3/SUV.htm";
    case 'santa-barbara||q5':
        return "https://www.audisantabarbara.com/showroom/2019/Audi/Q5/SUV.htm";
    case 'santa-barbara||q7':
        return "https://www.audisantabarbara.com/showroom/2019/Audi/Q7/SUV.htm";
    case 'santa-barbara||q8':
        return "https://www.audisantabarbara.com/showroom/2019/Audi/Q8/SUV.htm";
    case 'santa-barbara||rs3':
        return "https://www.audisantabarbara.com/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'santa-barbara||rs7-hatchback':
        return "https://www.audisantabarbara.com/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'santa-barbara||s3':
        return "https://www.audisantabarbara.com/showroom/2019/Audi/S3/Sedan.htm";
    case 'santa-barbara||s4':
        return "https://www.audisantabarbara.com/showroom/2019/Audi/S4/Sedan.htm";
    case 'santa-barbara||s5-cabriolet':
        return "https://www.audisantabarbara.com/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'santa-barbara||s5-coupe':
        return "https://www.audisantabarbara.com/showroom/2019/Audi/S5/Coupe.htm";
    case 'santa-barbara||s5-sportback':
        return "https://www.audisantabarbara.com/showroom/2019/Audi/S5/Sportback.htm";
    case 'santa-barbara||s6':
        return "https://www.audisantabarbara.com/showroom/2019/Audi/S6/Sedan.htm";
    case 'santa-barbara||s7-hatchback':
        return "https://www.audisantabarbara.com/showroom/2019/Audi/S7/Hatchback.htm";
    case 'santa-barbara||s8':
        return "https://www.audisantabarbara.com/showroom/2019/Audi/S8/Sedan.htm";
    case 'santa-barbara||tt-coupe':
        return "https://www.audisantabarbara.com/showroom/2019/Audi/TT/Coupe.htm";
    case 'santa-barbara||tts-coupe':
        return "https://www.audisantabarbara.com/showroom/2019/Audi/TTS/Coupe.htm";
    case 'seattle||a3':
        return "https://www.audioffers.com/puget-sound/showroom/2019/Audi/A3/Sedan.htm";
    case 'seattle||a3-cabriolet':
        return "https://www.audioffers.com/puget-sound/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'seattle||a3-e-tron':
        return "https://www.audioffers.com/puget-sound/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'seattle||a4':
        return "https://www.audioffers.com/puget-sound/showroom/2019/Audi/A4/Sedan.htm";
    case 'seattle||a4-allroad':
        return "https://www.audioffers.com/puget-sound/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'seattle||a5':
        return "https://www.audioffers.com/puget-sound/showroom/2019/Audi/A5/Sedan.htm";
    case 'seattle||a5-cabriolet':
        return "https://www.audioffers.com/puget-sound/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'seattle||a5-coupe':
        return "https://www.audioffers.com/puget-sound/showroom/2019/Audi/A5/Coupe.htm";
    case 'seattle||a5-sportback':
        return "https://www.audioffers.com/puget-sound/showroom/2019/Audi/A5/Sportback.htm";
    case 'seattle||a6':
        return "https://www.audioffers.com/puget-sound/showroom/2019/Audi/A6/Sedan.htm";
    case 'seattle||a7':
        return "https://www.audioffers.com/puget-sound/showroom/2019/Audi/A7/Hatchback.htm";
    case 'seattle||a7-hatchback':
        return "https://www.audioffers.com/puget-sound/showroom/2019/Audi/A7/Hatchback.htm";
    case 'seattle||a8':
        return "https://www.audioffers.com/puget-sound/showroom/2019/Audi/A8/Sedan.htm";
    case 'seattle||q3':
        return "https://www.audioffers.com/puget-sound/showroom/2019/Audi/Q3/SUV.htm";
    case 'seattle||q5':
        return "https://www.audioffers.com/puget-sound/showroom/2019/Audi/Q5/SUV.htm";
    case 'seattle||q7':
        return "https://www.audioffers.com/puget-sound/showroom/2019/Audi/Q7/SUV.htm";
    case 'seattle||q8':
        return "https://www.audioffers.com/puget-sound/showroom/2019/Audi/Q8/SUV.htm";
    case 'seattle||rs3':
        return "https://www.audioffers.com/puget-sound/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'seattle||rs7-hatchback':
        return "https://www.audioffers.com/puget-sound/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'seattle||s3':
        return "https://www.audioffers.com/puget-sound/showroom/2019/Audi/S3/Sedan.htm";
    case 'seattle||s4':
        return "https://www.audioffers.com/puget-sound/showroom/2019/Audi/S4/Sedan.htm";
    case 'seattle||s5-cabriolet':
        return "https://www.audioffers.com/puget-sound/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'seattle||s5-coupe':
        return "https://www.audioffers.com/puget-sound/showroom/2019/Audi/S5/Coupe.htm";
    case 'seattle||s5-sportback':
        return "https://www.audioffers.com/puget-sound/showroom/2019/Audi/S5/Sportback.htm";
    case 'seattle||s6':
        return "https://www.audioffers.com/puget-sound/showroom/2019/Audi/S6/Sedan.htm";
    case 'seattle||s7-hatchback':
        return "https://www.audioffers.com/puget-sound/showroom/2019/Audi/S7/Hatchback.htm";
    case 'seattle||s8':
        return "https://www.audioffers.com/puget-sound/showroom/2019/Audi/S8/Sedan.htm";
    case 'seattle||tt-coupe':
        return "https://www.audioffers.com/puget-sound/showroom/2019/Audi/TT/Coupe.htm";
    case 'seattle||tts-coupe':
        return "https://www.audioffers.com/puget-sound/showroom/2019/Audi/TTS/Coupe.htm";
    case 'spokane||a3':
        return "https://www.audispokane.com/showroom/2019/Audi/A3/Sedan.htm";
    case 'spokane||a3-cabriolet':
        return "https://www.audispokane.com/showroom/2019/Audi/A3/Cabriolet.htm";
    case 'spokane||a3-e-tron':
        return "https://www.audispokane.com/showroom/2019/Audi/A3+e-tron/Hatchback.htm";
    case 'spokane||a4':
        return "https://www.audispokane.com/showroom/2019/Audi/A4/Sedan.htm";
    case 'spokane||a4-allroad':
        return "https://www.audispokane.com/showroom/2019/Audi/A4+allroad/Wagon.htm";
    case 'spokane||a5':
        return "https://www.audispokane.com/showroom/2019/Audi/A5/Sedan.htm";
    case 'spokane||a5-cabriolet':
        return "https://www.audispokane.com/showroom/2019/Audi/A5/Cabriolet.htm";
    case 'spokane||a5-coupe':
        return "https://www.audispokane.com/showroom/2019/Audi/A5/Coupe.htm";
    case 'spokane||a5-sportback':
        return "https://www.audispokane.com/showroom/2019/Audi/A5/Sportback.htm";
    case 'spokane||a6':
        return "https://www.audispokane.com/showroom/2019/Audi/A6/Sedan.htm";
    case 'spokane||a7':
        return "https://www.audispokane.com/showroom/2019/Audi/A7/Hatchback.htm";
    case 'spokane||a7-hatchback':
        return "https://www.audispokane.com/showroom/2019/Audi/A7/Hatchback.htm";
    case 'spokane||a8':
        return "https://www.audispokane.com/showroom/2019/Audi/A8/Sedan.htm";
    case 'spokane||q3':
        return "https://www.audispokane.com/showroom/2019/Audi/Q3/SUV.htm";
    case 'spokane||q5':
        return "https://www.audispokane.com/showroom/2019/Audi/Q5/SUV.htm";
    case 'spokane||q7':
        return "https://www.audispokane.com/showroom/2019/Audi/Q7/SUV.htm";
    case 'spokane||q8':
        return "https://www.audispokane.com/showroom/2019/Audi/Q8/SUV.htm";
    case 'spokane||rs3':
        return "https://www.audispokane.com/showroom/2019/Audi/RS+3/Sedan.htm";
    case 'spokane||rs7-hatchback':
        return "https://www.audispokane.com/showroom/2019/Audi/RS+7/Hatchback.htm";
    case 'spokane||s3':
        return "https://www.audispokane.com/showroom/2019/Audi/S3/Sedan.htm";
    case 'spokane||s4':
        return "https://www.audispokane.com/showroom/2019/Audi/S4/Sedan.htm";
    case 'spokane||s5-cabriolet':
        return "https://www.audispokane.com/showroom/2019/Audi/S5/Cabriolet.htm";
    case 'spokane||s5-coupe':
        return "https://www.audispokane.com/showroom/2019/Audi/S5/Coupe.htm";
    case 'spokane||s5-sportback':
        return "https://www.audispokane.com/showroom/2019/Audi/S5/Sportback.htm";
    case 'spokane||s6':
        return "https://www.audispokane.com/showroom/2019/Audi/S6/Sedan.htm";
    case 'spokane||s7-hatchback':
        return "https://www.audispokane.com/showroom/2019/Audi/S7/Hatchback.htm";
    case 'spokane||s8':
        return "https://www.audispokane.com/showroom/2019/Audi/S8/Sedan.htm";
    case 'spokane||tt-coupe':
        return "https://www.audispokane.com/showroom/2019/Audi/TT/Coupe.htm";
    case 'spokane||tts-coupe':
        return "https://www.audispokane.com/showroom/2019/Audi/TTS/Coupe.htm";
    case 'albuquerque||a6':
        return "http://www.audiabq.com/showroom/2020/Audi/A6/Sedan.htm";
    case 'boise||a6':
        return "https://www.audiboise.com/showroom/2020/Audi/A6/Sedan.htm";
    case 'colorado-springs||a6':
        return "https://www.audicoloradosprings.com/showroom/2020/Audi/A6/Sedan.htm";
    case 'denver||a6':
        return "https://www.audioffers.com/colorado/showroom/2020/Audi/A6/Sedan.htm";
    case 'honolulu||a6':
        return "https://www.audihonolulu.com/showroom/2020/Audi/A6/Sedan.htm";
    case 'las-vegas||a6':
        return "https://www.audioffers.com/las-vegas/showroom/2020/Audi/A6/Sedan.htm";
    case 'los-angeles||a6':
        return "https://www.audioffers.com/southern-california/showroom/2020/Audi/A6/Sedan.htm";
    case 'palm-springs||a6':
        return "https://www.audiranchomirage.com/showroom/2020/Audi/A6/Sedan.htm";
    case 'phoenix||a6':
        return "https://www.audioffers.com/arizona/showroom/2020/Audi/A6/Sedan.htm";
    case 'portland||a6':
        return "https://www.audioffers.com/oregon/showroom/2020/Audi/A6/Sedan.htm";
    case 'reno||a6':
        return "https://www.audirenotahoe.com/showroom/2020/Audi/A6/Sedan.htm";
    case 'sacramento||a6':
        return "https://www.audioffers.com/sacramento/showroom/2020/Audi/A6/Sedan.htm";
    case 'salt-lake-city||a6':
        return "https://www.audioffers.com/utah/showroom/2020/Audi/A6/Sedan.htm";
    case 'san-diego||a6':
        return "https://www.audioffers.com/san-diego/showroom/2020/Audi/A6/Sedan.htm";
    case 'san-francisco||a6':
        return "https://www.audioffers.com/san-francisco/showroom/2020/Audi/A6/Sedan.htm";
    case 'santa-barbara||a6':
        return "https://www.audisantabarbara.com/showroom/2020/Audi/A6/Sedan.htm";
    case 'seattle||a6':
        return "https://www.audioffers.com/puget-sound/showroom/2020/Audi/A6/Sedan.htm";
    case 'spokane||a6':
        return "https://www.audispokane.com/showroom/2020/Audi/A6/Sedan.htm";
    case 'albuquerque||a7-hatchback':
        return "http://www.audiabq.com/showroom/2020/Audi/A7/Hatchback.htm";
    case 'albuquerque||q3':
        return "http://www.audiabq.com/showroom/2020/Audi/Q3/SUV.htm";
    case 'albuquerque||q5':
        return "http://www.audiabq.com/showroom/2020/Audi/Q5/SUV.htm";
    case 'albuquerque||q8':
        return "http://www.audiabq.com/showroom/2020/Audi/Q8/SUV.htm";
    case 'boise||a7-hatchback':
        return "https://www.audiboise.com/showroom/2020/Audi/A7/Hatchback.htm";
    case 'boise||q3':
        return "https://www.audiboise.com/showroom/2020/Audi/Q3/SUV.htm";
    case 'boise||q5':
        return "https://www.audiboise.com/showroom/2020/Audi/Q5/SUV.htm";
    case 'boise||q8':
        return "https://www.audiboise.com/showroom/2020/Audi/Q8/SUV.htm";
    case 'colorado-springs||a7-hatchback':
        return "https://www.audicoloradosprings.com/showroom/2020/Audi/A7/Hatchback.htm";
    case 'colorado-springs||q3':
        return "https://www.audicoloradosprings.com/showroom/2020/Audi/Q3/SUV.htm";
    case 'colorado-springs||q5':
        return "https://www.audicoloradosprings.com/showroom/2020/Audi/Q5/SUV.htm";
    case 'colorado-springs||q8':
        return "https://www.audicoloradosprings.com/showroom/2020/Audi/Q8/SUV.htm";
    case 'denver||a7-hatchback':
        return "https://www.audioffers.com/colorado/showroom/2020/Audi/A7/Hatchback.htm";
    case 'denver||q3':
        return "https://www.audioffers.com/colorado/showroom/2020/Audi/Q3/SUV.htm";
    case 'denver||q5':
        return "https://www.audioffers.com/colorado/showroom/2020/Audi/Q5/SUV.htm";
    case 'denver||q8':
        return "https://www.audioffers.com/colorado/showroom/2020/Audi/Q8/SUV.htm";
    case 'honolulu||a7-hatchback':
        return "https://www.audihonolulu.com/showroom/2020/Audi/A7/Hatchback.htm";
    case 'honolulu||q3':
        return "https://www.audihonolulu.com/showroom/2020/Audi/Q3/SUV.htm";
    case 'honolulu||q5':
        return "https://www.audihonolulu.com/showroom/2020/Audi/Q5/SUV.htm";
    case 'honolulu||q8':
        return "https://www.audihonolulu.com/showroom/2020/Audi/Q8/SUV.htm";
    case 'las-vegas||a7-hatchback':
        return "https://www.audioffers.com/las-vegas/showroom/2020/Audi/A7/Hatchback.htm";
    case 'las-vegas||q3':
        return "https://www.audioffers.com/las-vegas/showroom/2020/Audi/Q3/SUV.htm";
    case 'las-vegas||q5':
        return "https://www.audioffers.com/las-vegas/showroom/2020/Audi/Q5/SUV.htm";
    case 'las-vegas||q8':
        return "https://www.audioffers.com/las-vegas/showroom/2020/Audi/Q8/SUV.htm";
    case 'los-angeles||a7-hatchback':
        return "https://www.audioffers.com/southern-california/showroom/2020/Audi/A7/Hatchback.htm";
    case 'los-angeles||q3':
        return "https://www.audioffers.com/southern-california/showroom/2020/Audi/Q3/SUV.htm";
    case 'los-angeles||q5':
        return "https://www.audioffers.com/southern-california/showroom/2020/Audi/Q5/SUV.htm";
    case 'los-angeles||q8':
        return "https://www.audioffers.com/southern-california/showroom/2020/Audi/Q8/SUV.htm";
    case 'palm-springs||a7-hatchback':
        return "https://www.audiranchomirage.com/showroom/2020/Audi/A7/Hatchback.htm";
    case 'palm-springs||q3':
        return "https://www.audiranchomirage.com/showroom/2020/Audi/Q3/SUV.htm";
    case 'palm-springs||q5':
        return "https://www.audiranchomirage.com/showroom/2020/Audi/Q5/SUV.htm";
    case 'palm-springs||q8':
        return "https://www.audiranchomirage.com/showroom/2020/Audi/Q8/SUV.htm";
    case 'phoenix||a7-hatchback':
        return "https://www.audioffers.com/arizona/showroom/2020/Audi/A7/Hatchback.htm";
    case 'phoenix||q3':
        return "https://www.audioffers.com/arizona/showroom/2020/Audi/Q3/SUV.htm";
    case 'phoenix||q5':
        return "https://www.audioffers.com/arizona/showroom/2020/Audi/Q5/SUV.htm";
    case 'phoenix||q8':
        return "https://www.audioffers.com/arizona/showroom/2020/Audi/Q8/SUV.htm";
    case 'portland||a7-hatchback':
        return "https://www.audioffers.com/oregon/showroom/2020/Audi/A7/Hatchback.htm";
    case 'portland||q3':
        return "https://www.audioffers.com/oregon/showroom/2020/Audi/Q3/SUV.htm";
    case 'portland||q5':
        return "https://www.audioffers.com/oregon/showroom/2020/Audi/Q5/SUV.htm";
    case 'portland||q8':
        return "https://www.audioffers.com/oregon/showroom/2020/Audi/Q8/SUV.htm";
    case 'reno||a7-hatchback':
        return "https://www.audirenotahoe.com/showroom/2020/Audi/A7/Hatchback.htm";
    case 'reno||q3':
        return "https://www.audirenotahoe.com/showroom/2020/Audi/Q3/SUV.htm";
    case 'reno||q5':
        return "https://www.audirenotahoe.com/showroom/2020/Audi/Q5/SUV.htm";
    case 'reno||q8':
        return "https://www.audirenotahoe.com/showroom/2020/Audi/Q8/SUV.htm";
    case 'sacramento||a7-hatchback':
        return "https://www.audioffers.com/sacramento/showroom/2020/Audi/A7/Hatchback.htm";
    case 'sacramento||q3':
        return "https://www.audioffers.com/sacramento/showroom/2020/Audi/Q3/SUV.htm";
    case 'sacramento||q5':
        return "https://www.audioffers.com/sacramento/showroom/2020/Audi/Q5/SUV.htm";
    case 'sacramento||q8':
        return "https://www.audioffers.com/sacramento/showroom/2020/Audi/Q8/SUV.htm";
    case 'salt-lake-city||a7-hatchback':
        return "https://www.audioffers.com/utah/showroom/2020/Audi/A7/Hatchback.htm";
    case 'salt-lake-city||q3':
        return "https://www.audioffers.com/utah/showroom/2020/Audi/Q3/SUV.htm";
    case 'salt-lake-city||q5':
        return "https://www.audioffers.com/utah/showroom/2020/Audi/Q5/SUV.htm";
    case 'salt-lake-city||q8':
        return "https://www.audioffers.com/utah/showroom/2020/Audi/Q8/SUV.htm";
    case 'san-diego||a7-hatchback':
        return "https://www.audioffers.com/san-diego/showroom/2020/Audi/A7/Hatchback.htm";
    case 'san-diego||q3':
        return "https://www.audioffers.com/san-diego/showroom/2020/Audi/Q3/SUV.htm";
    case 'san-diego||q5':
        return "https://www.audioffers.com/san-diego/showroom/2020/Audi/Q5/SUV.htm";
    case 'san-diego||q8':
        return "https://www.audioffers.com/san-diego/showroom/2020/Audi/Q8/SUV.htm";
    case 'san-francisco||a7-hatchback':
        return "https://www.audioffers.com/san-francisco/showroom/2020/Audi/A7/Hatchback.htm";
    case 'san-francisco||q3':
        return "https://www.audioffers.com/san-francisco/showroom/2020/Audi/Q3/SUV.htm";
    case 'san-francisco||q5':
        return "https://www.audioffers.com/san-francisco/showroom/2020/Audi/Q5/SUV.htm";
    case 'san-francisco||q8':
        return "https://www.audioffers.com/san-francisco/showroom/2020/Audi/Q8/SUV.htm";
    case 'santa-barbara||a7-hatchback':
        return "https://www.audisantabarbara.com/showroom/2020/Audi/A7/Hatchback.htm";
    case 'santa-barbara||q3':
        return "https://www.audisantabarbara.com/showroom/2020/Audi/Q3/SUV.htm";
    case 'santa-barbara||q5':
        return "https://www.audisantabarbara.com/showroom/2020/Audi/Q5/SUV.htm";
    case 'santa-barbara||q8':
        return "https://www.audisantabarbara.com/showroom/2020/Audi/Q8/SUV.htm";
    case 'seattle||a7-hatchback':
        return "https://www.audioffers.com/puget-sound/showroom/2020/Audi/A7/Hatchback.htm";
    case 'seattle||q3':
        return "https://www.audioffers.com/puget-sound/showroom/2020/Audi/Q3/SUV.htm";
    case 'seattle||q5':
        return "https://www.audioffers.com/puget-sound/showroom/2020/Audi/Q5/SUV.htm";
    case 'seattle||q8':
        return "https://www.audioffers.com/puget-sound/showroom/2020/Audi/Q8/SUV.htm";
    case 'spokane||a7-hatchback':
        return "https://www.audispokane.com/showroom/2020/Audi/A7/Hatchback.htm";
    case 'spokane||q3':
        return "https://www.audispokane.com/showroom/2020/Audi/Q3/SUV.htm";
    case 'spokane||q5':
        return "https://www.audispokane.com/showroom/2020/Audi/Q5/SUV.htm";
    case 'spokane||q8':
        return "https://www.audispokane.com/showroom/2020/Audi/Q8/SUV.htm";
    case 'albuquerque||s6':
        return "http://www.audiabq.com/showroom/2020/Audi/S6/Sedan.htm";
    case 'boise||s6':
        return "https://www.audiboise.com/showroom/2020/Audi/S6/Sedan.htm";
    case 'colorado-springs||s6':
        return "https://www.audicoloradosprings.com/showroom/2020/Audi/S6/Sedan.htm";
    case 'denver||s6':
        return "https://www.audioffers.com/colorado/showroom/2020/Audi/S6/Sedan.htm";
    case 'honolulu||s6':
        return "https://www.audihonolulu.com/showroom/2020/Audi/S6/Sedan.htm";
    case 'las-vegas||s6':
        return "https://www.audioffers.com/las-vegas/showroom/2020/Audi/S6/Sedan.htm";
    case 'los-angeles||s6':
        return "https://www.audioffers.com/southern-california/showroom/2020/Audi/S6/Sedan.htm";
    case 'palm-springs||s6':
        return "https://www.audiranchomirage.com/showroom/2020/Audi/S6/Sedan.htm";
    case 'phoenix||s6':
        return "https://www.audioffers.com/arizona/showroom/2020/Audi/S6/Sedan.htm";
    case 'portland||s6':
        return "https://www.audioffers.com/oregon/showroom/2020/Audi/S6/Sedan.htm";
    case 'reno||s6':
        return "https://www.audirenotahoe.com/showroom/2020/Audi/S6/Sedan.htm";
    case 'sacramento||s6':
        return "https://www.audioffers.com/sacramento/showroom/2020/Audi/S6/Sedan.htm";
    case 'salt-lake-city||s6':
        return "https://www.audioffers.com/utah/showroom/2020/Audi/S6/Sedan.htm";
    case 'san-diego||s6':
        return "https://www.audioffers.com/san-diego/showroom/2020/Audi/S6/Sedan.htm";
    case 'san-francisco||s6':
        return "https://www.audioffers.com/san-francisco/showroom/2020/Audi/S6/Sedan.htm";
    case 'santa-barbara||s6':
        return "https://www.audisantabarbara.com/showroom/2020/Audi/S6/Sedan.htm";
    case 'seattle||s6':
        return "https://www.audioffers.com/puget-sound/showroom/2020/Audi/S6/Sedan.htm";
    case 'spokane||s6':
        return "https://www.audispokane.com/showroom/2020/Audi/S6/Sedan.htm";
    default:
        return "https://audiusa.com";
    }
}

